-- Per-routine catch-up analysis window (owner directive 2026-07-25, in response to the 2026-07-23/24
-- connector outage: missed days were never covered because each routine's next run only looked at
-- "today"/its own fixed lookback). Project: stock-trading-498512. Apply after bigquery/10_observability.sql
-- (ops.run_log) and bigquery/18_stack_review_fixes.sql (state.go_without_order, redefined below) -- no
-- other dependency; deliberately does NOT read state.cadence_watch / state.cadence_period_watch /
-- state.catchup_available so it can never inherit their same-day/same-period/catchup-safe scoping
-- limits (see header note below).
--
-- WHY THIS EXISTS. Every existing cadence view answers "did routine X miss its CURRENT slot" (state.
-- cadence_watch: today; state.cadence_period_watch: this week/month/quarter/year; state.trigger_
-- attestation: a coarse multi-period overdue threshold) and their alarms are DECOUPLED from what a
-- routine actually reads when it runs -- verified 2026-07-23/24: a 2-day connector outage meant D1..D3/
-- AR_att/AR_orc/W4/W5/etc. simply lost that day's evidence forever once their fixed lookback window
-- rolled forward, even though ops.alerts' missed_run rows for those days had themselves already silently
-- auto-resolved by aging out (see ops.sp_auto_resolve_alerts Rule 2, bigquery/34_alert_lifecycle.sql --
-- resolves on EITHER a later completion OR simply on the alert turning >1 day stale, whichever comes
-- first -- so "the alert cleared" is never proof the missed window was actually analyzed).
--
-- THIS VIEW answers a different, decision-agnostic question for every routine unconditionally, every
-- time it runs: "as of right now, how far back does my OWN evidence/analysis window need to reach?"
-- window_start_ts = the timestamp of my own last completed run, or (if I have never completed) a
-- cadence-sized fallback. DECISIONS made during the run stay current-session-scoped (nobody retroactively
-- places an order) -- only the EVIDENCE window widens. A routine's own Task_Plan preamble step reads its
-- one row here at start and folds window_start_ts into whatever it queries (Daily.md scan range, decision_
-- log lookback, etc.) -- wiring that read-and-fold-in step into Claude_Task_Plan.md's preamble and into
-- each routine's fixed-window prose is a SEPARATE follow-up, not part of this file. BEST-EFFORT / NON-
-- GATING by design (mirrors the OPS0 "must never be blocked" rule): a routine that cannot read this view
-- (BigQuery unreachable, view missing) falls back to its own existing cadence-default lookback and notes
-- that it did so -- it must never fail or halt on this view's absence.
--
-- BLINDING IS UNCHANGED. This view only widens HOW FAR BACK IN TIME a routine's evidence window reaches
-- -- it says nothing about, and never restricts, WHICH sources a routine may read (AR_att's strict
-- blinding, M1a's file-boundary blinding, etc. are untouched).
--
-- ROUTINE LIST: ops/cadence.yaml's `routines:` block (32 ids) is the sole source of truth. No existing
-- BigQuery object carries {routine, monitor_class} for all 31 including the 4 queue_driven ids (AR_att/
-- AR_orc/SL2/SL5) -- bigquery/12's and bigquery/24's UNNEST lists both deliberately EXCLUDE queue_driven
-- (not calendar-predictable), and bigquery/15's ops.routine_catalog has all 32 ids but no monitor_class
-- column at all. So the `routines` CTE below is GENERATED by scripts/gen_routine_lists.py (--write) from
-- ops/cadence.yaml, a 4th marker region alongside its existing bigquery/12/15/24 regions -- do NOT
-- hand-edit the STRUCT rows between the BEGIN/END GENERATED ROUTINE LIST markers; edit ops/cadence.yaml
-- and re-run `python scripts/gen_routine_lists.py --write` instead. `python scripts/gen_routine_lists.py
-- --check` (CI-gating) fails the build if this region drifts from ops/cadence.yaml.
--
-- FALLBACK WINDOW (cadence-default, used only when a routine has NEVER logged a completed run): daily
-- classes (daily_trading/daily_all) -> 1 day; weekly_sun -> 7 days; monthly_ftd -> 31 days; quarterly_ftd
-- -> 92 days; annual_ftd -> 366 days. queue_driven (AR_att/AR_orc/SL2/SL5) is NOT one of the schema's
-- named calendar classes -- it is a DELIBERATE, called-out design choice here to give it the same 1-day
-- fallback as the daily tier, matching its "checked daily, fires only if due" cadence (ops/cadence.yaml:
-- AR_att/AR_orc/SL2/SL5 all have `schedule: "daily; if ... due<=today"`). This is NOT dictated by any
-- existing spec and should be confirmed, not assumed, before this view is treated as final.
--
-- ID-SEPARATOR NORMALIZATION: joins on REGEXP_REPLACE(routine, r'[·._-]', ''), the same normalization
-- state.instruction_drift uses (bigquery/15_routine_catalog.sql, RUNBOOK §28), so legacy AR·att/AR·orc
-- middle-dot rows (2026-06-20..07-02 in ops.run_log) fold onto the current ASCII AR_att/AR_orc keys
-- instead of being silently dropped from the MAX(log_ts) computation.
--
-- SYNTHETIC-ROW SAFETY: the routines CTE is a closed, generated list -- NOT `SELECT DISTINCT routine
-- FROM ops.run_log` -- specifically so synthetic markers written by fire-drill/self-heal procedures
-- (FIRE_DRILL_ORDER_GUARD, FIRE_DRILL_ALERT_LATCH, FIRE_DRILL_ALERT_RESOLVE, FIRE_DRILL_DEP,
-- FIRE_DRILL_DEP_CONSUMER, SELFHEAL_RUN_LOG -- all confirmed live in ops.run_log) never appear as phantom
-- "routines" with their own (meaningless) catch-up windows.
--
-- TIMEZONE: deliberately NOT wrapped in DATETIME(..., 'America/Denver') anywhere -- unlike state.cadence_
-- watch's wall-clock 21:00 MT DEADLINE GUARD, this view has no deadline semantics at all, just a rolling
-- elapsed-time lookback from CURRENT_TIMESTAMP() (a UTC instant), so there is no DST edge to get wrong.
--
-- NO CAP on window_days: a routine that silently broke for months before finally completing again would
-- get an arbitrarily large window here (bounded only by its own run_log history). Not addressed by the
-- 2026-07-25 directive as scoped; a future safety valve (e.g. cap at N x its own cadence default) is a
-- design call for whoever wires this into the routines' actual evidence-gathering steps, not assumed here.
CREATE OR REPLACE VIEW `stock-trading-498512.state.routine_catchup_window` AS
WITH routines AS (
  -- GENERATED (scripts/gen_routine_lists.py --write, from ops/cadence.yaml, file order), ALL 32 ids
  -- incl. the 4 queue_driven ones. Do NOT hand-edit -- see header note above.
  SELECT * FROM UNNEST([
    -- BEGIN GENERATED ROUTINE LIST (scripts/gen_routine_lists.py --write; do not hand-edit)
    STRUCT('D1' AS routine, 'daily_trading' AS monitor_class),
    STRUCT('D2a' AS routine, 'daily_trading' AS monitor_class),
    STRUCT('D2' AS routine, 'daily_trading' AS monitor_class),
    STRUCT('D3' AS routine, 'daily_all' AS monitor_class),
    STRUCT('OPS0' AS routine, 'daily_all' AS monitor_class),
    STRUCT('OPS1' AS routine, 'daily_all' AS monitor_class),
    STRUCT('OPS2' AS routine, 'daily_all' AS monitor_class),
    STRUCT('SL3' AS routine, 'daily_trading' AS monitor_class),
    STRUCT('AR_att' AS routine, 'queue_driven' AS monitor_class),
    STRUCT('AR_orc' AS routine, 'queue_driven' AS monitor_class),
    STRUCT('SL2' AS routine, 'queue_driven' AS monitor_class),
    STRUCT('SL5' AS routine, 'queue_driven' AS monitor_class),
    STRUCT('W1' AS routine, 'weekly_sun' AS monitor_class),
    STRUCT('W2' AS routine, 'weekly_sun' AS monitor_class),
    STRUCT('W3' AS routine, 'weekly_sun' AS monitor_class),
    STRUCT('W4' AS routine, 'weekly_sun' AS monitor_class),
    STRUCT('W5' AS routine, 'weekly_sun' AS monitor_class),
    STRUCT('M1a' AS routine, 'monthly_ftd' AS monitor_class),
    STRUCT('M1b' AS routine, 'monthly_ftd' AS monitor_class),
    STRUCT('M2' AS routine, 'monthly_ftd' AS monitor_class),
    STRUCT('M3' AS routine, 'monthly_ftd' AS monitor_class),
    STRUCT('M4' AS routine, 'monthly_ftd' AS monitor_class),
    STRUCT('M5' AS routine, 'monthly_ftd' AS monitor_class),
    STRUCT('SL4' AS routine, 'monthly_ftd' AS monitor_class),
    STRUCT('Q1' AS routine, 'quarterly_ftd' AS monitor_class),
    STRUCT('Q2' AS routine, 'quarterly_ftd' AS monitor_class),
    STRUCT('Q3' AS routine, 'quarterly_ftd' AS monitor_class),
    STRUCT('Q4' AS routine, 'quarterly_ftd' AS monitor_class),
    STRUCT('SL1' AS routine, 'quarterly_ftd' AS monitor_class),
    STRUCT('A1' AS routine, 'annual_ftd' AS monitor_class),
    STRUCT('A2' AS routine, 'annual_ftd' AS monitor_class),
    STRUCT('A3' AS routine, 'annual_ftd' AS monitor_class)
  -- END GENERATED ROUTINE LIST
  ])
),
last_completed AS (
  -- Latest 'completed' log_ts per routine, id-separator-normalized (RUNBOOK §28 convention) so legacy
  -- AR·att/AR·orc middle-dot rows fold onto the current AR_att/AR_orc keys instead of being invisible.
  SELECT
    REGEXP_REPLACE(routine, r'[·._-]', '') AS routine_norm,
    MAX(log_ts) AS last_completed_ts
  FROM `stock-trading-498512.ops.run_log`
  WHERE status = 'completed'
  GROUP BY routine_norm
),
joined AS (
  SELECT
    r.routine,
    r.monitor_class,
    lc.last_completed_ts,
    lc.last_completed_ts IS NULL AS never_completed,
    -- Cadence-default fallback, in whole days -- used only when never_completed. queue_driven's fallback
    -- (1 day) is a design choice, not a named class in the brief -- see header note.
    CASE r.monitor_class
      WHEN 'daily_trading' THEN 1
      WHEN 'daily_all'     THEN 1
      WHEN 'weekly_sun'    THEN 7
      WHEN 'monthly_ftd'   THEN 31
      WHEN 'quarterly_ftd' THEN 92
      WHEN 'annual_ftd'    THEN 366
      WHEN 'queue_driven'  THEN 1
      ELSE 31   -- defensive: an unrecognized class should never occur (routines CTE is closed/generated)
    END AS fallback_days
  FROM routines r
  LEFT JOIN last_completed lc
    ON lc.routine_norm = REGEXP_REPLACE(r.routine, r'[·._-]', '')
)
SELECT
  routine,
  monitor_class,
  last_completed_ts,
  never_completed,
  fallback_days,
  -- The raw cadence-default fallback instant (always computed, for transparency/debugging), independent
  -- of whether it actually gets used below.
  TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL fallback_days DAY) AS cadence_fallback_window_start_ts,
  -- The window every routine actually reads: its own last completion, or the cadence fallback if it has
  -- never completed.
  COALESCE(
    last_completed_ts,
    TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL fallback_days DAY)
  ) AS window_start_ts,
  -- Elapsed size of that window in (fractional) days, for quick human/dashboard reading.
  ROUND(
    TIMESTAMP_DIFF(
      CURRENT_TIMESTAMP(),
      COALESCE(last_completed_ts, TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL fallback_days DAY)),
      MINUTE
    ) / 1440.0, 2
  ) AS window_days,
  CURRENT_TIMESTAMP() AS checked_at
FROM joined
ORDER BY routine;

-- ============================================================================
-- state.go_without_order -- D3 catch-up-window redefinition (owner directive 2026-07-25).
-- SUPERSEDES the state.go_without_order view definition in bigquery/18_stack_review_fixes.sql (D3 --
-- staging-completeness surface, RUNBOOK §25). Every column, join, and the two NOT EXISTS blocks below
-- are copied byte-for-byte from that original definition -- the ONLY change is the window predicate
-- that bounds `go_decisions.entry_date`.
--
-- ORIGINAL BEHAVIOUR (bigquery/18): a fixed `entry_date >= DATE_SUB(CURRENT_DATE('America/Denver'),
-- INTERVAL 2 DAY)` lookback (~36h in Claude_Task_Plan.md's D3 prose -- see that file's GO-WITHOUT-ORDER
-- self-check bullet). That fixed window meant a GO logged while D3 itself was down for multiple days
-- (e.g. the 2026-07-23/24 connector outage) could age out of the window before D3 ever ran again to
-- review it -- a genuine go_without_order candidate silently missed forever, not just delayed.
--
-- NEW BEHAVIOUR: the window is now GREATEST(2 days, days since D3's own last completed ops.run_log
-- run) -- FLOORED at the original ~36h/2-day lookback (it never narrows below what bigquery/18 always
-- used), and WIDENS automatically when D3 has been down longer than that, so a GO logged during any gap
-- in D3's own run history is still in-window the next time D3 (or a catch-up run standing in for it)
-- actually executes and reads this view. D3 having never logged a completed run at all falls back to
-- the original 2-day floor (COALESCE), not full history. D3 has no known legacy non-ASCII routine-id
-- form in ops.run_log (unlike AR_att/AR_orc), so a plain `routine = 'D3'` equality match is sufficient
-- here -- the RUNBOOK §28 id-separator normalization used elsewhere in this file is not needed.
--
-- DECISIONS STAY CURRENT-SESSION-SCOPED: this view only widens the EVIDENCE this routine reads: which
-- historical GO rows D3 reviews for a missing staged order. It does not retroactively place, alter, or
-- backdate any order -- D3's own adjudication step (Claude_Task_Plan.md) still runs fresh, in the
-- current session, against whatever this view surfaces.
--
-- DO NOT re-apply bigquery/18's original CREATE statement for this object live in isolation -- it would
-- revert the window to the fixed 2-day cutoff and silently reintroduce the missed-catch-up gap this
-- redefinition exists to close. bigquery/18's copy is kept there, unmodified, for DR-rebuild
-- apply-in-order reference only (see the SUPERSEDED marker added there pointing at this file).
CREATE OR REPLACE VIEW `stock-trading-498512.state.go_without_order` AS
WITH d3_last_completed AS (
  -- D3's own last completed ops.run_log run -- the anchor for how far back this view's evidence window
  -- needs to reach.
  SELECT MAX(log_ts) AS d3_last_completed_ts
  FROM `stock-trading-498512.ops.run_log`
  WHERE routine = 'D3' AND status = 'completed'
),
go_decisions AS (
  SELECT entry_id, entry_date, strategy, ticker, entry_type, title
  FROM `stock-trading-498512.events.decision_log`
  WHERE decision = 'GO'
    AND superseded_by IS NULL
    AND entry_date >= DATE_SUB(
      CURRENT_DATE('America/Denver'),
      -- FLOORED at the original fixed 2-day (~36h) lookback (GREATEST semantics): never narrower than
      -- bigquery/18's original definition, but widens to D3's own last-completion gap when that is
      -- bigger -- see the file-level comment above this CREATE statement.
      INTERVAL (
        SELECT GREATEST(
          2,
          COALESCE(
            DATE_DIFF(CURRENT_DATE('America/Denver'), DATE(d3_last_completed_ts, 'America/Denver'), DAY),
            2
          )
        )
        FROM d3_last_completed
      ) DAY
    )
)
SELECT
  g.entry_id, g.entry_date, g.strategy, g.ticker, g.entry_type, g.title,
  CURRENT_TIMESTAMP() AS checked_at
FROM go_decisions g
-- no staged order references this decision (by ref, else by ticker+strategy on/after the decision day).
-- DATE(..., 'America/Denver') — NOT the bare (UTC-default) form — because g.entry_date is the
-- Denver OPERATING day decision_log stamps; a bare UTC date is always >= the Denver date, so an
-- order/fill actually staged the PRIOR Denver evening (>=~17:00 MT = already the next UTC day) could
-- wrongly satisfy this match and suppress a genuine go-without-order candidate (false negative only;
-- 2026-07 report-system fix).
WHERE NOT EXISTS (
  SELECT 1 FROM `stock-trading-498512.events.queue_events` q
  WHERE q.queue = 'ORDER_STAGED'
    AND (JSON_VALUE(q.payload, '$.source_decision_ref') = g.entry_id
         OR (q.ticker = g.ticker AND q.strategy = g.strategy AND DATE(q.event_ts, 'America/Denver') >= g.entry_date))
)
-- and no fill recorded for that strategy/ticker on/after the decision day
AND NOT EXISTS (
  SELECT 1 FROM `stock-trading-498512.events.trade_fills` f
  WHERE f.ticker = g.ticker AND f.strategy = g.strategy
    AND DATE(f.fill_ts, 'America/Denver') >= g.entry_date
);

-- Verified live (read-only) 2026-07-25 against real stock-trading-498512.ops.run_log: the
-- routine_catchup_window SELECT body (run as a plain query, not yet CREATEd) executes cleanly and
-- returns plausible results for all 31 ids (the roster size ON THAT DATE — OPS2 was added 2026-07-27,
-- making it 32; this paragraph is a dated observation, so do NOT "correct" the 31), including
-- correctly showing never_completed=TRUE with the
-- cadence-sized fallback window for the never-run routines (92-day for quarterly SL1, 31-day for
-- monthly SL4, 366-day for annual A1/A2/A3 -- genuinely idle-by-cadence per existing memory notes),
-- and window_days in the ~2.3-2.5 day range for D1/D2/D2a/D3/AR_att/AR_orc/W4/W5 -- exactly
-- bracketing the real 2026-07-23/24 connector outage this whole design exists to catch.
