"""Shared helpers for generated markdown slice writers."""
from __future__ import annotations

import os
import re
import sys


def slugify(title: str) -> str:
    """Filesystem-safe slug used by generated slice names."""
    s = re.sub(r"[^a-z0-9]+", "_", title.strip().lower()).strip("_")
    return s or "section"


def find_orphaned_markdown_files(outdir: str, expected_files, hand_maintained) -> list[str]:
    """.md files in outdir that are not generated by the current build."""
    if not os.path.isdir(outdir):
        return []
    expected = set(expected_files) | set(hand_maintained)
    return sorted(fn for fn in os.listdir(outdir) if fn.endswith(".md") and fn not in expected)


def check_or_write_slices(
    files: dict[str, str],
    *,
    outdir: str,
    check: bool,
    hand_maintained,
    stale_message: str,
    orphan_message: str,
    orphan_warning: str,
    ok_message: str,
    wrote_message: str,
) -> int:
    """Compare or write generated slice files and report stale/orphaned outputs."""
    os.makedirs(outdir, exist_ok=True)
    drift = []
    for name, content in files.items():
        path = os.path.join(outdir, name)
        existing = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                existing = f.read()
        if check:
            if existing != content:
                drift.append(name)
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)

    orphans = find_orphaned_markdown_files(outdir, files, hand_maintained)
    if check:
        if drift:
            print(stale_message + ", ".join(sorted(drift)), file=sys.stderr)
        if orphans:
            print(orphan_message + ", ".join(orphans), file=sys.stderr)
        if drift or orphans:
            return 1
        print(ok_message)
        return 0

    if orphans:
        print(orphan_warning + ", ".join(orphans))
    print(wrote_message)
    return 0
