#!/usr/bin/env python3
"""Apply ONE pre-extracted SQL statement file to live BigQuery, dry-run first, hash-reported.

WHY THIS EXISTS. Landing a `bigquery/*.sql` object live is a recurring operation with, until now, no
safe mechanical path for a LARGE statement:

  * The BigQuery **console** is not automatable for large SQL. Measured 2026-09-05 (`weekly_report.gs`
    WR-2): the console's Monaco editor ignored synthetic Ctrl+A/Ctrl+V/Backspace, programmatic inserts
    landed unpredictably (the buffer ended up holding the statement twice plus a stray probe), and the
    buffer cannot be read back to verify. A ~16KB statement was correctly abandoned unrun.
  * Re-typing the statement into the **BigQuery MCP** tool works and is the sanctioned path, but it
    means an agent reproducing the bytes from memory. For `ops.sp_sq_cadence_check` that is a 76KB
    procedure driving the whole cadence dead-man's-switch fleet, and this repo's own rule for that
    procedure is that its body is "generated by programmatic exact-string replacement, not retyped"
    (bigquery/63's registry note). Re-typing it to APPLY it reintroduces exactly the transcription
    risk that rule exists to remove.

This script closes that gap: it reads the canonical bytes off disk and sends them, so nothing is ever
retyped. It is deliberately NARROW so it can be granted a correspondingly narrow permission rule
(`Bash(python3 scripts/apply_sql_file.py *)`) instead of a blanket `python3 -c` grant on a repo that
trades real money.

SAFETY PROPERTIES (all deliberate):
  * DRY-RUN FIRST, ALWAYS. Every statement is submitted with dry_run=True and must succeed before the
    real submission is even built. BigQuery's script dry-run does NOT semantically analyse anything
    after the first DDL in a script (see scripts/check_sql_dryrun.py's docstring), which is exactly
    why this script takes ONE statement per file rather than a whole bigquery/*.sql script — a missing
    `WHERE` in a later statement of a multi-statement file is invisible to the dry run, and that class
    of defect really did reach a file in this repo on 2026-09-08.
  * REPORTS WHAT IT IS ABOUT TO RUN — path, line/char/byte counts, sha256, first and last line — so
    the caller can match it against the extraction it intended.
  * NEVER EDITS, NEVER EXTRACTS. It applies a file exactly as given. Extraction from a numbered
    bigquery/*.sql file is the caller's job (use check_live_sql_parity.sql_tokens /
    find_procedure_body_end, never a hand-rolled splitter).
  * VERIFY AFTERWARDS with `python3 scripts/check_live_sql_parity.py`, which compares the LIVE object
    against the canonical repo body. That is the real gate; this script only moves bytes.

USAGE:
    python3 scripts/apply_sql_file.py <file.sql> [<file2.sql> ...]     # dry-run each, then apply
    python3 scripts/apply_sql_file.py --dry-run <file.sql>             # validate only, apply nothing

Files are applied IN THE ORDER GIVEN, and the run STOPS at the first failure — dependency order
matters (a view a procedure reads must exist before that procedure is created).
"""
import hashlib
import sys

try:
    from google.cloud import bigquery
except ImportError:  # pragma: no cover - environment guard, same shape as the other scripts here
    print("google-cloud-bigquery required: pip install google-cloud-bigquery", file=sys.stderr)
    raise SystemExit(2) from None

PROJECT = "stock-trading-498512"


def describe(path, sql):
    lines = sql.split("\n")
    print(f"  path      : {path}")
    print(f"  lines     : {len(lines)}   chars: {len(sql)}   bytes: {len(sql.encode('utf-8'))}")
    print(f"  sha256    : {hashlib.sha256(sql.encode('utf-8')).hexdigest()}")
    print(f"  first line: {lines[0][:100]}")
    print(f"  last line : {lines[-1][:100]}")


def main(argv):
    args = [a for a in argv if not a.startswith("--")]
    dry_only = "--dry-run" in argv
    if not args:
        print(__doc__, file=sys.stderr)
        return 2

    client = bigquery.Client(project=PROJECT)
    for path in args:
        try:
            sql = open(path, encoding="utf-8").read()
        except OSError as exc:
            print(f"FAILED to read {path}: {exc}", file=sys.stderr)
            return 1
        if not sql.strip():
            print(f"FAILED: {path} is empty", file=sys.stderr)
            return 1

        print(f"\n=== {path} ===")
        describe(path, sql)

        try:
            client.query(sql, job_config=bigquery.QueryJobConfig(dry_run=True, use_query_cache=False))
        except Exception as exc:  # noqa: BLE001 — surface BigQuery's own message verbatim
            print(f"  DRY RUN FAILED — nothing applied: {exc}", file=sys.stderr)
            return 1
        print("  dry run   : OK")

        if dry_only:
            print("  --dry-run set; not applying.")
            continue

        try:
            job = client.query(sql)
            job.result()
        except Exception as exc:  # noqa: BLE001
            print(f"  APPLY FAILED: {exc}", file=sys.stderr)
            return 1
        print(f"  APPLIED   : job {job.job_id}  state={job.state}  errors={job.errors}")

    print("\nNow verify: python3 scripts/check_live_sql_parity.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
