#!/usr/bin/env python3
"""Single-source the cadence: fail CI if the hand-kept SQL drifts from ops/cadence.yaml + the plan.

WHY THIS EXISTS. "What runs when" was hand-maintained in THREE places that had to stay in lockstep
with no automated guard:
  1. ops/cadence.yaml                          — the documented manifest (now carries monitor_class)
  2. state.cadence_expected_today (SQL)        — bigquery/12_cadence_monitor.sql, a hardcoded routine list
  3. ops.routine_catalog (SQL)                 — bigquery/15_routine_catalog.sql, a hardcoded instruction seed
plus the canonical routine headings in Claude_Task_Plan.md. A routine added / renamed / rescheduled in
one place but not the others drifted silently — exactly the RUNBOOK §22-class problem. This check makes
ops/cadence.yaml + Claude_Task_Plan.md the SOURCE OF TRUTH and verifies the two SQL files agree:

  A. state.cadence_expected_today's (routine -> schedule-class) set == cadence.yaml's
     (id -> monitor_class) for every routine whose monitor_class is calendar-predictable
     (i.e. != queue_driven; the AR routines are deliberately excluded from the calendar view).
  B. ops.routine_catalog's (routine -> canonical_instruction) == the instruction derived from each
     Claude_Task_Plan.md routine heading ("Read Claude_Task_Plan.md. Perform <heading>.").
  C. Every cadence.yaml routine id maps 1:1 to a Claude_Task_Plan.md heading and appears in the catalog
     (the scripts/print_routines.py cross-check, extended to the SQL layer).
  D. cadence.yaml's top-level `cadence_watch_deadline_local` == the TIME literal in the
     state.cadence_watch deadline guard (bigquery/12_cadence_monitor.sql). The deadline is otherwise a
     bare SQL constant with no source of truth, so a real cadence shift could silently leave it stale and
     re-open the pre-deadline false-positive window (RUNBOOK §1 step 3 / §20 follow-up).
  E. cadence.yaml's top-level `period_grace_days` == the OFFSET/day-count literals in
     state.cadence_period_watch (bigquery/24_cadence_period_watch.sql) — added 2026-07-03,
     self-improvement audit WO-1/B-6-obs, same discipline as check D.
  F. ops/triggers.json (if present) == the canonical {id, monitor_class, instruction} map derived from
     cadence.yaml + Claude_Task_Plan.md headings — GENERATED by `scripts/print_routines.py --write`,
     never hand-kept (self-improvement audit WO-2). If the file does not yet exist this check is
     skipped (it is an opt-in artifact, not required for every clone).
  J. state.cadence_period_watch's (routine -> monitor_class) STRUCT rows (bigquery/24_cadence_period_
     watch.sql `routines` CTE) == cadence.yaml's routines whose monitor_class is one of the four period
     classes (weekly_sun/monthly_ftd/quarterly_ftd/annual_ftd). The rows are GENERATED by
     `scripts/gen_routine_lists.py --write`; this check verifies the CONTENT still agrees (ARCH-3 Item
     30b, 2026-07-16 — this list previously had zero CI list-drift protection at all).
  K. bigquery/31_catchup_notify.sql's and bigquery/59_catchup_autofire.sql's hand-maintained
     catchup-safe UNNEST id lists == the {routine : catchup_safe AND monitor_class in <tier>} subset of
     cadence.yaml (31 = daily tier: daily_trading/daily_all; 59 = period tier: the four period
     classes). Also requires every cadence.yaml routine to declare an explicit `catchup_safe` boolean
     (missing key = error, mirroring the monitor_class presence check) — these two lists are a
     DECLARED capital-adjacency judgment, never derived from monitor_class (ARCH-3 Item 30b).
  L. The ROUTINE INVENTORY table in Claude_Task_Plan.md (the section between the "# ROUTINE INVENTORY
     & BIGQUERY RESPONSIBILITIES" heading and the next `---` divider) lists exactly the cadence.yaml
     routine ids, and each row's "Cadence · Type" cell agrees with that routine's monitor_class (ARCH-3
     Item 30b — this table previously had zero CI coverage).

This does NOT generate the bigquery/12/15/24 STRUCT rows by hand — `scripts/gen_routine_lists.py
--write` does that (checks A/B/J verify the generator's OUTPUT agrees with cadence.yaml; the CI step
`gen_routine_lists.py --check` verifies the committed files are byte-current with what --write would
produce). This script does NOT generate bigquery/31/59's catchup-safe lists or the plan's ROUTINE
INVENTORY table (those stay hand-authored, declared judgment calls) — it only CHECKS them (checks K/L),
so editing cadence.yaml or a plan heading and forgetting a dependent file fails the build with a
precise diff instead of surfacing weeks later as a false cadence/instruction_drift alert.

Usage:  python scripts/check_cadence_consistency.py        # exit 0 if consistent, 1 + diff if not
"""
import json
import os
import re
import sys

try:
    # this module's own reads now go through lib.textio.load_yaml() (2026-07-29 textio
    # adoption), so `yaml` is no longer referenced directly here, but the import stays for this
    # fail-fast ImportError guard (a clear "pip install pyyaml" message beats textio.py's own bare
    # ImportError traceback).
    import yaml  # noqa: F401
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    raise SystemExit(2) from None

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib.routine_manifest import (
    heading_to_id, parse_routine_headings, build_triggers_manifest, instruction_text, cadence_routines,
)
from lib.sql_files import numbered_sql_files, resolve_canonical, strip_sql_comments
from lib.textio import read_text, load_yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLAN = os.path.join(ROOT, "Claude_Task_Plan.md")
OWNER_ACTIONS = os.path.join(ROOT, "OWNER_ACTIONS.md")
CADENCE = os.path.join(ROOT, "ops", "cadence.yaml")
BIGQUERY_DIR = os.path.join(ROOT, "bigquery")
# Directory scanned for the canonical state.stalled_runs definition (check O) -- a SEPARATE module
# constant from BIGQUERY_DIR (not merely an alias resolved at call time), even though it starts out
# pointing at the exact same directory, so tests can monkeypatch check O's search directory in
# isolation from check D-extended's own BIGQUERY_DIR-based canonical-file scan for state.cadence_watch.
# That scan already runs, unpatched, against the REAL bigquery/ directory in every existing fixture
# test (it only stays clean because the real repo's deployed deadline literal happens to equal the
# fixture's "21:00" -- see find_canonical_cadence_watch_file()'s docstring); redirecting the shared
# BIGQUERY_DIR constant itself to isolate check O's tests would silently break that unrelated check's
# coverage in every one of those tests instead.
STALLED_RUNS_BIGQUERY_DIR = BIGQUERY_DIR
CADENCE_SQL = os.path.join(ROOT, "bigquery", "12_cadence_monitor.sql")
CATALOG_SQL = os.path.join(ROOT, "bigquery", "15_routine_catalog.sql")
PERIOD_WATCH_SQL = os.path.join(ROOT, "bigquery", "24_cadence_period_watch.sql")
TRIGGERS_JSON = os.path.join(ROOT, "ops", "triggers.json")
TRIGGER_IDS_JSON = os.path.join(ROOT, "ops", "trigger_ids.json")
AUTO_MERGE_YML = os.path.join(ROOT, ".github", "workflows", "auto-merge-claude.yml")
# The §38 marker-write allowlist moved into the sourced helper on 2026-07-29 (extracted so
# tests/test_auto_merge_logic.sh covers the production implementation); the workflow is kept as a
# fallback location so this check still finds the literal if it is ever moved back inline.
AUTO_MERGE_DECISION_SH = os.path.join(ROOT, "scripts", "auto_merge_decision.sh")
CATCHUP_NOTIFY_SQL = os.path.join(ROOT, "bigquery", "31_catchup_notify.sql")
CATCHUP_AUTOFIRE_SQL = os.path.join(ROOT, "bigquery", "59_catchup_autofire.sql")

# ---- check N: MODEL OF RECORD mirrors (added 2026-07-28, owner directive; labelled "M" at first —
# renamed to N, the lowest unused letter, once it collided with the pre-existing check M below (H1,
# whole-system deep audit 2026-07-17): both blocks had claimed the same letter independently) ----
# ops/cadence.yaml's top-level `routine_model` is the single source of truth for which Claude model
# the owner configured for the remote-routine fleet ("we will always use the same model for all remote
# routines"). Several prose/SQL sites RESTATE that id; before this check they agreed only by hand, and
# that manual sync had already failed once in practice (commit f347b8f, 2026-07-26: the owner switched
# all 31 routines to claude-opus-5 and the in-repo comment "was already stale even before that").
# A stale mirror is not cosmetic: A1/Q3 read the model of record to decide which model's capability
# research is decision-relevant and which Tier 2 magnitudes flip to version-pending, so a wrong value
# silently anchors the whole foundation document to a model the experiment does not run.
# This check makes the mirrors machine-enforced: change routine_model, and CI names every file that
# still disagrees. Research/history files (Quarterly_AI_Foundation_Delta.md, Monthly_AI_Capabilities.md,
# Annual_AI_Foundation_Sweep.md) are deliberately NOT scanned — they legitimately name many models.
# AI_Trading_Foundation.md is also NOT scanned, but not for the reason this comment used to give.
# It used to be written only by the annual A3, so coupling CI to A3's annual cadence would have failed
# the build for months at a time — that objection no longer applies: the field is now Tier-M-synced at
# DAILY cadence by D3, with Q4/A3 as idempotent backstops (see AI_Trading_Foundation.md Part 4 "Write
# authority — two tiers"). The file stays unscanned anyway, deliberately: a runtime alert
# (D3's/Q4's `model_of_record_synced`) rather than a CI gate is the chosen detector for this field,
# precisely so a model change can never redden the build fleet-wide and block auto-merge for every
# branch. This field's accuracy now rests on the Tier M daily sync path, not on CI.
def model_mirror_files():
    """The check-N mirror-file list, resolved at CALL time (not import time) from the module-level path
    constants CADENCE/OWNER_ACTIONS/PLAN/CATALOG_SQL, so monkeypatch.setattr(cc, "CADENCE", ...) (etc.,
    as the fixture-based tests do) takes effect here too. A module-level list built once at import time
    from hardcoded os.path.join(ROOT, ...) calls could never be monkeypatched, so a fixture test's
    routine_model VALUE (read from the patched CADENCE) would silently be compared against the REAL
    repo's mirror files instead of the fixture's — cross-contamination between what a test sets up and
    what it actually checks."""
    return [CADENCE, OWNER_ACTIONS, PLAN, CATALOG_SQL]

# MATCHING A MODEL ID: LOUD BY DEFAULT, NEVER SILENT (2026-07-28, adversarially re-reviewed TWICE the
# SAME day — a first cut over-tightened the match SHAPE, and a second cut over-corrected the other way
# with a shape-based escape hatch that turned out to be just as unsound). The governing principle: a
# FALSE POSITIVE here is cheap — it shows up in CI and is one 'model-id-exempt' marker away from fixed
# — while a FALSE NEGATIVE is the exact failure this check exists to eliminate: a stale mirror that CI
# swears is clean (the manual-sync failure of commit f347b8f). So the match must stay BROAD, subtracting
# only precisely-known non-assertions — never narrowed up front to "look like a model id", and never
# allowed to swallow a real, different id just because it happens to share a shape with something benign.
#
# ROUND 1 (reverted): a same-day adversarial pass on this check's FIRST cut (a pattern requiring family
# word(s) then a digit-led version, with a negative lookahead against a further slug character) proved
# that tightening the match SHAPE was the WRONG TRADE, with live repros:
#   - 'claude-opus-4-latest' — the real -latest/-preview alias convention — matched ZERO times.
#     End-to-end: a fixture with a genuinely stale OWNER_ACTIONS.md mirror printed "CADENCE
#     CONSISTENCY: OK ... matches all mirror sites" and exited 0. Silent false-clean — the worst
#     possible outcome for a check built specifically to prevent silent false-clean.
#   - 'claude-3-5-sonnet-20241022', 'claude-3-opus-20240229', 'claude-5-opus' — real historical
#     Anthropic ids with a DIGIT right after 'claude-' — also matched ZERO times; the tightened shape
#     required a letter immediately after the family hyphen.
#   - the URL-strip (r"https?://\S+", greedy to the next whitespace) SWALLOWED a genuine id sitting
#     right after a markdown link's closing paren with no space:
#     '[text](https://example.com/x)claude-sonnet-4 remains configured' — the id vanished with the URL.
# Fix: match broadly again (MODEL_ID_CORE below), and bound URL_RE at a closing bracket/quote/backtick
# instead of only whitespace.
#
# ROUND 2 (also reverted — DEFECT A, later the same day): the broad-match design then added a SECOND
# subtraction — "a slug that merely EXTENDS THE CORRECT id (routine_model) with a citation suffix", e.g.
# treat 'claude-opus-5-model-card' as clean when routine_model is 'claude-opus-5' because
# token.startswith(model) and the next character is '-'/'.'. This was UNSOUND: a real, DIFFERENT model
# id that happens to extend the correct id character-for-character is STRUCTURALLY IDENTICAL to a
# citation slug — shape alone cannot tell them apart. Live repros, ALL confirmed returning ZERO errors
# with routine_model='claude-opus-5' under the reverted rule:
#     claude-opus-5-preview, claude-opus-5-latest, claude-opus-5-beta, claude-opus-5-exp,
#     claude-opus-5-20250219, claude-opus-5-1, claude-opus-5.1
# A mirror reading "All remote routines run claude-opus-5-preview today." printed "CADENCE
# CONSISTENCY: OK ... matches all mirror sites" and exited 0 — again the exact silent false-clean this
# check exists to prevent. The branch was DELETED, not refined — there is no shape-only fix, because the
# ambiguity is inherent (a citation slug and a real sibling model id are the same shape by construction).
# Consequence, which is CORRECT and intended: 'claude-opus-5-model-card' appearing in prose OUTSIDE a
# URL is now FLAGGED too, and the author resolves it with the 'model-id-exempt' marker, same as any
# other citation. An id sitting inside a URL is still stripped by URL_RE, which already covers the
# overwhelmingly common citation case. Do NOT re-add an "extends the correct id" subtraction in any
# form, however narrowed — if a future site produces a false positive, mark that specific line
# 'model-id-exempt' instead.
#
# Do NOT re-tighten MODEL_ID_CORE to "look like" a model id in some more elaborate way either (Round 1
# above). If a future site produces a false positive, add 'model-id-exempt' to that line, or extend the
# SUBTRACTION below with a new, precisely scoped, well-tested, NON-shape-based exception (one that
# structurally cannot also match a real different model id) — never narrow the broad match itself.
#
# THE DESIGN: match BROADLY (anything shaped like "claude-" + more slug characters), then SUBTRACT
# exactly ONE precisely-known class of non-assertion:
#   NOT_A_MODEL_PREFIXES — tokens that name CLI/SDK tooling, never a model ('claude-code',
#   'claude-code-action', 'claude-agent-sdk-with-your-claude-plan', ...). No Anthropic model is named
#   claude-code*/claude-agent-sdk*/claude-cli*/claude-desktop*, so this can never hide a genuinely
#   drifted id — UNLESS the remainder right after the matched prefix looks version-shaped ('-' or '.'
#   then a DIGIT, e.g. 'claude-code-5', 'claude-cli-2.1'), in which case it is left FLAGGED, not
#   subtracted (DEFECT B, 2026-07-28: a blunt str.startswith() previously swallowed a hypothetical real
#   model sharing a tooling prefix's name — confirmed live, 'claude-code-5' returned zero errors — see
#   _tooling_prefix_hides_version below).
# A URL span still never carries a fleet assertion, so it is stripped before scanning a line — but the
# strip now stops at a closing bracket/brace/angle-bracket/quote/backtick as well as whitespace, so it
# can no longer eat a model id that immediately follows a markdown link with no space.
#
# KNOWN, ACCEPTED LIMIT (DEFECT C — do not "fix"): a model id glued directly onto a URL path segment
# with NO delimiter, e.g. 'https://example.com/system-cardclaude-opus-4-8', is still never scanned —
# but AS OF 2026-07-28's leading-\b removal (below), the MECHANISM is not what an earlier pass of this
# comment claimed. That earlier text said URL_RE "consumes it whole" and that the id is unfindable
# because there is no word boundary between 'card' and 'claude' — implying the boundary check was the
# operative cause. Re-tested against BOTH regex generations and the claim does not hold either way:
#   - WITH the (now-removed) leading \b: MODEL_ID_RE.findall() on the raw, unstripped string ALSO
#     returns [] — 'd' (of 'card') and 'c' (of 'claude') are both word characters, so \b never matches
#     between them and the scan can't even start there. URL_RE never gets a chance to matter for this
#     string under the old regex, because MODEL_ID_RE was already blind to it on its own.
#   - WITHOUT the leading \b (current code, since MODEL_ID_RE has no start-anchor at all anymore):
#     MODEL_ID_RE.findall() on the RAW string now DOES find 'claude-opus-4-8' embedded inside
#     'system-cardclaude-opus-4-8' — confirmed live. So post-fix, URL_RE is now the ACTUAL and ONLY
#     reason this case still yields no match: the whole string is a single unbroken URL (no comma,
#     semicolon, pipe, bracket, quote, or other stop character anywhere in it), so URL_RE's substitution
#     consumes it in full before MODEL_ID_RE ever runs, and the id inside is never scanned. End-to-end
#     behavior is unchanged (still no match) but the mechanism has flipped: URL_RE was NEVER the
#     mechanism under the old regex, and IS the (sole) mechanism under the new one. This is unfixable by
#     construction either way — with no delimiter, the id's characters are indistinguishable from an
#     ordinary URL path segment — and an id living inside a URL, delimited or not, is a citation rather
#     than a fleet assertion, so losing recall here is an acceptable trade. Do NOT widen URL_RE's
#     stop-set trying to catch this (there is no delimiter to stop at) and do NOT add a test asserting
#     the swallow — that would enshrine an accepted gap as a spec instead of leaving it documented here
#     as a known, reasoned limit.
#
# KNOWN, ACCEPTED LIMIT (case sensitivity — decided 2026-07-28, do NOT re-litigate without new
# evidence): MODEL_ID_CORE is lowercase-only, so a capitalized form like 'Claude-Sonnet-5' never
# matches, and re.IGNORECASE was considered and DECLINED. Measured against all four real mirror files
# with re.IGNORECASE added: it would newly match 26 tokens, EVERY one ordinary English prose, NONE a
# model id — Claude-in-Chrome (x8), Claude-only (x5), Claude-version (x5), Claude-specific (x3),
# Claude-Code-on-Web (x2), Claude-crafted (x1), Claude-family (x1), Claude-produced (x1) — i.e. 26
# immediate CI failures each demanding its own 'model-id-exempt' marker on a line that never named a
# model in the first place. Separately, the realistic capitalized human-written form for a fleet
# assertion is "Claude Opus 5" (a space, not a hyphen) — case-insensitivity would not catch that shape
# either way, since MODEL_ID_CORE requires a hyphen after 'claude'. So re.IGNORECASE buys a narrow,
# not-observed-in-practice band (a hyphenated id with non-lowercase letters) at a large, concrete,
# immediate cost (26 false positives on the current tree) and does not even reach the realistic
# capitalized case. Declined. If a future audit re-flags this, re-measure the token count against the
# THEN-current mirror files before re-proposing — do not assume the 26-token cost is stale without
# checking, and do not add re.IGNORECASE without also solving the "Claude Opus 5" (space-separated) gap
# it still wouldn't close.
#
# KNOWN GAP (prose-form family names — "Opus 5", "Sonnet 5", "Fable 5" — documented 2026-07-28; do NOT
# implement prose matching pre-emptively, and do NOT add a test asserting the gap): MODEL_ID_CORE only
# matches ids shaped 'claude-...', so the space-separated human form — including the fleet's own
# routine-suffix convention "(Opus 5)" that the live trigger text uses to name the model to a human
# reader — carries no 'claude-' prefix and is never scanned at all. A mirror line asserting the WRONG
# model in that form therefore passes clean. Confirmed live: with routine_model='claude-opus-5', the
# line "All remote routines now run Sonnet 5 today, replacing the prior Opus 5 configuration." runs
# through MODEL_ID_RE.findall() and returns [] — check_model_of_record() reports zero errors for it.
#   MEASURED CURRENT EXPOSURE (2026-07-28, re-run against the four real mirror files this check scans).
#   Measure the BARE form, not a paren-anchored one — the gap is about the space-separated shape in any
#   context, and a paren-anchored grep undercounts it (1 hit vs 3):
#     $ grep -nE "\b(Opus|Sonnet|Haiku|Fable) [0-9]" ops/cadence.yaml OWNER_ACTIONS.md \
#           Claude_Task_Plan.md bigquery/15_routine_catalog.sql
#     bigquery/15_routine_catalog.sql:110:-- addendum's model references from Fable 5 to Opus 5, and the routines' own `model` field to
#     bigquery/15_routine_catalog.sql:112:-- operator addendum (as of 2026-07-26: "Spawn Sonnet 5 model sub-agents to do the grunt work. Save your
#     bigquery/15_routine_catalog.sql:113:-- processing (Opus 5) for design/analysis/orchestration work only."), separated from the heading by a
#   THREE lines, all in one file, and they are NOT all historical narration — the distinction matters:
#     - :110 IS historical ("owner switched the addendum's model references from Fable 5 to Opus 5"),
#       describing the 2026-07-26 change in the past tense. Already correct; would not rot.
#     - :112-113 are a PRESENT-TENSE quotation of the CURRENT live trigger addendum — the surrounding
#       comment says the live web-UI trigger message "is now ALWAYS" the heading plus this addendum.
#       If the fleet model changes and this quoted text is not updated in the same pass, it becomes
#       exactly the stale live assertion this check exists to catch, and check N will not see it.
#   So the exposure today is small (one file, three lines) but it is NOT purely historical prose.
#   WHY NOT CLOSED NOW: matching bare "Opus 5"/"Sonnet 5"/"Haiku 5"/"Fable 5" would require a second,
#   prose-shaped pattern over ordinary English words (a family name followed by a bare digit), whose
#   false-positive cost on living docs (bigquery/15's own historical-comment prose is the immediate
#   example, and any future narration of a past model switch elsewhere would hit the same pattern) has
#   never been measured — the exact same mistake the case-sensitivity decision above avoided by
#   measuring the 26-token cost FIRST, before deciding.
#   CONSEQUENCE an owner should weigh: if the fleet model changes again, prose of this form — including
#   the "(Opus 5)" routine-suffix convention itself — will NOT be flagged by this check and can rot
#   silently, the same class of risk commit f347b8f already demonstrated for the hyphenated id form.
#   WHAT A FUTURE AUDIT SHOULD DO before proposing a fix: measure the false-positive count of a
#   prose-shaped pattern (e.g. r"\b(Opus|Sonnet|Haiku|Fable) [0-9]") against the THEN-current mirror
#   files first, exactly as the case-sensitivity paragraph's 26-token measurement did — do not add prose
#   matching on the strength of "it seems safe," measure it.
#
# MODEL_ID_CORE is the one shape both MODEL_ID_RE (the mirror scanner) and MODEL_ID_VALID (the
# routine_model well-formedness gate) are built from -- but sharing a shape does NOT by itself mean
# the two can never drift apart: MODEL_ID_VALID.fullmatch() checks the WHOLE string, while
# MODEL_ID_RE.findall() only has to locate an embedded token, and MODEL_ID_RE's trailing \b cannot
# terminate a match right after a non-word character -- a trailing '-' or '.', both admitted by
# MODEL_ID_CORE's own tail class ([a-z0-9.\-]*). So a routine_model value ending in '-' or '.' could
# pass MODEL_ID_VALID.fullmatch() as WELL-FORMED while MODEL_ID_RE.findall() on that same text only
# ever recovers a SHORTER token, self-contradictorily flagging the source-of-truth line itself
# (DEFECT, 2026-07-28: confirmed live with routine_model='claude-opus-5-'). check_model_of_record()'s
# validation gate closes that gap by separately rejecting any routine_model whose last character is
# not alphanumeric. The precise property that now holds is narrower than "can never drift": any value
# the VALIDATION GATE ACCEPTS is matchable IN FULL by the scanner -- not that MODEL_ID_RE and
# MODEL_ID_VALID can never disagree on some OTHER string neither of them is ever asked to validate.
MODEL_ID_CORE = r"claude-[a-z0-9][a-z0-9.\-]*"
# LEADING \b DROPPED (2026-07-28 adversarial review, HIGH; see the DEFECT C paragraph above for how
# this changes that limit's mechanism). The leading \b required a non-word character immediately before
# 'claude', so a dropped-space typo fusing the id into the previous word ("Fleet nowclaude-sonnet-5 is
# the model.") hid it from the scanner entirely -- confirmed live pre-fix, zero errors. The trailing \b
# is KEPT: it still stops the match at the end of the id's own character class (no word character
# bleeds past a match into whatever follows), which is the boundary that actually matters for correctly
# delimiting the RIGHT edge of an id. Re-verified against all four real mirror files (ops/cadence.yaml,
# OWNER_ACTIONS.md, Claude_Task_Plan.md, bigquery/15_routine_catalog.sql): dropping the leading \b
# matches NOTHING NEW there today, so this is a free strictness gain with zero false-positive cost on
# the current tree.
MODEL_ID_RE = re.compile(MODEL_ID_CORE + r"\b")
# fullmatch (not a bare $-anchored .match()) so a YAML block-scalar's trailing "\n" (routine_model: |)
# is rejected as MALFORMED instead of silently passing — a bare "$" also matches just before a
# trailing newline, which let such a value leak into the mismatch loop below and interpolate a raw
# embedded newline into the single-line " - " bullet report (2026-07-28 adversarial review).
MODEL_ID_VALID = re.compile(MODEL_ID_CORE)
# The one remaining subtraction: a token starting with one of these names CLI/SDK tooling, never a
# model — UNLESS the remainder right after the matched prefix looks version-shaped (DEFECT B; see
# _tooling_prefix_hides_version), in which case it is left FLAGGED rather than subtracted. Also enforced
# against routine_model ITSELF (see check_model_of_record) — a routine_model value that hits one of
# these prefixes is rejected outright as malformed: it would be too easy to confuse with the CLI/SDK
# tooling of the same name, and in the exact-match case (e.g. routine_model='claude-code') could never
# be found by the scanner at all (it would always subtract itself out as tooling), silently making the
# whole check vacuous.
NOT_A_MODEL_PREFIXES = ("claude-code", "claude-agent-sdk", "claude-cli", "claude-desktop")
# A URL span never carries a fleet assertion — strip it before scanning a line for model ids. Bounded
# at a closing bracket/brace/angle-bracket/quote/backtick as well as whitespace, so the strip stops at
# a markdown link's closing ')' instead of running on and eating whatever immediately follows with no
# space (2026-07-28 adversarial review, MEDIUM finding). Also bounded at ',' ';' '|' '<' '(' '[' '{'
# (2026-07-28, operator-requested, MEDIUM): those are natural sentence delimiters the character class
# previously still admitted, so a genuine stale id sitting immediately after one of them within the
# same line -- e.g. "See https://example.com/x,claude-sonnet-4 is stale" -- was eaten along with the
# URL and never scanned. Confirmed live pre-fix: zero matches on that line. Deliberately NOT bounded at
# ':' despite it also reading as a plausible sentence delimiter: a URL legitimately contains a ':' in
# an authority-section port number ("https://example.com:8080/path"), and excluding it from the class
# would truncate the strip there, leaving "8080/path" unstripped and scanned as ordinary text on every
# such URL. The genuine in-URL-path citation case (a slug with NO delimiter before it, e.g.
# '.../claude-opus-4-8-system-card') is unaffected by any of this -- none of the newly-excluded
# characters appear in an ordinary path segment, so that span is still consumed whole.
URL_RE = re.compile(r"""https?://[^\s,;|<>()\[\]{}"'`]+""")
# A line carrying this marker names a model id for illustration/history, not as a fleet assertion.
# \b-anchored on the LEFT, negative-lookahead-bounded on the RIGHT (2026-07-28 adversarial review,
# HIGH, two rounds the same day):
#   Round 1: an unanchored substring search let an ordinary word containing 'model-id-exempt' as an
#   infix (e.g. "...that citation is model-id-exemption-only, not a live assertion.") silently suppress
#   a REAL drift reported on the same line -- check_model_of_record() skips the ENTIRE line on a
#   MODEL_EXEMPT match, so a false marker hit hides everything on that line, not just itself. Confirmed
#   live pre-fix: a fixture line naming a genuinely stale id and containing "model-id-exemption-only"
#   printed "CADENCE CONSISTENCY: OK" and exited 0. Fixed by adding a trailing \b.
#   Round 2 (this fix): a trailing \b is satisfied by ANY non-word character, including '-', so a
#   LONGER hyphen-continued token that merely STARTS WITH the marker -- a filename or config-key
#   mention like 'model-id-exempt-list.md' or 'model-id-exempt-routines:' -- also matched and, same as
#   Round 1, silently suppressed a genuine drift reported on the same line. Confirmed live pre-fix:
#   'model-id-exempt-list.md' and 'model-id-exempt-routines:' both matched \bmodel-id-exempt\b (the '-'
#   right after 'exempt' already satisfies a trailing \b). Fixed by replacing the trailing \b with a
#   negative lookahead that additionally rejects a hyphen continuation, `(?![-\w])`: the marker token
#   must be followed by end-of-string or a character that is neither '-' nor a word character (a space,
#   '.', ',', ')', backtick, etc. -- exactly the ordinary prose punctuation that follows a real,
#   standalone marker) to suppress. 'model-id-exempt', 'model-id-exempt.', 'marked model-id-exempt, a
#   cite' all still suppress; 'model-id-exempt-list.md', 'model-id-exempt-routines:',
#   'model-id-exemption-only' ('i' is a word char), 'model-id-exempted' ('e' is a word char), and
#   'nonmodel-id-exempt' (no left \b -- 'n' before 'model' is a word char) do not.
MODEL_EXEMPT = re.compile(r"\bmodel-id-exempt(?![-\w])")
# KNOWN, DELIBERATE LIMIT (model-id-exempt is LINE-SCOPED — documented 2026-07-28, do NOT implement the
# escape hatch below pre-emptively): check_model_of_record() skips the ENTIRE line on a MODEL_EXEMPT
# match, not just the token nearest the marker. A legitimate exemption for one, historical id on a line
# therefore also hides any OTHER, genuinely wrong id sharing that same line. Confirmed live: with
# routine_model='claude-opus-5', the line "In 2026-07 we migrated from claude-sonnet-4
# (model-id-exempt) to claude-opus-6 as the new fleet model." matches MODEL_EXEMPT (True) and is
# skipped whole — the pre-skip scan would have found BOTH 'claude-sonnet-4' and 'claude-opus-6', the
# latter a real drift (routine_model is 'claude-opus-5', not 'claude-opus-6'), but check_model_of_record
# never gets to look at either because the line-level skip fires first.
#   WHY THIS IS DIFFERENT FROM THE ROUNDS 1-6 FIXES: every other miss this file's history documents was
#   the CHECKER failing to see something on its own — a regex too narrow, a strip too greedy, a boundary
#   too loose — with no human involvement at the site of the miss. This one requires a human to have
#   typed the literal marker 'model-id-exempt' onto that exact line, which is an explicit, author-signed
#   assertion that the author reviewed that line and takes responsibility for what it contains. Line
#   scope is therefore the INTENDED contract of the marker, not an accidental gap: it is opt-in silence
#   at a spot a human already looked at, not the check silently missing something nobody looked at.
#   Do NOT "fix" this by narrowing MODEL_EXEMPT's suppression to some token-proximity heuristic (e.g.
#   "only the nearest id") — proximity is a shape-based guess with the same failure mode Rounds 1/2
#   above rejected for MODEL_ID_CORE itself, and it would silently change the meaning of every
#   'model-id-exempt' marker already written into the tree today.
#   ESCAPE HATCH IF THIS EVER BITES IN PRACTICE (record only — NOT implemented, do not add pre-emptively):
#   a scoped marker form 'model-id-exempt:<id>' that suppresses only the named token instead of the
#   whole line, backward compatible with the existing bare marker (a bare 'model-id-exempt' keeps
#   meaning "whole line," as today). If a future audit finds a real line that needs one id exempted
#   while a second, different id on the same line must still be caught, implement the scoped form then —
#   do not add it speculatively ahead of a real, observed need.


def _tooling_prefix_hides_version(token, prefix):
    """True if the characters immediately after `prefix` in `token` look like a version suffix — a '-'
    or '.' followed by a DIGIT, e.g. 'claude-code-5', 'claude-code-4-8', 'claude-cli-2.1' — rather than
    a tooling-name extension like 'claude-code-action' or 'claude-code-settings.json'.

    DEFECT B (2026-07-28 adversarial review): NOT_A_MODEL_PREFIXES exists to subtract CLI/SDK tooling
    names, never a model — but matching it with a blunt str.startswith() silently swallowed a
    hypothetical real model that happens to share a tooling prefix's name (confirmed live:
    'claude-code-5' returned zero errors against routine_model='claude-opus-5'). A version-shaped
    remainder is a positive signal the token names something OTHER than the tooling product itself, so
    such a token must stay FLAGGED (loud) rather than be subtracted as "just tooling".

    DEFECT B, CONTINUED (2026-07-28, same-day follow-up): the original fix only recognized a version
    when a literal '-' or '.' SEPARATES it from the prefix ('claude-code-5'). A digit GLUED directly
    onto the prefix with no separator ('claude-code5') fell through both branches and was silently
    subtracted as ordinary tooling — confirmed live: 'claude-code5' (and 'claude-code58', 'claude-cli9',
    'claude-desktop3', 'claude-agent-sdk7') returned zero errors. A leading digit is exactly as strong a
    version-shaped signal as a separator-prefixed one, so it must also stay FLAGGED."""
    rest = token[len(prefix):]
    if not rest:
        return False
    if rest[0].isdigit():
        return True
    return rest[0] in "-." and len(rest) >= 2 and rest[1].isdigit()


def _is_subtracted_non_assertion(token):
    """True if `token` (a MODEL_ID_RE match already known to differ from routine_model) belongs to the
    one precisely-known non-assertion class the broad match must SUBTRACT — see "THE DESIGN" above:
    tokens naming CLI/SDK tooling (NOT_A_MODEL_PREFIXES), unless the remainder right after the matched
    prefix looks version-shaped, in which case the token is left FLAGGED (DEFECT B, see
    _tooling_prefix_hides_version).

    DEFECT A (2026-07-28 adversarial review) deleted this function's second, unsound subtraction — "a
    slug that merely extends the correct routine_model with a citation suffix" — entirely; see the
    comment block above MODEL_ID_CORE for the live repros that forced the removal and why no shape-only
    replacement is possible. Do NOT re-add a routine_model-dependent branch here."""
    for prefix in NOT_A_MODEL_PREFIXES:
        if token.startswith(prefix):
            return not _tooling_prefix_hides_version(token, prefix)
    return False


def check_model_of_record():
    """`routine_model` exists and is well-formed, and every mirror site quotes the same id."""
    errs = []
    doc = load_yaml(CADENCE)
    model = doc.get("routine_model")
    if model is None:
        return ["ops/cadence.yaml: missing top-level 'routine_model' — it is the source of truth for "
                "which Claude model the owner configured for the remote-routine fleet, and A1/Q3/A3 "
                "read it to anchor AI_Trading_Foundation.md's in-use-version field. Re-add it."], None
    if not (isinstance(model, str) and MODEL_ID_VALID.fullmatch(model)):
        return [f"ops/cadence.yaml: routine_model must be a bare Claude model id like "
                f"'claude-opus-5' (got {model!r})"], None
    if not model[-1].isalnum():
        # MODEL_ID_CORE's tail class ([a-z0-9.\-]*) admits a trailing '-' or '.', so a value like
        # 'claude-opus-5-' or 'claude-opus-5.' passes MODEL_ID_VALID.fullmatch() above as
        # well-formed -- but MODEL_ID_RE's trailing \b cannot terminate a match right after that same
        # non-word character, so the mirror scanner recovers only the SHORTER token 'claude-opus-5'
        # from prose naming this exact value. Left unchecked, check_model_of_record() would then
        # report BOTH a mirror line AND this very ops/cadence.yaml line as drifted -- a
        # self-contradictory report pointing the author at the line that IS the source value. Reject
        # it here instead, explicitly naming the trailing character so the fix is obvious.
        return [f"ops/cadence.yaml: routine_model must be a bare Claude model id like "
                f"'claude-opus-5' (got {model!r} — it ends with {model[-1]!r}, a trailing "
                f"non-alphanumeric character the mirror scanner's word-boundary match can never "
                f"include, so this value could never be found in full by MODEL_ID_RE)"], None
    if model.startswith(NOT_A_MODEL_PREFIXES):
        return [f"ops/cadence.yaml: routine_model must be a bare Claude model id like "
                f"'claude-opus-5' (got {model!r} — this names CLI/SDK tooling, never a model; every "
                f"mirror-site token that starts with it would be subtracted as tooling too, making "
                f"this whole check vacuous)"], None
    for path in model_mirror_files():
        if not os.path.exists(path):
            continue
        rel = os.path.relpath(path, ROOT)
        for n, line in enumerate(open(path, encoding="utf-8"), 1):
            if MODEL_EXEMPT.search(line):
                continue
            scanned = URL_RE.sub(" ", line)
            # dict.fromkeys, not set(...): de-dupes while preserving FIRST-APPEARANCE order, so two
            # distinct wrong ids on one line report in a deterministic (left-to-right) order instead of
            # one that varies with PYTHONHASHSEED (2026-07-28 adversarial review).
            for found in dict.fromkeys(MODEL_ID_RE.findall(scanned)):
                if found == model or _is_subtracted_non_assertion(found):
                    continue
                errs.append(
                    f"{rel}:{n}: names model '{found}' but ops/cadence.yaml routine_model is "
                    f"'{model}'. All remote routines run the SAME model, so every mirror must "
                    f"quote it. If the owner changed the fleet model, update routine_model AND "
                    f"this line in the same pass; if this line is illustrative or historical "
                    f"rather than a fleet assertion, add the marker 'model-id-exempt' to it.")
    return errs, model

# The RUNBOOK §38 marker-write routine-id allowlist: routine_re='^(D1|D2a|...)$'
AUTO_MERGE_ROUTINE_RE = re.compile(r"routine_re='\^\(([^)]+)\)\$'")

# state.cadence_period_watch's OFFSET-N literals, keyed by the column alias they compute.
PERIOD_GRACE_OFFSET = re.compile(r"OFFSET (\d+)\)\s*AS (month|quarter|year)_grace_day")
# The weekly grace is a calendar-day count from that week's Sunday (not an OFFSET into trading days).
PERIOD_GRACE_WEEKLY = re.compile(r"DATE_ADD\(n\.week_start,\s*INTERVAL (\d+) DAY\)")

# The four "period" monitor_class values (check J/K's period tier + the ROUTINE INVENTORY cadence-cell
# mapping, check L). daily_trading/daily_all are the "daily" tier (check K's bigquery/31 side).
PERIOD_CLASSES = {"weekly_sun", "monthly_ftd", "quarterly_ftd", "annual_ftd"}
# daily_sun_thu added 2026-08-08 (daily-tier Fri/Sat consolidation onto Sunday, ops/cadence.yaml):
# every Sunday-Thursday calendar day, NOT trading-day-gated -- see ops/cadence.yaml's DAILY-TIER
# FRI/SAT CONSOLIDATION header note. It is a DAILY_CLASSES member (not a PERIOD_CLASSES one) for
# every purpose DAILY_CLASSES feeds: check K's bigquery/31_catchup_notify.sql daily-tier UNNEST
# list, and the ALLOWED_CLASSES/CALENDAR_CLASSES vocabulary below.
DAILY_CLASSES = {"daily_trading", "daily_all", "daily_sun_thu"}

# ---- check M (H1, whole-system deep audit 2026-07-17): the EVENING-slot daily cohort's SAME-DAY
# DOUBLE-RUN GUARD copies must carry the noon-threshold clause. bigquery/12's midnight-crossing grace
# can stamp a post-midnight prior-day run onto today's run_date; without counting ONLY completions
# whose log_ts is in the real evening window, that mis-stamped early-AM completion cancels the genuine
# evening run. D1/D2/D3/SL3 each carry a per-routine guard copy in Claude_Task_Plan.md (D2a has no
# per-routine copy — its double-run risk is covered by D2's own guard, not a copy of its own). Each
# copy's ops.run_log COUNT(*) query must therefore also filter
# `AND DATETIME(log_ts,'America/Denver') >= DATETIME(<today...>, TIME '12:00:00')`.
EVENING_DAILY_GUARD_IDS = ("D1", "D2", "D3", "SL3")
# The guard query's stable prefix (D2's copy omits the ", America/Denver" qualifier on <today>, so the
# run_date token is matched loosely), capturing what follows status='completed' up to the closing `.
GUARD_QUERY_RE = {
    rid: re.compile(
        r"routine='%s' AND run_date=<today[^>]*> AND status='completed'(?P<after>[^`]{0,160})" % rid)
    for rid in EVENING_DAILY_GUARD_IDS
}
GUARD_NOON_CLAUSE_RE = re.compile(
    r"AND DATETIME\(log_ts,'America/Denver'\) >= DATETIME\(<today[^>]*>, TIME '12:00:00'\)")

# ---- check J: bigquery/24's post-normalization STRUCT rows are ALWAYS fully labelled (both
# `AS routine` and `AS monitor_class`) -- scripts/gen_routine_lists.py emits every row this way.
PERIOD_WATCH_ROUTINE_ROW = re.compile(
    r"STRUCT\('([^']+)'\s+AS routine,\s*'([^']+)'\s+AS monitor_class\)")

# ---- check K: bigquery/31/59's hand-maintained catchup-safe UNNEST([...]) AS routine id lists.
SQL_LINE_COMMENT = re.compile(r"--[^\n]*")
UNNEST_ROUTINE_BRACKET = re.compile(r"UNNEST\(\[(.*?)\]\)\s*AS routine", re.S)
QUOTED_ID = re.compile(r"'([A-Za-z0-9_]+)'")

# ---- check L: the ROUTINE INVENTORY table section of Claude_Task_Plan.md (scoped between its own
# heading and the NEXT '---' divider -- the strategy slice-map table elsewhere in the file also has
# `| **...** |`-shaped rows and must NOT be swept in).
INVENTORY_HEADING = "# ROUTINE INVENTORY & BIGQUERY RESPONSIBILITIES"
# 2026-07-29: an earlier version of this file tried to tell parse_inventory_table()'s two None cases
# apart -- "heading never introduced" (pre-feature checkout, skip silently) vs. "heading text changed"
# (regex rot, fail loud) -- via a loose substring search for "ROUTINE INVENTORY": substring present but
# exact heading missing => DISARMED (fail loud); substring absent too => assume pre-feature checkout and
# skip. PROVEN DEFEATABLE the same day: renaming the heading to something that also drops the substring
# (e.g. "# ROUTINE ROSTER & BIGQUERY RESPONSIBILITIES") makes BOTH branches miss, so main() exits 0
# silently -- reproducing the exact bug the heuristic was built to catch, for precisely the class of
# edit (a heading rewording) it existed to catch. The heuristic is deleted here, not re-tuned: a
# substring test can always be defeated by a rewording that drops the substring too, so no replacement
# substring closes that hole for good. Claude_Task_Plan.md is not optional and the ROUTINE INVENTORY
# table is a mandatory section of it, so "the table can't be found" was never actually a legitimate
# skip case either -- main() now treats BOTH None cases (heading reworded, section removed) as one
# unconditional hard error instead of trying to distinguish them.
# Columns: | ID | Routine | Cadence · Type | BigQuery reads | BigQuery writes | Cadence .md output |
# — group 1 is the id, group 2 is the 'Cadence · Type' cell (the 3rd column; the 2nd, the routine
# name, is skipped over).
INVENTORY_ROW = re.compile(r"^\|\s*\*\*([A-Za-z0-9_]+)\*\*\s*\|[^|]*\|([^|]*)\|", re.M)
# First token of the 'Cadence · Type' cell -> the set of monitor_class values it may legitimately mean.
INVENTORY_CADENCE_TOKEN_MAP = {
    "Daily": DAILY_CLASSES,
    # "Sun-Thu" added 2026-08-08 (daily-tier Fri/Sat consolidation onto Sunday) -- the distinct,
    # ASCII-only token for the 8 routines (D1/D2a/D2/D3/OPS0/OPS1/OPS2/SL3) that moved to
    # monitor_class: daily_sun_thu, so the ROUTINE INVENTORY table can tell a reader "runs
    # Sunday-Thursday only" apart from "Daily" (still every calendar/trading day) at a glance.
    # ASCII hyphen deliberately, not an en/em dash -- see ops/cadence.yaml's own MODEL_ID_CORE-
    # adjacent lesson on ASCII-only tokens elsewhere in this repo's checkers.
    "Sun-Thu": {"daily_sun_thu"},
    "Weekly": {"weekly_sun"},
    "Monthly": {"monthly_ftd"},
    "Quarterly": {"quarterly_ftd"},
    "Annual": {"annual_ftd"},
    "Queue-driven": {"queue_driven"},
}
# AR_att/AR_orc's cell reads 'Daily¹' (footnote ¹: queue-driven, fires daily but no-ops unless due).
INVENTORY_FOOTNOTE_QUEUE_DRIVEN_IDS = {"AR_att", "AR_orc"}

ALLOWED_CLASSES = {
    "daily_trading", "daily_all", "daily_sun_thu", "weekly_sun",
    "monthly_ftd", "quarterly_ftd", "annual_ftd", "queue_driven",
}
# monitor_class values the calendar view (state.cadence_expected_today) must encode.
CALENDAR_CLASSES = ALLOWED_CLASSES - {"queue_driven"}

# The state.cadence_watch deadline-guard literal: DATETIME(e.today, TIME 'HH:MM:SS'). Capture HH:MM.
SQL_DEADLINE = re.compile(r"DATETIME\(\s*e\.today\s*,\s*TIME\s*'(\d{2}:\d{2})(?::\d{2})?'\s*\)")
HHMM = re.compile(r"^\d{2}:\d{2}$")

# `CREATE [OR REPLACE] VIEW `stock-trading-498512.state.cadence_watch`` — matched against
# comment-stripped text (see find_canonical_cadence_watch_file() below) so a header/prose mention can
# never be mistaken for a live definition, same discipline check_superseded_markers.py's OBJECT_DDL and
# check_sq_version_registry.py's PROC_DDL already use for this exact class of false-positive.
CADENCE_WATCH_VIEW_DDL = re.compile(
    r"CREATE\s+(?:OR\s+REPLACE\s+)?VIEW\s+`stock-trading-498512\.state\.cadence_watch`",
    re.IGNORECASE,
)

# ---- check O (2026-08-08 audit follow-up to bigquery/148): state.stalled_runs is the ONLY thing that
# ever raises the `routine_stalled` alert -- a routine that logged 'started' but never a terminal row.
# Its hand-maintained `cls` CTE (an UNNEST([STRUCT(...), ...]) id -> min_stale_hours table) is joined
# with `JOIN cls c USING (routine)`, an INNER join, so a routine id absent from that list is dropped
# BEFORE the terminal-row anti-join or the elapsed-hours threshold are ever evaluated: it can hang
# forever and never be flagged. Not hypothetical -- `cls` was last edited 2026-07-10; OPS0/OPS1/OPS2
# were added to ops/cadence.yaml on 2026-07-15/07-19/07-27 with no matching `cls` edit, so all three
# (having already logged 16 'started' rows) were invisible to stall detection until bigquery/148 fixed
# it on 2026-08-08. Nothing ever compared the two lists, so nothing caught the drift -- this check is
# that comparison, in BOTH directions: a routine in cadence.yaml but missing from `cls` can never be
# flagged (the exact OPS0/OPS1/OPS2 gap); an id in `cls` but not in cadence.yaml is a stale entry for a
# retired/renamed routine.
#
# Resolved DYNAMICALLY against whichever bigquery/*.sql file currently defines `CREATE OR REPLACE VIEW
# state.stalled_runs` (never hardcoded to bigquery/148 -- the view has already moved once, 18 -> 148,
# and hardcoding the file here would itself be exactly the class of rot this check exists to prevent).
# Reuses the same numbered_sql_files()/resolve_canonical() machinery and ambiguous-winner contract (D6,
# 2026-08-06) that find_canonical_cadence_watch_file() above already established for state.cadence_
# watch, applied to a second, independently-superseded view -- see STALLED_RUNS_BIGQUERY_DIR's own
# comment (near BIGQUERY_DIR) for why this is a separate directory constant rather than a reuse of
# BIGQUERY_DIR itself.
# Matched against comment-stripped text, same discipline as CADENCE_WATCH_VIEW_DDL above.
STALLED_RUNS_VIEW_DDL = re.compile(
    r"CREATE\s+(?:OR\s+REPLACE\s+)?VIEW\s+`stock-trading-498512\.state\.stalled_runs`",
    re.IGNORECASE,
)
# Scoped to the `cls` CTE's own UNNEST([...]) bracket -- not a blind whole-file STRUCT( scan -- so a
# STRUCT(...) belonging to a LATER, unrelated statement in the same multi-statement file (bigquery/148
# defines several objects) can never leak in. The non-greedy `.*?` stops at the FIRST `])`, which is
# exactly the array's own close (the STRUCT(...) entries inside contain no `[`/`]` of their own).
# Comments are stripped by the CALLER (parse_stalled_runs_cls_ids, via lib.sql_files.strip_sql_
# comments) before this ever runs, so a commented-out or illustrative STRUCT('X', 6) in prose (e.g.
# this view's own header, which narrates past `cls` entries by name) can never be read as a live entry.
CLS_CTE_UNNEST_RE = re.compile(
    r"\bcls\s+AS\s*\(\s*SELECT\s*\*\s*FROM\s*UNNEST\(\s*\[(.*?)\]\s*\)", re.S)
# Handles BOTH spellings actually present in the real body: the CTE's first entry is labelled
# (STRUCT('D1' AS routine, 6 AS min_stale_hours)) and every later one is positional (STRUCT('D2a', 6)).
CLS_ENTRY_RE = re.compile(r"STRUCT\('([A-Za-z0-9_]+)'(?:\s+AS\s+routine)?\s*,")


def plan_headings():
    """Ordered routine section headings from Claude_Task_Plan.md (shared parser)."""
    return parse_routine_headings(PLAN)


def load_cadence():
    doc = load_yaml(CADENCE)
    return {r["id"]: r for r in cadence_routines(doc)}


def cadence_duplicate_ids():
    """[id, ...] (sorted, deduped) for any routine id appearing more than once in ops/cadence.yaml's
    routines list. load_cadence()'s dict comprehension above silently keeps only the LAST such entry
    (valid YAML, no parse error -- a duplicate `id:` across list items, not a duplicate mapping key),
    so every downstream check would validate against whichever duplicate happened to be listed last
    with zero signal. This walks the raw list first so a duplicate id fails loud instead, mirroring
    the duplicate Claude_Task_Plan.md heading check main() already does for `head_by_id` below."""
    doc = load_yaml(CADENCE)
    ids = [r["id"] for r in cadence_routines(doc)]
    return sorted({i for i in ids if ids.count(i) > 1})


def parse_expected_sql():
    """{routine: schedule_class} from the STRUCT(... AS routine, ... AS schedule) list in 12_*.sql."""
    txt = read_text(CADENCE_SQL)
    pat = re.compile(r"STRUCT\('([^']+)'\s+AS routine,\s*'([^']+)'\s+AS schedule\)")
    return dict(pat.findall(txt))


def parse_catalog_sql():
    """{routine: canonical_instruction} from 15_*.sql (handles the first AS-labelled row + shorthand rows).

    The instruction literal may contain BigQuery-escaped single quotes (''), emitted by
    scripts/gen_routine_lists.py gen_15_region (_sql_str) when a routine heading contains an
    apostrophe. Match those doubled quotes and un-escape '' -> ' so the parsed value equals check B's
    want_catalog (derived from the RAW heading text). This is the paired half of gen_15_region's
    escaping -- the two MUST stay in lockstep. Byte-identical on a tree with no apostrophe headings."""
    txt = read_text(CATALOG_SQL)
    pat = re.compile(
        r"STRUCT\('([^']+)'(?:\s+AS routine)?,\s*'(Read Claude_Task_Plan\.md\. Perform (?:[^']|'')*)'")
    return {rid: instr.replace("''", "'") for rid, instr in pat.findall(txt)}


def parse_deadline_sql():
    """['HH:MM', ...] from the DATETIME(e.today, TIME 'HH:MM:SS') deadline guard in 12_*.sql (state.cadence_watch)."""
    return SQL_DEADLINE.findall(read_text(CADENCE_SQL))


def find_canonical_cadence_watch_file():
    """(number, filename, ambiguous_files) for the highest-numbered bigquery/*.sql file that defines
    `CREATE OR REPLACE VIEW state.cadence_watch` — the object has been redefined across several
    superseding files (12 -> 48 -> 113 -> 129 -> 142, and counting), and the highest-numbered occurrence
    is the one actually deployed live. Resolution goes through scripts/lib/sql_files.py's shared
    resolve_canonical() (order-independent max() over parsed file numbers, same construction
    check_superseded_markers.py's violations() and check_sq_version_registry.py's resolve_winners()
    already use for this exact "which file wins" question — see those scripts' module docstrings for
    why iteration order does not matter here).

    ambiguous_files is None in the normal case. bigquery/*.sql's NN_ leading number is NOT guaranteed
    unique (two files already share 114 in this repo today — see resolve_canonical()'s own docstring);
    if a FUTURE file at a duplicated number also defined `state.cadence_watch`, a bare max() could no
    longer tell the two apart and would silently validate whichever sorted first. When that happens,
    `filename` is None and `ambiguous_files` is the sorted list of every colliding filename — the
    caller MUST treat that as a hard error, never pick one on its own (D6, 2026-08-06 adversarial
    audit). Dormant on the real tree today: verified neither bigquery/114 file defines this view.

    Returns (None, None, None) if no occurrence is found at all (should never happen on a real
    checkout — CADENCE_SQL itself always defines one)."""
    occurrences = []
    for number, path in numbered_sql_files(BIGQUERY_DIR):
        if os.path.isdir(path):
            continue
        text = strip_sql_comments(read_text(path))
        if CADENCE_WATCH_VIEW_DDL.search(text):
            occurrences.append((number, os.path.basename(path)))
    if not occurrences:
        return None, None, None
    winner_number, winner_files = resolve_canonical(occurrences)
    if len(winner_files) > 1:
        return winner_number, None, winner_files
    return winner_number, winner_files[0], None


def parse_canonical_deadline_sql():
    """(['HH:MM', ...], number, filename, ambiguous_files) — the state.cadence_watch deadline-guard
    literal(s) parsed from the CANONICAL (highest-numbered) bigquery/*.sql file defining that view, NOT
    the fixed bigquery/12_cadence_monitor.sql parse_deadline_sql() above is pinned to (that original
    file is itself long superseded — 48 -> 113 -> 129 -> 142 and counting — so a deadline change landed
    only in a superseding file previously had NO consistency guard tying it back to ops/cadence.yaml at
    all, the same registry-vs-body split class check_sq_version_registry.py exists to catch for a
    heartbeat literal, applied here to this view instead).

    Comments are stripped first (scripts/lib/sql_files.strip_sql_comments) before SQL_DEADLINE runs, so
    a header/prose mention of a TIME literal — e.g. a file's own header narrating a before/after deadline
    change in prose — can never be mistaken for the live guard clause. This differs from the plain
    parse_deadline_sql() above, which does not strip comments; that has been harmless in practice only
    because bigquery/12's header has never happened to contain a matching digit-literal false positive.

    ambiguous_files is None in the normal case; see find_canonical_cadence_watch_file()'s own docstring
    (D6, 2026-08-06) — when it is NOT None, `fn` is None too and the caller must report the ambiguity
    rather than parse a (nonexistent, unpickable) single winning file.
    Returns ([], None, None, None) if no canonical file/definition could be found at all."""
    number, fn, ambiguous_files = find_canonical_cadence_watch_file()
    if ambiguous_files is not None:
        return [], number, None, ambiguous_files
    if fn is None:
        return [], number, fn, None
    text = strip_sql_comments(read_text(os.path.join(BIGQUERY_DIR, fn)))
    return SQL_DEADLINE.findall(text), number, fn, None


def find_canonical_stalled_runs_file():
    """(number, filename, ambiguous_files) for the highest-numbered bigquery/*.sql file that defines
    `CREATE OR REPLACE VIEW state.stalled_runs` (check O) -- the object has been redefined once already
    (18 -> 148, and counting; bigquery/148's own header says "supersedes bigquery/18"). Mirrors
    find_canonical_cadence_watch_file() above exactly, including its ambiguous-winner contract (D6,
    2026-08-06): `ambiguous_files` is None in the normal case; when it is NOT None, `filename` is None
    too and the caller must report every colliding filename rather than pick one. Scans
    STALLED_RUNS_BIGQUERY_DIR, not BIGQUERY_DIR directly -- see that constant's own comment for why the
    two are kept separate.

    Returns (None, None, None) if no occurrence is found at all (should never happen on a real
    checkout)."""
    occurrences = []
    for number, path in numbered_sql_files(STALLED_RUNS_BIGQUERY_DIR):
        if os.path.isdir(path):
            continue
        text = strip_sql_comments(read_text(path))
        if STALLED_RUNS_VIEW_DDL.search(text):
            occurrences.append((number, os.path.basename(path)))
    if not occurrences:
        return None, None, None
    winner_number, winner_files = resolve_canonical(occurrences)
    if len(winner_files) > 1:
        return winner_number, None, winner_files
    return winner_number, winner_files[0], None


def parse_stalled_runs_cls_ids():
    """([routine_id, ...], number, filename, ambiguous_files) — the routine ids inside the `cls` CTE's
    UNNEST([...]) STRUCT list of the CANONICAL (highest-numbered) bigquery/*.sql file currently
    defining state.stalled_runs (check O). Comments are stripped first (lib.sql_files.strip_sql_
    comments) so a commented-out or illustrative STRUCT('X', 6) can never be read as a live entry, and
    the parse is scoped to the `cls` CTE's own UNNEST bracket (CLS_CTE_UNNEST_RE) rather than a blind
    whole-file STRUCT( scan, so a STRUCT(...) belonging to a later, unrelated statement in the same
    file can never leak in.

    Returns ([], number, filename, None) — an EMPTY list, never None — if the file was found but the
    `cls` CTE/UNNEST bracket could not be parsed (regex rot): main() must treat that as a hard error,
    never a silent skip (a checker that quietly validates nothing is the exact failure class this repo
    keeps getting bitten by). ambiguous_files mirrors find_canonical_stalled_runs_file()'s contract:
    non-None means the file itself could not be uniquely resolved, in which case ids is always []."""
    number, fn, ambiguous_files = find_canonical_stalled_runs_file()
    if ambiguous_files is not None:
        return [], number, None, ambiguous_files
    if fn is None:
        return [], number, fn, None
    text = strip_sql_comments(read_text(os.path.join(STALLED_RUNS_BIGQUERY_DIR, fn)))
    m = CLS_CTE_UNNEST_RE.search(text)
    if m is None:
        return [], number, fn, None
    return CLS_ENTRY_RE.findall(m.group(1)), number, fn, None


def cadence_deadline_yaml():
    """Top-level cadence_watch_deadline_local from ops/cadence.yaml (raw value, or None)."""
    doc = load_yaml(CADENCE)
    return doc.get("cadence_watch_deadline_local")


def cadence_period_grace_yaml():
    """Top-level period_grace_days from ops/cadence.yaml (dict, or None)."""
    doc = load_yaml(CADENCE)
    return doc.get("period_grace_days")


def parse_period_grace_sql():
    """{monitor_class: grace_days} from bigquery/24_cadence_period_watch.sql.

    month/quarter/year are OFFSET N (0-indexed -> the (N+1)th trading day); weekly is a plain
    calendar-day count already expressed the same way period_grace_days.weekly_sun is (1 = Monday).
    Returns None if the file is absent (pre-2026-07-03 checkout) so the caller can skip check E.
    """
    if not os.path.exists(PERIOD_WATCH_SQL):
        return None
    txt = read_text(PERIOD_WATCH_SQL)
    out = {}
    for offset, which in PERIOD_GRACE_OFFSET.findall(txt):
        cls = {"month": "monthly_ftd", "quarter": "quarterly_ftd", "year": "annual_ftd"}[which]
        out[cls] = int(offset) + 1
    m = PERIOD_GRACE_WEEKLY.search(txt)
    if m:
        out["weekly_sun"] = int(m.group(1))
    return out


def parse_period_watch_routines_sql():
    """{routine: monitor_class} from bigquery/24_cadence_period_watch.sql's `routines` CTE
    (check J) — post-normalization (scripts/gen_routine_lists.py --write) every row is fully
    labelled `STRUCT('<id>' AS routine, '<class>' AS monitor_class)`. Returns None if the file is
    absent (pre-feature checkout) so the caller can skip check J, same convention as check E's
    parse_period_grace_sql."""
    if not os.path.exists(PERIOD_WATCH_SQL):
        return None
    txt = read_text(PERIOD_WATCH_SQL)
    return dict(PERIOD_WATCH_ROUTINE_ROW.findall(txt))


def parse_unnest_routine_ids(path):
    """Ids inside a `... UNNEST([ ... ]) AS routine` bracket (check K), `--` line comments stripped
    FIRST so an inline comment naming an id (e.g. "-- SL4 (rev ...)") can never be mistaken for a
    quoted list entry. Returns None if `path` does not exist OR if no such bracket is found. main()
    DISTINGUISHES the two by os.path.exists: a file that is ABSENT skips check K silently (pre-
    feature checkout), but a file that is PRESENT-but-unparseable FAILS check K loudly — otherwise a
    reformat that breaks the regex (`AS  routine`, `UNNEST(ARRAY[...]`) would silently disarm the
    only drift guard bigquery/31 and 59 have (2026-07-17 audit — the same regex-rot vacuous-pass
    class checks A/D/E/J/L already fail loud on by returning an empty container, not None)."""
    if not os.path.exists(path):
        return None
    txt = SQL_LINE_COMMENT.sub("", read_text(path))
    m = UNNEST_ROUTINE_BRACKET.search(txt)
    if m is None:
        return None
    return QUOTED_ID.findall(m.group(1))


def parse_inventory_table(plan_path):
    """[(id, cadence_type_cell), ...] rows from ONLY the ROUTINE INVENTORY section of the plan —
    scoped between the "# ROUTINE INVENTORY & BIGQUERY RESPONSIBILITIES" heading and the NEXT `---`
    divider, so the strategy slice-map table elsewhere in the file (which also has `| **...** |`-
    shaped rows, e.g. `| **AR_attacker** |`) can never leak in (check L). Returns None if the exact
    heading text is not found (reworded, or the whole section removed) — main() treats that as a
    single unconditional hard error rather than trying to tell the two cases apart: the ROUTINE
    INVENTORY table is a mandatory section of Claude_Task_Plan.md (which is itself not optional), so
    there is no legitimate case where its absence should be a silent skip (2026-07-29 — replaced a
    substring-based disambiguation that a heading rewording could defeat, see the comment above
    INVENTORY_HEADING)."""
    txt = read_text(plan_path)
    start = txt.find(INVENTORY_HEADING)
    if start == -1:
        return None
    rest = txt[start + len(INVENTORY_HEADING):]
    end = rest.find("\n---")
    section = rest if end == -1 else rest[:end]
    return INVENTORY_ROW.findall(section)


def generate_triggers_manifest(head_by_id, cad):
    """The canonical {id: {monitor_class, instruction}} map — same shape print_routines.py --write
    emits to ops/triggers.json. Delegates to the shared implementation (scripts/lib/routine_manifest.py)
    so CI verifies the committed file against the SAME code path print_routines.py --write uses,
    not an independently-maintained copy of it."""
    return build_triggers_manifest(list(head_by_id.values()), cad)


def check_depends_on(cad):
    """Error strings for any depends_on entry that is not a known routine id in cad (a dangling/typo'd
    dependency -- it feeds the FATAL ops.sp_assert_deps gate, so a silent typo here would abort a live
    routine at runtime instead of failing this offline check)."""
    errors = []
    for rid, r in cad.items():
        for dep in (r.get("depends_on") or []):
            if dep not in cad:
                errors.append(f"{rid}: depends_on '{dep}' is not a routine id in ops/cadence.yaml "
                              f"(dangling/typo'd dependency — it feeds the FATAL sp_assert_deps gate)")
    return errors


def catchup_list_errors(cad, path, filename, tier_word, classes):
    """Check K for ONE of bigquery/31/59's hand-maintained catchup-safe `UNNEST([...]) AS routine`
    lists: it must equal cadence.yaml's {catchup_safe AND monitor_class in <classes>} subset.

    An ABSENT file is skipped silently (pre-feature checkout); a PRESENT-but-unparseable file FAILS
    loudly (DISARMED) so a benign SQL reformat can never silently disarm the guard. The daily
    (bigquery/31) and period (bigquery/59) call sites differ only in (path, filename, tier_word,
    classes), so this shared helper keeps their two error strings — the observable contract — from
    ever drifting apart with a one-sided edit. Returns a list of error strings (possibly empty)."""
    want = {rid for rid, r in cad.items()
            if r.get("catchup_safe") is True and r.get("monitor_class") in classes}
    have = parse_unnest_routine_ids(path)
    if have is None and os.path.exists(path):
        return [
            f"{filename} exists but no `UNNEST([...]) AS routine` bracket could be "
            f"parsed — check K's catchup-safe {tier_word} drift guard is DISARMED (regex rot? e.g. a "
            f"reformat to `AS  routine` or `UNNEST(ARRAY[...]`). Restore a parseable bracket."]
    if have is not None:
        have_set = set(have)
        if have_set != want:
            return [
                f"{filename} catchup-safe {tier_word} UNNEST list DRIFT — "
                f"file has {sorted(have_set)}, cadence.yaml-derived (catchup_safe AND {tier_word} tier) "
                f"wants {sorted(want)}"]
    return []


def class_map_errors(want, have, *, missing_from, mismatch_label, mismatch_ref, extra_in, extra_not_a):
    """Shared want/have `{id: class}` MISSING / mismatch / extra comparison used by check A
    (state.cadence_expected_today vs 12_cadence_monitor.sql) and check J (state.cadence_period_watch's
    routines CTE vs 24_cadence_period_watch.sql) — both independently re-derived this exact
    three-branch loop, differing only in message wording (2026-07-29 dedup).

    Every message fragment is a caller-supplied literal rather than something templated from a single
    filename: the two call sites' existing wording is not even internally consistent with itself
    (check A's own "extra" message says "12_*.sql" while its "missing"/"mismatch" messages say
    "12_cadence_monitor.sql") and these messages are load-bearing — CI and a BigQuery bridge parse
    them — so preserving them byte-for-byte matters more than a cleaner single-filename template."""
    errors = []
    for rid, cls in want.items():
        if rid not in have:
            errors.append(f"{rid}: monitor_class={cls} in cadence.yaml but MISSING from {missing_from}")
        elif have[rid] != cls:
            errors.append(f"{rid}: {mismatch_label} — cadence.yaml='{cls}' vs {mismatch_ref}='{have[rid]}'")
    for rid in have:
        if rid not in want:
            errors.append(f"{rid}: in {extra_in} but not a {extra_not_a}")
    return errors


def main():
    cad = load_cadence()
    headings = plan_headings()
    errors = []

    # ---- duplicate routine id in ops/cadence.yaml's routines list (silently collapsed by
    # load_cadence()'s dict comprehension otherwise -- see cadence_duplicate_ids()'s docstring) ----
    for rid in cadence_duplicate_ids():
        errors.append(f"ops/cadence.yaml: duplicate routine id '{rid}' — each routine id must "
                      f"appear exactly once")

    # ---- canonical maps from the SOURCE OF TRUTH (cadence.yaml + the plan) ----
    head_by_id, dup = {}, []
    for h in headings:
        rid = heading_to_id(h)
        if rid is None:
            errors.append(f"plan heading does not map to a routine id (bad format?): '{h}'")
            continue
        if rid in head_by_id:
            dup.append(rid)
        head_by_id[rid] = h
    for rid in dup:
        errors.append(f"duplicate Claude_Task_Plan.md heading for id {rid}")

    # check B must derive its expectation from the SAME shared template check F uses (lib/
    # routine_manifest.instruction_text) rather than re-literalizing the f-string here -- that literal
    # was the 4th independent copy the 2026-07-20 extraction was supposed to kill (codebase audit
    # 2026-07-26): edit instruction_text's wording and regenerate bigquery/15 via gen_routine_lists.py
    # --write, and this hardcoded copy would silently compute the OLD string, failing CI for every
    # routine with a diff that points at cadence.yaml/plan headings instead of the real culprit.
    want_catalog = {rid: instruction_text(h) for rid, h in head_by_id.items()}
    want_expected = {rid: r["monitor_class"] for rid, r in cad.items()
                     if r.get("monitor_class") in CALENDAR_CLASSES}

    # ---- validate monitor_class presence + vocabulary ----
    for rid, r in cad.items():
        mc = r.get("monitor_class")
        if mc is None:
            errors.append(f"{rid}: missing monitor_class in ops/cadence.yaml")
        elif mc not in ALLOWED_CLASSES:
            errors.append(f"{rid}: monitor_class '{mc}' not in {sorted(ALLOWED_CLASSES)}")

    # ---- depends_on references must be known routine ids (silent-drift guard) ----
    errors.extend(check_depends_on(cad))

    # ---- C. cadence.yaml id <-> plan heading 1:1 ----
    for rid in cad:
        if rid not in head_by_id:
            errors.append(f"{rid}: in ops/cadence.yaml but no matching Claude_Task_Plan.md heading")
    for rid in head_by_id:
        if rid not in cad:
            errors.append(f"{rid}: Claude_Task_Plan.md heading but no ops/cadence.yaml routine")

    # ---- A. state.cadence_expected_today (12_*.sql) == calendar-class routines in cadence.yaml ----
    have_expected = parse_expected_sql()
    if not have_expected:
        errors.append("could not parse any STRUCT(... AS schedule) rows from 12_cadence_monitor.sql")
    errors.extend(class_map_errors(
        want_expected, have_expected,
        missing_from="state.cadence_expected_today (12_cadence_monitor.sql)",
        mismatch_label="schedule class mismatch", mismatch_ref="12_cadence_monitor.sql",
        extra_in="state.cadence_expected_today (12_*.sql)",
        extra_not_a="calendar-class routine in cadence.yaml (queue_driven/unknown routines must NOT be listed)"))

    # ---- B. ops.routine_catalog (15_*.sql) == plan-heading-derived instruction ----
    have_catalog = parse_catalog_sql()
    if not have_catalog:
        errors.append("could not parse any catalog STRUCT rows from 15_routine_catalog.sql")
    for rid, instr in want_catalog.items():
        if rid not in have_catalog:
            errors.append(f"{rid}: has a plan heading but is MISSING from ops.routine_catalog (15_*.sql)")
        elif have_catalog[rid] != instr:
            errors.append(f"{rid}: routine_catalog instruction drift\n"
                          f"     plan-derived: {instr}\n"
                          f"     15_*.sql:     {have_catalog[rid]}")
    for rid in have_catalog:
        if rid not in want_catalog:
            errors.append(f"{rid}: in ops.routine_catalog (15_*.sql) but has no Claude_Task_Plan.md heading")

    # ---- D. cadence_watch deadline guard: cadence.yaml constant == bigquery/12 SQL TIME literal ----
    want_deadline = cadence_deadline_yaml()
    have_deadlines = parse_deadline_sql()
    deadline_ok = True
    if want_deadline is None:
        errors.append("ops/cadence.yaml: missing top-level 'cadence_watch_deadline_local' "
                      "(declares the state.cadence_watch deadline-guard time)")
        deadline_ok = False
    elif not (isinstance(want_deadline, str) and HHMM.match(want_deadline)):
        errors.append(f"ops/cadence.yaml: cadence_watch_deadline_local must be a quoted \"HH:MM\" string "
                      f"(got {want_deadline!r} — an UNquoted 21:00 is YAML base-60 = 1260; always quote it)")
        deadline_ok = False
    if not have_deadlines:
        errors.append("bigquery/12_cadence_monitor.sql: could not parse the DATETIME(e.today, TIME '..') "
                      "deadline-guard literal from state.cadence_watch (did the clause change shape?)")
        deadline_ok = False
    elif len(set(have_deadlines)) > 1:
        errors.append(f"bigquery/12_cadence_monitor.sql: multiple distinct deadline literals "
                      f"{sorted(set(have_deadlines))} in state.cadence_watch — expected exactly one")
        deadline_ok = False
    if deadline_ok and have_deadlines[0] != want_deadline:
        errors.append(f"cadence_watch deadline DRIFT — ops/cadence.yaml='{want_deadline}' vs "
                      f"bigquery/12_cadence_monitor.sql TIME='{have_deadlines[0]}'. Keep them in sync.")

    # ---- D (extended, 2026-08-06, bigquery/142 revert follow-up): the CANONICAL (highest-numbered)
    # bigquery/*.sql file CURRENTLY defining state.cadence_watch must ALSO agree with cadence.yaml.
    # bigquery/12 is itself long superseded (48 -> 113 -> 129 -> 142); the check above only ever compared
    # against that original, no-longer-deployed body, so a deadline change landed in a superseding file
    # (129's 21:00->21:45 autotune, then 142's revert back to 21:00) had NO CI guard tying it back to
    # cadence.yaml at all — the same registry-vs-body split class check_sq_version_registry.py exists to
    # catch for a heartbeat literal, applied here to this view. ----
    canon_deadlines, canon_number, canon_fn, canon_ambiguous = parse_canonical_deadline_sql()
    canon_deadline_ok = True
    if canon_ambiguous is not None:
        errors.append(
            f"AMBIGUOUS canonical file for state.cadence_watch — bigquery/{canon_number} is the "
            f"winning (highest) leading number, but {len(canon_ambiguous)} DIFFERENT files share it "
            f"and each defines `CREATE OR REPLACE VIEW state.cadence_watch`: "
            f"{', '.join('bigquery/' + fn for fn in canon_ambiguous)}. Check D's canonical-file "
            f"deadline guard cannot determine which is actually deployed — renumber one file so the "
            f"leading number is unique, or determine which definition is actually deployed and "
            f"delete/renumber the other.")
        canon_deadline_ok = False
    elif canon_fn is None:
        errors.append("could not find any bigquery/*.sql file defining "
                      "`CREATE OR REPLACE VIEW state.cadence_watch` at all — check D's canonical-file "
                      "deadline guard cannot run")
        canon_deadline_ok = False
    else:
        if not canon_deadlines:
            errors.append(f"bigquery/{canon_fn}: could not parse the DATETIME(e.today, TIME '..') "
                          f"deadline-guard literal from its state.cadence_watch definition (the "
                          f"highest-numbered file currently defining it — did the clause change shape?)")
            canon_deadline_ok = False
        elif len(set(canon_deadlines)) > 1:
            errors.append(f"bigquery/{canon_fn}: multiple distinct deadline literals "
                          f"{sorted(set(canon_deadlines))} in its state.cadence_watch definition — "
                          f"expected exactly one")
            canon_deadline_ok = False
    if deadline_ok and canon_deadline_ok and canon_fn is not None and canon_deadlines[0] != want_deadline:
        errors.append(f"cadence_watch deadline DRIFT (canonical file) — ops/cadence.yaml="
                      f"'{want_deadline}' vs bigquery/{canon_fn} (the highest-numbered file currently "
                      f"defining state.cadence_watch) TIME='{canon_deadlines[0]}'. Keep them in sync.")

    # ---- E. period_grace_days: cadence.yaml == bigquery/24_cadence_period_watch.sql ----
    want_grace = cadence_period_grace_yaml()
    have_grace = parse_period_grace_sql()
    if have_grace is not None:  # file present; if absent, this repo predates the feature — skip silently
        if want_grace is None:
            errors.append("ops/cadence.yaml: missing top-level 'period_grace_days' "
                          "(bigquery/24_cadence_period_watch.sql exists and needs a declared source of truth)")
        else:
            for cls in ("weekly_sun", "monthly_ftd", "quarterly_ftd", "annual_ftd"):
                y, s = want_grace.get(cls), have_grace.get(cls)
                if y is None:
                    errors.append(f"ops/cadence.yaml period_grace_days: missing '{cls}'")
                elif s is None:
                    errors.append(f"bigquery/24_cadence_period_watch.sql: could not parse a grace literal for '{cls}'")
                elif y != s:
                    errors.append(f"period_grace_days DRIFT for {cls} — ops/cadence.yaml={y} vs "
                                  f"bigquery/24_cadence_period_watch.sql={s}. Keep them in sync.")

    # ---- J. state.cadence_period_watch's `routines` CTE (24_*.sql) == period-class routines in
    # cadence.yaml (ARCH-3 Item 30b) — the GENERATED counterpart to check A, for the period-tier list. ----
    want_period_routines = {rid: r["monitor_class"] for rid, r in cad.items()
                             if r.get("monitor_class") in PERIOD_CLASSES}
    have_period_routines = parse_period_watch_routines_sql()
    if have_period_routines is not None:  # file present; absent = pre-feature checkout, skip silently
        if not have_period_routines:
            errors.append("could not parse any labelled STRUCT(... AS monitor_class) rows from "
                          "24_cadence_period_watch.sql's `routines` CTE")
        errors.extend(class_map_errors(
            want_period_routines, have_period_routines,
            missing_from="state.cadence_period_watch's routines CTE (24_cadence_period_watch.sql)",
            mismatch_label="period-watch monitor_class mismatch", mismatch_ref="24_cadence_period_watch.sql",
            extra_in="state.cadence_period_watch's routines CTE (24_*.sql)",
            extra_not_a="period-class routine in cadence.yaml"))

    # ---- K. catchup_safe: every cadence.yaml routine must declare the boolean, and bigquery/31/59's
    # hand-maintained UNNEST id lists must equal the corresponding {catchup_safe AND monitor_class in
    # <tier>} subset (ARCH-3 Item 30b — these two lists previously had ZERO drift protection). ----
    for rid, r in cad.items():
        if "catchup_safe" not in r:
            errors.append(f"{rid}: missing catchup_safe boolean in ops/cadence.yaml")
        elif not isinstance(r["catchup_safe"], bool):
            errors.append(f"{rid}: catchup_safe must be a boolean true/false (got {r['catchup_safe']!r})")

    errors.extend(catchup_list_errors(
        cad, CATCHUP_NOTIFY_SQL, "bigquery/31_catchup_notify.sql", "daily", DAILY_CLASSES))
    errors.extend(catchup_list_errors(
        cad, CATCHUP_AUTOFIRE_SQL, "bigquery/59_catchup_autofire.sql", "period", PERIOD_CLASSES))

    # ---- L. Claude_Task_Plan.md's ROUTINE INVENTORY table == cadence.yaml ids, and each row's
    # 'Cadence · Type' cell agrees with that routine's monitor_class (ARCH-3 Item 30b). ----
    have_inventory = parse_inventory_table(PLAN)
    if have_inventory is None:
        # 2026-07-29: unconditional hard error, not a skip. A prior version of this check tried to
        # tell "heading never introduced" (skip silently) apart from "heading reworded" (fail loud)
        # via a loose substring search — PROVEN DEFEATABLE the same day by a rewording that drops the
        # substring too (e.g. "# ROUTINE ROSTER & BIGQUERY RESPONSIBILITIES"), which made both
        # branches miss and let main() exit 0 silently, reproducing the exact bug the heuristic
        # existed to catch. The ROUTINE INVENTORY table is a mandatory section of Claude_Task_Plan.md
        # (itself not optional), so "the table can't be found" is a drift error in every case — there
        # is no legitimate skip case left to preserve.
        errors.append(
            f"Claude_Task_Plan.md: could not locate the exact heading '{INVENTORY_HEADING}' followed "
            f"by a parseable ROUTINE INVENTORY table — check L's drift guard cannot run. Either the "
            f"heading text was reworded (restore it exactly as shown above, or update "
            f"INVENTORY_HEADING in this script to match the new text), or the entire ROUTINE "
            f"INVENTORY section was deleted (restore it — the table is mandatory, so its absence is "
            f"itself a drift error, not a pre-feature-checkout case to skip).")
    else:  # heading present and table parsed — compare its rows against ops/cadence.yaml
        have_inventory_ids = {rid for rid, _cell in have_inventory}
        for rid in sorted(set(cad) - have_inventory_ids):
            errors.append(f"{rid}: in ops/cadence.yaml but missing a row in Claude_Task_Plan.md's "
                          f"ROUTINE INVENTORY table")
        for rid in sorted(have_inventory_ids - set(cad)):
            errors.append(f"{rid}: ROUTINE INVENTORY table row has no matching ops/cadence.yaml routine")
        for rid, cell in have_inventory:
            if rid not in cad:
                continue
            mc = cad[rid].get("monitor_class")
            token = cell.strip().split()[0] if cell.strip() else ""
            if rid in INVENTORY_FOOTNOTE_QUEUE_DRIVEN_IDS and token.rstrip("¹") == "Daily" and token.endswith("¹"):
                allowed = {"queue_driven"}
            else:
                allowed = INVENTORY_CADENCE_TOKEN_MAP.get(token)
            if allowed is None:
                errors.append(f"{rid}: ROUTINE INVENTORY 'Cadence · Type' cell first token '{token}' "
                              f"not recognized (Daily/Weekly/Monthly/Quarterly/Annual/Queue-driven)")
            elif mc not in allowed:
                errors.append(f"{rid}: ROUTINE INVENTORY cadence cell '{token}' implies monitor_class in "
                              f"{sorted(allowed)}, but ops/cadence.yaml has monitor_class='{mc}'")

    # ---- F. ops/triggers.json (if present) == the canonical generated map ----
    if os.path.exists(TRIGGERS_JSON):
        want_manifest = generate_triggers_manifest(head_by_id, cad)
        try:
            have_manifest = json.load(open(TRIGGERS_JSON, encoding="utf-8"))
        except (OSError, ValueError) as e:
            errors.append(f"ops/triggers.json: could not parse as JSON ({e})")
            have_manifest = None
        if have_manifest is not None and have_manifest != want_manifest:
            errors.append("ops/triggers.json is STALE — does not match the canonical map derived from "
                          "ops/cadence.yaml + Claude_Task_Plan.md headings. Regenerate with "
                          "`python scripts/print_routines.py --write` and commit the result "
                          "(it must be GENERATED, never hand-edited).")

    # ---- G. ops/trigger_ids.json (if present): unique trigger_ids, no entry for a routine no
    # longer in cadence.yaml (self-improvement audit, 2026-07-14 — this file had zero CI
    # validation despite being nearly identical in shape/purpose to ops/triggers.json). A cad
    # routine with NO entry yet is expected/transient (recorded once its live trigger is created)
    # and is a WARN, not a build failure. ----
    if os.path.exists(TRIGGER_IDS_JSON):
        try:
            trigger_ids_doc = json.load(open(TRIGGER_IDS_JSON, encoding="utf-8"))
        except (OSError, ValueError) as e:
            errors.append(f"ops/trigger_ids.json: could not parse as JSON ({e})")
            trigger_ids_doc = None
        if trigger_ids_doc is not None:
            have_ids = {k: v for k, v in trigger_ids_doc.items() if k != "_meta"}
            by_trigger = {}
            for rid, entry in have_ids.items():
                tid = (entry or {}).get("trigger_id")
                by_trigger.setdefault(tid, []).append(rid)
            for tid, rids in by_trigger.items():
                if tid and len(rids) > 1:
                    errors.append(f"ops/trigger_ids.json: trigger_id '{tid}' is shared by routines "
                                  f"{sorted(rids)} — duplicate/typo'd id would misdirect a live "
                                  f"RemoteTrigger call")
            stale = sorted(rid for rid in have_ids if rid not in cad)
            if stale:
                errors.append(f"ops/trigger_ids.json: entries for routine(s) no longer in "
                              f"ops/cadence.yaml: {stale} — remove the stale entry")
            missing = sorted(rid for rid in cad if rid not in have_ids)
            if missing:
                print(f"NOTE: ops/trigger_ids.json has no entry yet for {missing} (new routine — "
                      f"record its live trigger id once created via RemoteTrigger/Chrome; not a "
                      f"CI failure, per the file's own not-live-synced caveat).")

            # ---- I. expected_trigger: every routine WITH an ops/trigger_ids.json entry must carry a
            # well-formed `expected_trigger` in ops/cadence.yaml (trigger-config-drift audit, 2026-07-16,
            # ARCH-2/CC-5 merge). This is the structured, mechanically-diffable schedule Q4 step E and
            # OPS0 STEP 3 diff a live RemoteTrigger get() against, replacing the old free-text
            # WEB-UI TRIGGER AUDIT comment block as the enforced source of truth. A routine with NO
            # trigger_ids.json entry yet (OPS0, until its live trigger is created) is a NOTE only,
            # mirroring the NOTE just above — not a build failure. ----
            EXPECTED_TRIGGER_RECURRENCE = {"daily", "weekly", "custom_cron"}
            for rid in sorted(cad):
                et = cad[rid].get("expected_trigger")
                if rid not in have_ids:
                    if et is None:
                        print(f"NOTE: {rid} has no expected_trigger yet (no live trigger id recorded "
                              f"either — expected until ops/trigger_ids.json gets an entry for it).")
                    continue
                if et is None:
                    errors.append(f"{rid}: has an ops/trigger_ids.json entry but no 'expected_trigger' "
                                  f"in ops/cadence.yaml (structured schedule required for the "
                                  f"RemoteTrigger-diff self-heal sweep — Q4 step E / OPS0 STEP 3)")
                    continue
                rec = et.get("recurrence")
                if rec not in EXPECTED_TRIGGER_RECURRENCE:
                    errors.append(f"{rid}: expected_trigger.recurrence={rec!r} not in "
                                  f"{sorted(EXPECTED_TRIGGER_RECURRENCE)}")
                    continue
                if "enabled" not in et:
                    errors.append(f"{rid}: expected_trigger missing 'enabled'")
                if rec in ("daily", "weekly"):
                    tl = et.get("time_local")
                    if not (isinstance(tl, str) and HHMM.match(tl)):
                        errors.append(f"{rid}: expected_trigger.time_local must be a quoted \"HH:MM\" "
                                      f"string for recurrence={rec} (got {tl!r} — an unquoted HH:MM is "
                                      f"YAML base-60, same caveat as cadence_watch_deadline_local)")
                elif rec == "custom_cron":
                    cu = et.get("cron_utc")
                    if not (isinstance(cu, str) and cu.strip()):
                        errors.append(f"{rid}: expected_trigger.cron_utc must be a non-empty string "
                                      f"(TO_POPULATE bootstrap placeholder, or an observed cron once a "
                                      f"sweep has populated it) for recurrence=custom_cron")

    # ---- H. auto-merge-claude.yml's RUNBOOK §38 marker-write routine_re must accept every
    # cadence.yaml id (self-improvement audit, 2026-07-14) — this hand-typed alternation is a
    # second copy of the routine-id set already carried by ops/cadence.yaml, with no guard: a
    # routine added to cadence.yaml but not to this regex has its commits silently skipped by the
    # §38 marker-write self-heal, with no CI signal. Only checks the cadence-ids-subset-of-regex
    # direction (under-inclusive/silent-skip) — the regex being a superset is harmless. ----
    # The literal moved into the sourced helper on 2026-07-29. Look in BOTH locations and validate
    # EVERY copy found (not first-match-wins): if the allowlist is ever duplicated across the helper
    # and the workflow, a stale second copy must fail loudly rather than hide behind a complete one.
    # Read the module globals at call time so tests can monkeypatch either path.
    allowlist_paths = [p for p in (AUTO_MERGE_DECISION_SH, AUTO_MERGE_YML) if os.path.exists(p)]
    if allowlist_paths:
        found = [(p, AUTO_MERGE_ROUTINE_RE.search(read_text(p)))
                 for p in allowlist_paths]
        found = [(p, m) for p, m in found if m is not None]
        if not found:
            errors.append("could not find the RUNBOOK §38 marker-write routine allowlist literal in "
                          "scripts/auto_merge_decision.sh or .github/workflows/auto-merge-claude.yml "
                          "— its shape may have changed; update AUTO_MERGE_ROUTINE_RE / "
                          "AUTO_MERGE_DECISION_SH / AUTO_MERGE_YML in this script to match")
        for _p, m in found:
            _rel = os.path.relpath(_p, ROOT)
            routine_re_pat = re.compile(f"^(?:{m.group(1)})$")
            for rid in cad:
                if not routine_re_pat.fullmatch(rid):
                    errors.append(f"{rid}: in ops/cadence.yaml but NOT matched by {_rel}'s "
                                  f"routine_re — RUNBOOK §38 marker-write will silently skip this "
                                  f"routine's commits (add it to the routine_re alternation)")
    else:
        # Both candidate locations missing is not "nothing to check", it is check H having no signal
        # at all — the same silent-no-op shape as the substring-gate bug check M had (2026-08-08 audit
        # finding). Neither file existing at once is implausible today, but a future rename/move of
        # BOTH without updating this script must not read as a clean CI run.
        errors.append("could not find the RUNBOOK §38 marker-write routine allowlist source — neither "
                      f"{os.path.relpath(AUTO_MERGE_DECISION_SH, ROOT)} nor "
                      f"{os.path.relpath(AUTO_MERGE_YML, ROOT)} exists, so check H validated nothing; "
                      "restore one of these files or update AUTO_MERGE_DECISION_SH / AUTO_MERGE_YML "
                      "in this script to match their new location")

    # ---- M. EVENING-slot daily SAME-DAY guard copies carry the noon-threshold clause (H1). ----
    # Used to be gated on the "SAME-DAY DOUBLE-RUN GUARD" sentinel being present at all, on the theory
    # that this only ever skips a minimal test fixture / pre-feature checkout — but a bare substring
    # gate fails open on ANY loss of that heading (a rename, a rewrite that drops the sentinel word),
    # silently disarming the whole check with no CI signal, not just the fixture case it was written
    # for (2026-08-08 audit finding). The inner loop below already errors loudly, per routine, when
    # GUARD_QUERY_RE[rid] finds no match — there is no reason total absence of the sentinel should be
    # quieter than that. Run unconditionally: a plan with zero SAME-DAY DOUBLE-RUN GUARD text now fails
    # loudly (one error per EVENING_DAILY_GUARD_IDS routine) instead of passing vacuously. Test
    # fixtures that don't care about check M must now carry valid guard text too (see
    # tests/test_cadence_consistency.py's _write_check_fixture / _AR_ATT_PLAN).
    plan_txt = open(PLAN, encoding="utf-8").read()
    for rid in EVENING_DAILY_GUARD_IDS:
        matches = list(GUARD_QUERY_RE[rid].finditer(plan_txt))
        if not matches:
            errors.append(f"{rid}: could not find its SAME-DAY DOUBLE-RUN GUARD `ops.run_log` "
                          f"COUNT(*) query in Claude_Task_Plan.md — check M's H1 noon-threshold guard "
                          f"is DISARMED for this routine (did the guard query change shape?)")
            continue
        for m in matches:
            if not GUARD_NOON_CLAUSE_RE.search(m.group("after")):
                errors.append(
                    f"{rid}: SAME-DAY DOUBLE-RUN GUARD copy is MISSING the noon-threshold clause "
                    f"(H1) — an EVENING-slot daily routine (slot >= 16:00 MT) must count only "
                    f"completions in the real evening window: append "
                    f"`AND DATETIME(log_ts,'America/Denver') >= DATETIME(<today, America/Denver>, "
                    f"TIME '12:00:00')` to its `status='completed'` COUNT(*) query, so a post-midnight "
                    f"prior-day run mis-stamped onto today by bigquery/12's midnight-crossing grace "
                    f"cannot cancel the genuine evening run (see the shared Observability guard's "
                    f"CYCLE-AWARE VARIANT).")

    # ---- N. model of record: cadence.yaml routine_model == every mirror site ----
    model_errs, model_of_record = check_model_of_record()
    errors.extend(model_errs)

    # ---- O. state.stalled_runs' `cls` CTE routine list == ops/cadence.yaml's routine ids, BOTH
    # directions (see the comment above STALLED_RUNS_VIEW_DDL for the full WHY -- this is the same
    # class of gap that let OPS0/OPS1/OPS2 hang undetected for weeks until bigquery/148). ----
    cls_ids, cls_number, cls_fn, cls_ambiguous = parse_stalled_runs_cls_ids()
    if cls_ambiguous is not None:
        errors.append(
            f"AMBIGUOUS canonical file for state.stalled_runs — bigquery/{cls_number} is the "
            f"winning (highest) leading number, but {len(cls_ambiguous)} DIFFERENT files share it "
            f"and each defines `CREATE OR REPLACE VIEW state.stalled_runs`: "
            f"{', '.join('bigquery/' + fn for fn in cls_ambiguous)}. Check O's cls-list drift guard "
            f"cannot determine which is actually deployed — renumber one file so the leading number "
            f"is unique, or determine which definition is actually deployed and delete/renumber the "
            f"other.")
    elif cls_fn is None:
        errors.append("could not find any bigquery/*.sql file defining "
                      "`CREATE OR REPLACE VIEW state.stalled_runs` at all — check O's cls-list drift "
                      "guard cannot run")
    elif not cls_ids:
        errors.append(f"bigquery/{cls_fn}: could not parse any routine id out of state.stalled_runs' "
                      f"`cls` CTE UNNEST([...]) STRUCT list — check O's cls-list drift guard is "
                      f"DISARMED (regex rot? e.g. a reformat of the STRUCT(...) rows, or of the "
                      f"`cls AS (... UNNEST([...]) ...)` shape itself). Restore a parseable `cls` CTE.")
    else:
        cls_set, cad_set = set(cls_ids), set(cad)
        for rid in sorted(cad_set - cls_set):
            errors.append(f"{rid}: in ops/cadence.yaml but MISSING from bigquery/{cls_fn}'s "
                          f"state.stalled_runs `cls` CTE — this routine can NEVER be flagged "
                          f"routine_stalled no matter how long it hangs (the `JOIN cls c USING "
                          f"(routine)` INNER join drops it before the terminal-row anti-join or "
                          f"elapsed-hours threshold ever run — this is exactly the OPS0/OPS1/OPS2 "
                          f"gap bigquery/148 fixed). Add a STRUCT('{rid}', <min_stale_hours>) entry.")
        for rid in sorted(cls_set - cad_set):
            errors.append(f"{rid}: in bigquery/{cls_fn}'s state.stalled_runs `cls` CTE but not a "
                          f"routine id in ops/cadence.yaml — stale entry for a retired/renamed "
                          f"routine, remove it.")

    # ---- report ----
    if errors:
        print("CADENCE CONSISTENCY: FAIL\n")
        for e in errors:
            print(" - " + e)
        print("\nFix ops/cadence.yaml (monitor_class) / Claude_Task_Plan.md headings and the matching "
              "bigquery/12_cadence_monitor.sql + bigquery/15_routine_catalog.sql so all three agree, "
              "then re-run. (See ops/cadence.yaml header + scripts/print_routines.py.)")
        return 1

    extra = ""
    if have_grace is not None:
        extra += " period_grace_days matches 24_cadence_period_watch.sql."
    if os.path.exists(TRIGGERS_JSON):
        extra += " ops/triggers.json is current."
    if model_of_record:
        extra += f" routine_model {model_of_record} matches all mirror sites."
    if cls_fn is not None:
        extra += f" state.stalled_runs cls list (bigquery/{cls_fn}) matches all {len(cad)} routine ids."
    canon_note = (f" and bigquery/{canon_fn} (canonical)" if canon_fn is not None else "")
    print(f"CADENCE CONSISTENCY: OK — {len(cad)} routines; "
          f"{len(want_expected)} calendar-class match state.cadence_expected_today; "
          f"{len(have_catalog)} catalog entries match the plan headings; "
          f"cadence_watch deadline {want_deadline} matches 12_cadence_monitor.sql (superseded reference)"
          f"{canon_note}.{extra}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
