#!/usr/bin/env python3
"""Single-source the cadence: fail CI if the hand-kept SQL drifts from ops/cadence.yaml + the plan.

WHY THIS EXISTS. "What runs when" was hand-maintained in THREE places that had to stay in lockstep
with no automated guard:
  1. ops/cadence.yaml                          — the documented manifest (now carries monitor_class)
  2. state.cadence_expected_today (SQL)        — bigquery/12_cadence_monitor.sql, a hardcoded routine list
  3. ops.routine_catalog (SQL)                 — bigquery/15_routine_catalog.sql, a hardcoded instruction seed
plus the canonical routine headings in Claude_Task_Plan.md. A routine added / renamed / rescheduled in
one place but not the others drifted silently — exactly the RUNBOOK §22-class problem. This check makes
ops/cadence.yaml + Claude_Task_Plan.md the SOURCE OF TRUTH and verifies the two SQL files agree:

  A. state.cadence_expected_today's (routine -> schedule-class) set == cadence.yaml's
     (id -> monitor_class) for every routine whose monitor_class is calendar-predictable
     (i.e. != queue_driven; the AR routines are deliberately excluded from the calendar view).
  B. ops.routine_catalog's (routine -> canonical_instruction) == the instruction derived from each
     Claude_Task_Plan.md routine heading ("Read Claude_Task_Plan.md. Perform <heading>.").
  C. Every cadence.yaml routine id maps 1:1 to a Claude_Task_Plan.md heading and appears in the catalog
     (the scripts/print_routines.py cross-check, extended to the SQL layer).
  D. cadence.yaml's top-level `cadence_watch_deadline_local` == the TIME literal in the
     state.cadence_watch deadline guard (bigquery/12_cadence_monitor.sql). The deadline is otherwise a
     bare SQL constant with no source of truth, so a real cadence shift could silently leave it stale and
     re-open the pre-deadline false-positive window (RUNBOOK §1 step 3 / §20 follow-up).
  E. cadence.yaml's top-level `period_grace_days` == the OFFSET/day-count literals in
     state.cadence_period_watch (bigquery/24_cadence_period_watch.sql) — added 2026-07-03,
     self-improvement audit WO-1/B-6-obs, same discipline as check D.
  F. ops/triggers.json (if present) == the canonical {id, monitor_class, instruction} map derived from
     cadence.yaml + Claude_Task_Plan.md headings — GENERATED by `scripts/print_routines.py --write`,
     never hand-kept (self-improvement audit WO-2). If the file does not yet exist this check is
     skipped (it is an opt-in artifact, not required for every clone).
  J. state.cadence_period_watch's (routine -> monitor_class) STRUCT rows (bigquery/24_cadence_period_
     watch.sql `routines` CTE) == cadence.yaml's routines whose monitor_class is one of the four period
     classes (weekly_sun/monthly_ftd/quarterly_ftd/annual_ftd). The rows are GENERATED by
     `scripts/gen_routine_lists.py --write`; this check verifies the CONTENT still agrees (ARCH-3 Item
     30b, 2026-07-16 — this list previously had zero CI list-drift protection at all).
  K. bigquery/31_catchup_notify.sql's and bigquery/59_catchup_autofire.sql's hand-maintained
     catchup-safe UNNEST id lists == the {routine : catchup_safe AND monitor_class in <tier>} subset of
     cadence.yaml (31 = daily tier: daily_trading/daily_all; 59 = period tier: the four period
     classes). Also requires every cadence.yaml routine to declare an explicit `catchup_safe` boolean
     (missing key = error, mirroring the monitor_class presence check) — these two lists are a
     DECLARED capital-adjacency judgment, never derived from monitor_class (ARCH-3 Item 30b).
  L. The ROUTINE INVENTORY table in Claude_Task_Plan.md (the section between the "# ROUTINE INVENTORY
     & BIGQUERY RESPONSIBILITIES" heading and the next `---` divider) lists exactly the cadence.yaml
     routine ids, and each row's "Cadence · Type" cell agrees with that routine's monitor_class (ARCH-3
     Item 30b — this table previously had zero CI coverage).

This does NOT generate the bigquery/12/15/24 STRUCT rows by hand — `scripts/gen_routine_lists.py
--write` does that (checks A/B/J verify the generator's OUTPUT agrees with cadence.yaml; the CI step
`gen_routine_lists.py --check` verifies the committed files are byte-current with what --write would
produce). This script does NOT generate bigquery/31/59's catchup-safe lists or the plan's ROUTINE
INVENTORY table (those stay hand-authored, declared judgment calls) — it only CHECKS them (checks K/L),
so editing cadence.yaml or a plan heading and forgetting a dependent file fails the build with a
precise diff instead of surfacing weeks later as a false cadence/instruction_drift alert.

Usage:  python scripts/check_cadence_consistency.py        # exit 0 if consistent, 1 + diff if not
"""
import json
import os
import re
import sys

try:
    # this module's own reads now go through lib.textio.load_yaml() (2026-07-29 textio
    # adoption), so `yaml` is no longer referenced directly here, but the import stays for this
    # fail-fast ImportError guard (a clear "pip install pyyaml" message beats textio.py's own bare
    # ImportError traceback).
    import yaml  # noqa: F401
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    raise SystemExit(2) from None

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib.routine_manifest import (
    heading_to_id, parse_routine_headings, build_triggers_manifest, instruction_text, cadence_routines,
)
from lib.report import fail_or_ok
from lib.sql_files import numbered_sql_files, resolve_canonical, strip_sql_comments
from lib.textio import read_text, load_yaml
from lib.model_of_record import (
    # Check N's extraction (2026-08-31 code-quality pass, cadence#2) moved these out of this file;
    # imported by name (not `import lib.model_of_record as ...`) because
    # tests/test_cadence_consistency.py still reaches them directly as cc.MODEL_ID_RE /
    # cc.MODEL_ID_VALID / cc.MODEL_EXEMPT / cc._is_subtracted_non_assertion -- otherwise unused in
    # THIS file's own code, hence the noqa. See check N's old location (below) for the two wrapper
    # functions that keep cc.check_model_of_record()/cc.model_mirror_files() callable unchanged.
    MODEL_ID_RE, MODEL_ID_VALID, MODEL_EXEMPT, _is_subtracted_non_assertion,  # noqa: F401
    model_mirror_files as _model_of_record_mirror_files,
    check_model_of_record as _model_of_record_check,
)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLAN = os.path.join(ROOT, "Claude_Task_Plan.md")
OWNER_ACTIONS = os.path.join(ROOT, "OWNER_ACTIONS.md")
CADENCE = os.path.join(ROOT, "ops", "cadence.yaml")
BIGQUERY_DIR = os.path.join(ROOT, "bigquery")
# Directory scanned for the canonical state.stalled_runs definition (check O) -- a SEPARATE module
# constant from BIGQUERY_DIR (not merely an alias resolved at call time), even though in production it
# points at the exact same directory, so tests can monkeypatch check O's search directory in isolation
# from check D-extended's own BIGQUERY_DIR-based canonical-file scan for state.cadence_watch.
# BOTH ARE NOW PATCHED INDEPENDENTLY BY THE TESTS (cadence#0, 2026-08-31 code-quality pass). This
# comment used to end by noting that check D-extended's scan "already runs, unpatched, against the
# REAL bigquery/ directory in every existing fixture test", staying clean only because the live
# ops/cadence.yaml deadline literal happened to equal the fixtures' hardcoded "21:00". That was true
# and was the defect: ~55 fixture tests walked the real 205-file tree on every cc.main() call (~19.7s
# of that file's ~21s runtime) and were coupled to a live config value none of them was about, so
# changing cadence_watch_deadline_local would have broken all of them at once with a message naming
# neither the change nor the test's own subject. tests/test_cadence_consistency.py's
# _patch_fixture_paths() now redirects BIGQUERY_DIR at a tmp_path fixture too, writing a
# state.cadence_watch definition whose TIME literal is DERIVED from that fixture's own cadence.yaml.
# Keeping the two constants separate is still what lets either check's fixture be overridden without
# disturbing the other's -- which is why this is not collapsed back into a single constant.
STALLED_RUNS_BIGQUERY_DIR = BIGQUERY_DIR
CADENCE_SQL = os.path.join(ROOT, "bigquery", "12_cadence_monitor.sql")
CATALOG_SQL = os.path.join(ROOT, "bigquery", "15_routine_catalog.sql")
PERIOD_WATCH_SQL = os.path.join(ROOT, "bigquery", "24_cadence_period_watch.sql")
TRIGGERS_JSON = os.path.join(ROOT, "ops", "triggers.json")
TRIGGER_IDS_JSON = os.path.join(ROOT, "ops", "trigger_ids.json")
AUTO_MERGE_YML = os.path.join(ROOT, ".github", "workflows", "auto-merge-claude.yml")
# The §38 marker-write allowlist moved into the sourced helper on 2026-07-29 (extracted so
# tests/test_auto_merge_logic.sh covers the production implementation); the workflow is kept as a
# fallback location so this check still finds the literal if it is ever moved back inline.
AUTO_MERGE_DECISION_SH = os.path.join(ROOT, "scripts", "auto_merge_decision.sh")
CATCHUP_NOTIFY_SQL = os.path.join(ROOT, "bigquery", "31_catchup_notify.sql")
CATCHUP_AUTOFIRE_SQL = os.path.join(ROOT, "bigquery", "59_catchup_autofire.sql")

# ---- check N: MODEL OF RECORD mirrors -- EXTRACTED to scripts/lib/model_of_record.py (2026-08-31
# code-quality pass, cadence#2). This block used to live here in full (~400 self-contained lines / 25%
# of this file: MODEL_ID_CORE/MODEL_ID_RE/MODEL_ID_VALID/NOT_A_MODEL_PREFIXES/URL_RE/MODEL_EXEMPT,
# model_mirror_files(), _tooling_prefix_hides_version(), _is_subtracted_non_assertion(),
# check_model_of_record()) -- its only external dependencies were this module's own CADENCE/
# OWNER_ACTIONS/PLAN/CATALOG_SQL/ROOT path constants and lib.textio.load_yaml, and it had exactly one
# call site (main()'s check N, further below). See scripts/lib/model_of_record.py's own module
# docstring for the full WHY and history. The two thin wrappers below resolve THIS module's CADENCE/
# OWNER_ACTIONS/PLAN/CATALOG_SQL/ROOT globals at call time and pass them straight into the extracted
# module, so every `monkeypatch.setattr(cc, "CADENCE", ...)`-style fixture in
# tests/test_cadence_consistency.py keeps working unchanged.
def model_mirror_files():
    """Resolves this module's own CADENCE/OWNER_ACTIONS/PLAN/CATALOG_SQL globals at CALL time (not
    import time) and hands them to lib.model_of_record.model_mirror_files() -- so
    monkeypatch.setattr(cc, "CADENCE", ...) (etc., as the fixture-based tests do) still takes effect
    here, exactly as before check N's extraction to scripts/lib/model_of_record.py (2026-08-31
    code-quality pass, cadence#2)."""
    return _model_of_record_mirror_files(CADENCE, OWNER_ACTIONS, PLAN, CATALOG_SQL)


def check_model_of_record(doc=None):
    """Thin wrapper around lib.model_of_record.check_model_of_record(): resolves this module's own
    CADENCE/ROOT globals (and this module's own model_mirror_files() above) at CALL time and passes
    them through, so a test's monkeypatch.setattr(cc, "CADENCE", ...) keeps working unchanged after
    check N's extraction to scripts/lib/model_of_record.py (2026-08-31 code-quality pass, cadence#2).
    `doc` -- see the PERF NOTE above load_cadence()."""
    return _model_of_record_check(CADENCE, model_mirror_files(), ROOT, doc=doc)


# The RUNBOOK §38 marker-write routine-id allowlist: routine_re='^(D1|D2a|...)$'
AUTO_MERGE_ROUTINE_RE = re.compile(r"routine_re='\^\(([^)]+)\)\$'")

# state.cadence_period_watch's OFFSET-N literals, keyed by the column alias they compute.
PERIOD_GRACE_OFFSET = re.compile(r"OFFSET (\d+)\)\s*AS (month|quarter|year)_grace_day")
# The weekly grace is a calendar-day count from that week's Sunday (not an OFFSET into trading days).
PERIOD_GRACE_WEEKLY = re.compile(r"DATE_ADD\(n\.week_start,\s*INTERVAL (\d+) DAY\)")

# The four "period" monitor_class values (check J/K's period tier + the ROUTINE INVENTORY cadence-cell
# mapping, check L). daily_trading/daily_all are the "daily" tier (check K's bigquery/31 side).
PERIOD_CLASSES = {"weekly_sun", "monthly_ftd", "quarterly_ftd", "annual_ftd"}
# daily_sun_thu added 2026-08-08 (daily-tier Fri/Sat consolidation onto Sunday, ops/cadence.yaml):
# every Sunday-Thursday calendar day, NOT trading-day-gated -- see ops/cadence.yaml's DAILY-TIER
# FRI/SAT CONSOLIDATION header note. It is a DAILY_CLASSES member (not a PERIOD_CLASSES one) for
# every purpose DAILY_CLASSES feeds: check K's bigquery/31_catchup_notify.sql daily-tier UNNEST
# list, and the ALLOWED_CLASSES/CALENDAR_CLASSES vocabulary below.
DAILY_CLASSES = {"daily_trading", "daily_all", "daily_sun_thu"}

# ---- check M (H1, whole-system deep audit 2026-07-17): the EVENING-slot daily cohort's SAME-DAY
# DOUBLE-RUN GUARD copies must carry the noon-threshold clause. bigquery/12's midnight-crossing grace
# can stamp a post-midnight prior-day run onto today's run_date; without counting ONLY completions
# whose log_ts is in the real evening window, that mis-stamped early-AM completion cancels the genuine
# evening run. D1/D2/D2a/D3/SL3 each carry a per-routine guard copy in Claude_Task_Plan.md. D2a's own
# copy was added when its SAME-DAY DOUBLE-RUN GUARD scope was widened (2026-08-09) — it is
# `catchup_safe: false`, so the OPS0/OPS2 catch-up exclusions cover the refire vector, but NOT a manual
# re-run or a retry after partial failure, and D2a has double-completed in production on both
# 2026-07-03 (07:26 + 16:27 MT) and 2026-07-11 (15:36 + 16:26 MT). (An earlier version of this comment
# claimed D2a's double-run risk was "covered by D2's own guard" — that was wrong: D2's guard queries
# `routine='D2'` and structurally cannot see D2a; it protects D2 FROM D2a's chain-call, the opposite
# direction from D2a's own exposure.) Each copy's ops.run_log COUNT(*) query must therefore also filter
# `AND DATETIME(log_ts,'America/Denver') >= DATETIME(<today...>, TIME '12:00:00')`.
EVENING_DAILY_GUARD_IDS = ("D1", "D2", "D2a", "D3", "SL3")
# The guard query's stable prefix (D2's copy omits the ", America/Denver" qualifier on <today>, so the
# run_date token is matched loosely), capturing what follows status='completed' up to the closing `.
GUARD_QUERY_RE = {
    rid: re.compile(
        r"routine='%s' AND run_date=<today[^>]*> AND status='completed'(?P<after>[^`]{0,160})" % rid)
    for rid in EVENING_DAILY_GUARD_IDS
}
GUARD_NOON_CLAUSE_RE = re.compile(
    r"AND DATETIME\(log_ts,'America/Denver'\) >= DATETIME\(<today[^>]*>, TIME '12:00:00'\)")

# ---- check M membership cross-check (2026-08-09, mirroring check_cron_dst_safety.py's
# daily_sun_thu_coverage_errors() pattern — read that function first, it is the template this one
# follows). EVENING_DAILY_GUARD_IDS above is a hand-maintained tuple that check M's per-id loop
# iterates directly; nothing ever compared it back to ops/cadence.yaml, so a THIRD evening-slot routine
# (new, or re-timed into the evening) could silently never be looked at by check M at all — not merely
# fail a sub-check, but be entirely invisible to it, the same class of gap check_cron_dst_safety.py's
# daily_sun_thu split had before its own coverage guard.
#
# Candidate population is DERIVED FROM ops/cadence.yaml DATA — every routine whose
# `expected_trigger.time_local` is >= EVENING_SLOT_THRESHOLD ("16:00", the evening slot exposed to
# bigquery/12's midnight-crossing mis-stamp) — verified against the live file (2026-08-09): D1 16:00,
# D2a 16:40, D2 17:15, AR_att 18:00, AR_orc 18:35, D3 18:45, SL2 19:05, SL5 19:25, SL3 20:00, OPS2
# 22:15, OPS0 22:30 (11 routines). The two SIDES below stay HAND-maintained declared judgment calls,
# exactly like EVENING_WINDOW_ROUTINE_IDS/NON_WINDOW_DAILY_SUN_THU_IDS in check_cron_dst_safety.py —
# evening_slot_guard_membership_errors() only asserts every evening-slot routine has been CLASSIFIED by
# a human into one of the two sets, NEVER that the classification matches Claude_Task_Plan.md's actual
# guard text (that remains check M's own per-id GUARD_QUERY_RE/GUARD_NOON_CLAUSE_RE loop's job).
#
# CRITICAL — do NOT derive candidate membership from whether the guard TEXT is present in
# Claude_Task_Plan.md. Check M's whole job is to assert that text is present and correct; if membership
# were derived from the text, a routine missing its guard would simply drop OUT of the candidate set
# and this cross-check would pass vacuously — exactly the fail-open shape this file's checks keep
# getting bitten by (see check L's history and check M's own former substring gate, both above).
NOON_CLAUSE_EXEMPT_EVENING_IDS = {
    "AR_att": "queue-driven dispatch, not a calendar evening slot — explicitly out of the generalized "
              "SAME-DAY DOUBLE-RUN GUARD bullet's scope (drops out automatically as queue-driven).",
    "AR_orc": "queue-driven dispatch, not a calendar evening slot — same as AR_att.",
    "SL2": "queue-driven dispatch, not a calendar evening slot — same as AR_att.",
    "SL5": "queue-driven dispatch, not a calendar evening slot — same as AR_att.",
    "OPS0": "cadence dispatcher — deliberately fires AFTER the cadence_watch deadline (22:30 MT), not "
            "before it; its own SAME-DAY DOUBLE-RUN GUARD copy uses the plain (non-noon) predicate.",
    "OPS2": "catch-up executor — deliberately fires AFTER the cadence_watch deadline (22:15 MT), not "
            "before it; its own SAME-DAY DOUBLE-RUN GUARD copy uses the plain (non-noon) predicate, "
            "and OPS2 is never itself auto-caught-up.",
    "W5": "period-tier (weekly_sun), not daily -- the noon-clause exists to stop a midnight-crossing "
          "mis-stamped completion from falsely satisfying the IMMEDIATELY NEXT cycle's SAME-DAY "
          "GUARD (a daily routine's next occurrence is the very next calendar day, exactly where "
          "such a mis-stamp would land). W5's next occurrence is the FOLLOWING SUNDAY, 7 days "
          "later -- a stray Monday-dated completion from a delayed Sunday 23:00 fire crossing local "
          "midnight can never match next Sunday's `run_date=<that Sunday>` guard query, so the "
          "collision the noon-clause prevents is structurally impossible for a weekly-cadence "
          "routine. RETIMED 2026-08-17 from 04:00 to 23:00 MDT (ops/cadence.yaml) -- the first "
          "period-tier routine to cross the 16:00 evening-slot threshold.",
}
EVENING_SLOT_THRESHOLD = "16:00"


def evening_slot_guard_membership_errors(cad):
    """FAIL LOUD if ops/cadence.yaml's actual evening-slot (expected_trigger.time_local >=
    EVENING_SLOT_THRESHOLD) routine population diverges from the union of EVENING_DAILY_GUARD_IDS and
    NOON_CLAUSE_EXEMPT_EVENING_IDS — see the comment block above NOON_CLAUSE_EXEMPT_EVENING_IDS for the
    full rationale. Three hard-error cases, mirroring check_cron_dst_safety.py's daily_sun_thu_coverage_
    errors(): UNCLASSIFIED (evening-slot in cadence.yaml, in neither set — a new/re-timed routine
    nobody has decided about), STALE (named in one of the sets but no longer evening-slot in
    cadence.yaml), and OVERLAP (named in both — a self-contradiction)."""
    exempt_ids = set(NOON_CLAUSE_EXEMPT_EVENING_IDS)
    guard_ids = set(EVENING_DAILY_GUARD_IDS)
    errs = []

    overlap = guard_ids & exempt_ids
    if overlap:
        errs.append(
            f"scripts/check_cadence_consistency.py: {sorted(overlap)} appear in BOTH "
            f"EVENING_DAILY_GUARD_IDS and NOON_CLAUSE_EXEMPT_EVENING_IDS — pick one.")

    candidates = set()
    for rid, r in cad.items():
        tl = (r.get("expected_trigger") or {}).get("time_local")
        if isinstance(tl, str) and HHMM.match(tl) and tl >= EVENING_SLOT_THRESHOLD:
            candidates.add(rid)

    unclassified = candidates - (guard_ids | exempt_ids)
    if unclassified:
        errs.append(
            f"{sorted(unclassified)}: expected_trigger.time_local >= {EVENING_SLOT_THRESHOLD!r} in "
            f"ops/cadence.yaml (an evening-slot routine exposed to bigquery/12's midnight-crossing "
            f"mis-stamp) but named in NEITHER EVENING_DAILY_GUARD_IDS nor "
            f"NOON_CLAUSE_EXEMPT_EVENING_IDS in scripts/check_cadence_consistency.py. Add it to "
            f"EVENING_DAILY_GUARD_IDS (with a per-routine noon-clause SAME-DAY DOUBLE-RUN GUARD copy "
            f"in Claude_Task_Plan.md) or to NOON_CLAUSE_EXEMPT_EVENING_IDS with a one-line reason "
            f"before check M can validate it.")

    stale = (guard_ids | exempt_ids) - candidates
    if stale:
        errs.append(
            f"{sorted(stale)}: named in EVENING_DAILY_GUARD_IDS or NOON_CLAUSE_EXEMPT_EVENING_IDS in "
            f"scripts/check_cadence_consistency.py but no longer expected_trigger.time_local >= "
            f"{EVENING_SLOT_THRESHOLD!r} in ops/cadence.yaml (renamed, retired, or retimed) — remove "
            f"the stale entry.")
    return errs

# ---- check J: bigquery/24's post-normalization STRUCT rows are ALWAYS fully labelled (both
# `AS routine` and `AS monitor_class`) -- scripts/gen_routine_lists.py emits every row this way.
PERIOD_WATCH_ROUTINE_ROW = re.compile(
    r"STRUCT\('([^']+)'\s+AS routine,\s*'([^']+)'\s+AS monitor_class\)")

# ---- check K: bigquery/31/59's hand-maintained catchup-safe UNNEST([...]) AS routine id lists.
SQL_LINE_COMMENT = re.compile(r"--[^\n]*")
UNNEST_ROUTINE_BRACKET = re.compile(r"UNNEST\(\[(.*?)\]\)\s*AS routine", re.S)
QUOTED_ID = re.compile(r"'([A-Za-z0-9_]+)'")

# ---- check L: the ROUTINE INVENTORY table section of Claude_Task_Plan.md (scoped between its own
# heading and the NEXT '---' divider -- the strategy slice-map table elsewhere in the file also has
# `| **...** |`-shaped rows and must NOT be swept in).
INVENTORY_HEADING = "# ROUTINE INVENTORY & BIGQUERY RESPONSIBILITIES"
# 2026-07-29: an earlier version of this file tried to tell parse_inventory_table()'s two None cases
# apart -- "heading never introduced" (pre-feature checkout, skip silently) vs. "heading text changed"
# (regex rot, fail loud) -- via a loose substring search for "ROUTINE INVENTORY": substring present but
# exact heading missing => DISARMED (fail loud); substring absent too => assume pre-feature checkout and
# skip. PROVEN DEFEATABLE the same day: renaming the heading to something that also drops the substring
# (e.g. "# ROUTINE ROSTER & BIGQUERY RESPONSIBILITIES") makes BOTH branches miss, so main() exits 0
# silently -- reproducing the exact bug the heuristic was built to catch, for precisely the class of
# edit (a heading rewording) it existed to catch. The heuristic is deleted here, not re-tuned: a
# substring test can always be defeated by a rewording that drops the substring too, so no replacement
# substring closes that hole for good. Claude_Task_Plan.md is not optional and the ROUTINE INVENTORY
# table is a mandatory section of it, so "the table can't be found" was never actually a legitimate
# skip case either -- main() now treats BOTH None cases (heading reworded, section removed) as one
# unconditional hard error instead of trying to distinguish them.
# Columns: | ID | Routine | Cadence · Type | BigQuery reads | BigQuery writes | Cadence .md output |
# — group 1 is the id, group 2 is the 'Cadence · Type' cell (the 3rd column; the 2nd, the routine
# name, is skipped over).
INVENTORY_ROW = re.compile(r"^\|\s*\*\*([A-Za-z0-9_]+)\*\*\s*\|[^|]*\|([^|]*)\|", re.M)
# First token of the 'Cadence · Type' cell -> the set of monitor_class values it may legitimately mean.
INVENTORY_CADENCE_TOKEN_MAP = {
    "Daily": DAILY_CLASSES,
    # "Sun-Thu" added 2026-08-08 (daily-tier Fri/Sat consolidation onto Sunday) -- the distinct,
    # ASCII-only token for the 8 routines (D1/D2a/D2/D3/OPS0/OPS1/OPS2/SL3) that moved to
    # monitor_class: daily_sun_thu, so the ROUTINE INVENTORY table can tell a reader "runs
    # Sunday-Thursday only" apart from "Daily" (still every calendar/trading day) at a glance.
    # ASCII hyphen deliberately, not an en/em dash -- see ops/cadence.yaml's own MODEL_ID_CORE-
    # adjacent lesson on ASCII-only tokens elsewhere in this repo's checkers.
    "Sun-Thu": {"daily_sun_thu"},
    "Weekly": {"weekly_sun"},
    "Monthly": {"monthly_ftd"},
    "Quarterly": {"quarterly_ftd"},
    "Annual": {"annual_ftd"},
    "Queue-driven": {"queue_driven"},
}
# AR_att/AR_orc's cell reads 'Daily¹' (footnote ¹: queue-driven, fires daily but no-ops unless due).
INVENTORY_FOOTNOTE_QUEUE_DRIVEN_IDS = {"AR_att", "AR_orc"}

ALLOWED_CLASSES = {
    "daily_trading", "daily_all", "daily_sun_thu", "weekly_sun",
    "monthly_ftd", "quarterly_ftd", "annual_ftd", "queue_driven",
}
# monitor_class values the calendar view (state.cadence_expected_today) must encode.
CALENDAR_CLASSES = ALLOWED_CLASSES - {"queue_driven"}

# The state.cadence_watch deadline-guard literal: DATETIME(e.today, TIME 'HH:MM:SS'). Capture HH:MM.
SQL_DEADLINE = re.compile(r"DATETIME\(\s*e\.today\s*,\s*TIME\s*'(\d{2}:\d{2})(?::\d{2})?'\s*\)")
HHMM = re.compile(r"^\d{2}:\d{2}$")

# `CREATE [OR REPLACE] VIEW `stock-trading-498512.state.cadence_watch`` — matched against
# comment-stripped text (see find_canonical_cadence_watch_file() below) so a header/prose mention can
# never be mistaken for a live definition, same discipline check_superseded_markers.py's OBJECT_DDL and
# check_sq_version_registry.py's PROC_DDL already use for this exact class of false-positive.
CADENCE_WATCH_VIEW_DDL = re.compile(
    r"CREATE\s+(?:OR\s+REPLACE\s+)?VIEW\s+`stock-trading-498512\.state\.cadence_watch`",
    re.IGNORECASE,
)

# ---- check O (2026-08-08 audit follow-up to bigquery/148): state.stalled_runs is the ONLY thing that
# ever raises the `routine_stalled` alert -- a routine that logged 'started' but never a terminal row.
# Its hand-maintained `cls` CTE (an UNNEST([STRUCT(...), ...]) id -> min_stale_hours table) is joined
# with `JOIN cls c USING (routine)`, an INNER join, so a routine id absent from that list is dropped
# BEFORE the terminal-row anti-join or the elapsed-hours threshold are ever evaluated: it can hang
# forever and never be flagged. Not hypothetical -- `cls` was last edited 2026-07-10; OPS0/OPS1/OPS2
# were added to ops/cadence.yaml on 2026-07-15/07-19/07-27 with no matching `cls` edit, so all three
# (having already logged 16 'started' rows) were invisible to stall detection until bigquery/148 fixed
# it on 2026-08-08. Nothing ever compared the two lists, so nothing caught the drift -- this check is
# that comparison, in BOTH directions: a routine in cadence.yaml but missing from `cls` can never be
# flagged (the exact OPS0/OPS1/OPS2 gap); an id in `cls` but not in cadence.yaml is a stale entry for a
# retired/renamed routine.
#
# Resolved DYNAMICALLY against whichever bigquery/*.sql file currently defines `CREATE OR REPLACE VIEW
# state.stalled_runs` (never hardcoded to bigquery/148 -- the view has already moved once, 18 -> 148,
# and hardcoding the file here would itself be exactly the class of rot this check exists to prevent).
# Reuses the same numbered_sql_files()/resolve_canonical() machinery and ambiguous-winner contract (D6,
# 2026-08-06) that find_canonical_cadence_watch_file() above already established for state.cadence_
# watch, applied to a second, independently-superseded view -- see STALLED_RUNS_BIGQUERY_DIR's own
# comment (near BIGQUERY_DIR) for why this is a separate directory constant rather than a reuse of
# BIGQUERY_DIR itself.
# Matched against comment-stripped text, same discipline as CADENCE_WATCH_VIEW_DDL above.
STALLED_RUNS_VIEW_DDL = re.compile(
    r"CREATE\s+(?:OR\s+REPLACE\s+)?VIEW\s+`stock-trading-498512\.state\.stalled_runs`",
    re.IGNORECASE,
)
# Scoped to the `cls` CTE's own UNNEST([...]) bracket -- not a blind whole-file STRUCT( scan -- so a
# STRUCT(...) belonging to a LATER, unrelated statement in the same multi-statement file (bigquery/148
# defines several objects) can never leak in. The non-greedy `.*?` stops at the FIRST `])`, which is
# exactly the array's own close (the STRUCT(...) entries inside contain no `[`/`]` of their own).
# Comments are stripped by the CALLER (parse_stalled_runs_cls_ids, via lib.sql_files.strip_sql_
# comments) before this ever runs, so a commented-out or illustrative STRUCT('X', 6) in prose (e.g.
# this view's own header, which narrates past `cls` entries by name) can never be read as a live entry.
CLS_CTE_UNNEST_RE = re.compile(
    r"\bcls\s+AS\s*\(\s*SELECT\s*\*\s*FROM\s*UNNEST\(\s*\[(.*?)\]\s*\)", re.S)
# Handles BOTH spellings actually present in the real body: the CTE's first entry is labelled
# (STRUCT('D1' AS routine, 6 AS min_stale_hours)) and every later one is positional (STRUCT('D2a', 6)).
CLS_ENTRY_RE = re.compile(r"STRUCT\('([A-Za-z0-9_]+)'(?:\s+AS\s+routine)?\s*,")


def plan_headings():
    """Ordered routine section headings from Claude_Task_Plan.md (shared parser)."""
    return parse_routine_headings(PLAN)


# PERF NOTE, EVERY FUNCTION BELOW THAT TAKES AN OPTIONAL `doc` PARAMETER (2026-08-31 code-quality
# pass, cadence#3): load_cadence(), cadence_duplicate_ids(), cadence_deadline_yaml(),
# cadence_period_grace_yaml() and check_model_of_record() each used to call `load_yaml(CADENCE)`
# independently, and main() calls all five -- so the same ~1150-line ops/cadence.yaml document was
# parsed from scratch 5 times per run (measured: ~70-150ms per parse, PyYAML's pure-Python
# SafeLoader since `yaml.safe_load` never opts into the available CSafeLoader; ~350-750ms total
# across the 5 calls). Each now accepts an optional `doc`: main() parses CADENCE exactly once and
# threads that same parsed document into every one of them. Every direct/standalone call (the whole
# test suite calls these with zero args throughout) is unaffected -- omitting `doc` re-parses CADENCE
# from disk right here, exactly as before this pass.
def load_cadence(doc=None):
    if doc is None:
        doc = load_yaml(CADENCE)
    return {r["id"]: r for r in cadence_routines(doc)}


def cadence_duplicate_ids(doc=None):
    """[id, ...] (sorted, deduped) for any routine id appearing more than once in ops/cadence.yaml's
    routines list. load_cadence()'s dict comprehension above silently keeps only the LAST such entry
    (valid YAML, no parse error -- a duplicate `id:` across list items, not a duplicate mapping key),
    so every downstream check would validate against whichever duplicate happened to be listed last
    with zero signal. This walks the raw list first so a duplicate id fails loud instead, mirroring
    the duplicate Claude_Task_Plan.md heading check main() already does for `head_by_id` below.
    `doc` -- see the PERF NOTE above load_cadence()."""
    if doc is None:
        doc = load_yaml(CADENCE)
    ids = [r["id"] for r in cadence_routines(doc)]
    return sorted({i for i in ids if ids.count(i) > 1})


def parse_expected_sql():
    """{routine: schedule_class} from the STRUCT(... AS routine, ... AS schedule) list in 12_*.sql."""
    txt = read_text(CADENCE_SQL)
    pat = re.compile(r"STRUCT\('([^']+)'\s+AS routine,\s*'([^']+)'\s+AS schedule\)")
    return dict(pat.findall(txt))


def parse_catalog_sql():
    """{routine: canonical_instruction} from 15_*.sql (handles the first AS-labelled row + shorthand rows).

    The instruction literal may contain BigQuery-escaped single quotes (''), emitted by
    scripts/gen_routine_lists.py gen_15_region (_sql_str) when a routine heading contains an
    apostrophe. Match those doubled quotes and un-escape '' -> ' so the parsed value equals check B's
    want_catalog (derived from the RAW heading text). This is the paired half of gen_15_region's
    escaping -- the two MUST stay in lockstep. Byte-identical on a tree with no apostrophe headings."""
    txt = read_text(CATALOG_SQL)
    pat = re.compile(
        r"STRUCT\('([^']+)'(?:\s+AS routine)?,\s*'(Read Claude_Task_Plan\.md\. Perform (?:[^']|'')*)'")
    return {rid: instr.replace("''", "'") for rid, instr in pat.findall(txt)}


def parse_deadline_sql():
    """['HH:MM', ...] from the DATETIME(e.today, TIME 'HH:MM:SS') deadline guard in 12_*.sql (state.cadence_watch)."""
    return SQL_DEADLINE.findall(read_text(CADENCE_SQL))


# PERF NOTE, THE FOUR FUNCTIONS BELOW (2026-08-31 code-quality pass, cadence#1): find_canonical_
# cadence_watch_file() and find_canonical_stalled_runs_file() each used to independently walk +
# strip_sql_comments() EVERY bigquery/*.sql file (already 205 and growing), even though BIGQUERY_DIR
# and STALLED_RUNS_BIGQUERY_DIR point at the SAME directory in production (see STALLED_RUNS_
# BIGQUERY_DIR's own comment near BIGQUERY_DIR) -- two full walks of one tree. Their matching
# parse_canonical_deadline_sql()/parse_stalled_runs_cls_ids() then each threw that work away and
# re-read + re-stripped the WINNING file a second time. Measured: find_canonical_cadence_watch_file()
# alone cost ~359ms; parse_canonical_deadline_sql() (which calls it, then redoes the winner) cost
# ~677ms; the check-O equivalent cost ~617ms -- roughly 1.3s of the script's ~2.26s total runtime came
# from re-walking/re-reading this one tree. All four now accept an optional `scan` -- a pre-computed
# _scan_bigquery_dir() result -- so main() can build ONE shared scan per run (see _scan_bigquery_dir's
# own docstring) and thread it through every one of them, instead of each function doing its own walk
# and its own extra re-read of the winner. Every direct/standalone call (as most of the test suite
# makes) omits `scan` and gets a fresh walk right here, exactly as before this pass.
def _scan_bigquery_dir(bigquery_dir):
    """[(number, path, stripped_text), ...] for every bigquery/NN_*.sql file in `bigquery_dir`, read
    and comment-stripped exactly once -- the shared walk find_canonical_cadence_watch_file() and
    find_canonical_stalled_runs_file() below both need. This is a plain function, not a persisted
    cache: it re-walks the directory on every call, so calling it fresh at the top of main() (or
    letting a callee do so when no `scan` is passed) can never see stale content from an earlier call
    in the same process -- the correctness property tests that monkeypatch BIGQUERY_DIR/
    STALLED_RUNS_BIGQUERY_DIR between calls rely on."""
    out = []
    for number, path in numbered_sql_files(bigquery_dir):
        if os.path.isdir(path):
            continue
        out.append((number, path, strip_sql_comments(read_text(path))))
    return out


def find_canonical_cadence_watch_file(scan=None):
    """(number, filename, ambiguous_files) for the highest-numbered bigquery/*.sql file that defines
    `CREATE OR REPLACE VIEW state.cadence_watch` — the object has been redefined across several
    superseding files (12 -> 48 -> 113 -> 129 -> 142, and counting), and the highest-numbered occurrence
    is the one actually deployed live. Resolution goes through scripts/lib/sql_files.py's shared
    resolve_canonical() (order-independent max() over parsed file numbers, same construction
    check_superseded_markers.py's violations() and check_sq_version_registry.py's resolve_winners()
    already use for this exact "which file wins" question — see those scripts' module docstrings for
    why iteration order does not matter here).

    ambiguous_files is None in the normal case. bigquery/*.sql's NN_ leading number is NOT guaranteed
    unique (two files already share 114 in this repo today — see resolve_canonical()'s own docstring);
    if a FUTURE file at a duplicated number also defined `state.cadence_watch`, a bare max() could no
    longer tell the two apart and would silently validate whichever sorted first. When that happens,
    `filename` is None and `ambiguous_files` is the sorted list of every colliding filename — the
    caller MUST treat that as a hard error, never pick one on its own (D6, 2026-08-06 adversarial
    audit). Dormant on the real tree today: verified neither bigquery/114 file defines this view.

    `scan` -- see the PERF NOTE above _scan_bigquery_dir(); a fresh _scan_bigquery_dir(BIGQUERY_DIR)
    walk is done here when omitted.

    Returns (None, None, None) if no occurrence is found at all (should never happen on a real
    checkout — CADENCE_SQL itself always defines one)."""
    files = scan if scan is not None else _scan_bigquery_dir(BIGQUERY_DIR)
    occurrences = []
    for number, path, text in files:
        if CADENCE_WATCH_VIEW_DDL.search(text):
            occurrences.append((number, os.path.basename(path)))
    if not occurrences:
        return None, None, None
    winner_number, winner_files = resolve_canonical(occurrences)
    if len(winner_files) > 1:
        return winner_number, None, winner_files
    return winner_number, winner_files[0], None


def parse_canonical_deadline_sql(scan=None):
    """(['HH:MM', ...], number, filename, ambiguous_files) — the state.cadence_watch deadline-guard
    literal(s) parsed from the CANONICAL (highest-numbered) bigquery/*.sql file defining that view, NOT
    the fixed bigquery/12_cadence_monitor.sql parse_deadline_sql() above is pinned to (that original
    file is itself long superseded — 48 -> 113 -> 129 -> 142 and counting — so a deadline change landed
    only in a superseding file previously had NO consistency guard tying it back to ops/cadence.yaml at
    all, the same registry-vs-body split class check_sq_version_registry.py exists to catch for a
    heartbeat literal, applied here to this view instead).

    Comments are stripped first (scripts/lib/sql_files.strip_sql_comments) before SQL_DEADLINE runs, so
    a header/prose mention of a TIME literal — e.g. a file's own header narrating a before/after deadline
    change in prose — can never be mistaken for the live guard clause. This differs from the plain
    parse_deadline_sql() above, which does not strip comments; that has been harmless in practice only
    because bigquery/12's header has never happened to contain a matching digit-literal false positive.

    ambiguous_files is None in the normal case; see find_canonical_cadence_watch_file()'s own docstring
    (D6, 2026-08-06) — when it is NOT None, `fn` is None too and the caller must report the ambiguity
    rather than parse a (nonexistent, unpickable) single winning file.

    `scan` -- the SAME _scan_bigquery_dir(BIGQUERY_DIR) result passed to find_canonical_cadence_watch_
    file(); reusing it here lets the winning file's already-comment-stripped text be pulled straight
    out of the scan instead of being re-read + re-stripped a second time (see the PERF NOTE above
    _scan_bigquery_dir()). Omitted -> a fresh walk, exactly as before this pass.
    Returns ([], None, None, None) if no canonical file/definition could be found at all."""
    files = scan if scan is not None else _scan_bigquery_dir(BIGQUERY_DIR)
    number, fn, ambiguous_files = find_canonical_cadence_watch_file(files)
    if ambiguous_files is not None:
        return [], number, None, ambiguous_files
    if fn is None:
        return [], number, fn, None
    text = next(t for _n, p, t in files if os.path.basename(p) == fn)
    return SQL_DEADLINE.findall(text), number, fn, None


def find_canonical_stalled_runs_file(scan=None):
    """(number, filename, ambiguous_files) for the highest-numbered bigquery/*.sql file that defines
    `CREATE OR REPLACE VIEW state.stalled_runs` (check O) -- the object has been redefined once already
    (18 -> 148, and counting; bigquery/148's own header says "supersedes bigquery/18"). Mirrors
    find_canonical_cadence_watch_file() above exactly, including its ambiguous-winner contract (D6,
    2026-08-06): `ambiguous_files` is None in the normal case; when it is NOT None, `filename` is None
    too and the caller must report every colliding filename rather than pick one. Scans
    STALLED_RUNS_BIGQUERY_DIR, not BIGQUERY_DIR directly -- see that constant's own comment for why the
    two are kept separate.

    `scan` -- see the PERF NOTE above _scan_bigquery_dir(); a fresh _scan_bigquery_dir(STALLED_RUNS_
    BIGQUERY_DIR) walk is done here when omitted.

    Returns (None, None, None) if no occurrence is found at all (should never happen on a real
    checkout)."""
    files = scan if scan is not None else _scan_bigquery_dir(STALLED_RUNS_BIGQUERY_DIR)
    occurrences = []
    for number, path, text in files:
        if STALLED_RUNS_VIEW_DDL.search(text):
            occurrences.append((number, os.path.basename(path)))
    if not occurrences:
        return None, None, None
    winner_number, winner_files = resolve_canonical(occurrences)
    if len(winner_files) > 1:
        return winner_number, None, winner_files
    return winner_number, winner_files[0], None


def parse_stalled_runs_cls_ids(scan=None):
    """([routine_id, ...], number, filename, ambiguous_files) — the routine ids inside the `cls` CTE's
    UNNEST([...]) STRUCT list of the CANONICAL (highest-numbered) bigquery/*.sql file currently
    defining state.stalled_runs (check O). Comments are stripped first (lib.sql_files.strip_sql_
    comments) so a commented-out or illustrative STRUCT('X', 6) can never be read as a live entry, and
    the parse is scoped to the `cls` CTE's own UNNEST bracket (CLS_CTE_UNNEST_RE) rather than a blind
    whole-file STRUCT( scan, so a STRUCT(...) belonging to a later, unrelated statement in the same
    file can never leak in.

    `scan` -- the SAME _scan_bigquery_dir(STALLED_RUNS_BIGQUERY_DIR) result passed to find_canonical_
    stalled_runs_file(); reusing it avoids a third re-read/re-strip of the winning file (see the PERF
    NOTE above _scan_bigquery_dir()). Omitted -> a fresh walk, exactly as before this pass.

    Returns ([], number, filename, None) — an EMPTY list, never None — if the file was found but the
    `cls` CTE/UNNEST bracket could not be parsed (regex rot): main() must treat that as a hard error,
    never a silent skip (a checker that quietly validates nothing is the exact failure class this repo
    keeps getting bitten by). ambiguous_files mirrors find_canonical_stalled_runs_file()'s contract:
    non-None means the file itself could not be uniquely resolved, in which case ids is always []."""
    files = scan if scan is not None else _scan_bigquery_dir(STALLED_RUNS_BIGQUERY_DIR)
    number, fn, ambiguous_files = find_canonical_stalled_runs_file(files)
    if ambiguous_files is not None:
        return [], number, None, ambiguous_files
    if fn is None:
        return [], number, fn, None
    text = next(t for _n, p, t in files if os.path.basename(p) == fn)
    m = CLS_CTE_UNNEST_RE.search(text)
    if m is None:
        return [], number, fn, None
    return CLS_ENTRY_RE.findall(m.group(1)), number, fn, None


def cadence_deadline_yaml(doc=None):
    """Top-level cadence_watch_deadline_local from ops/cadence.yaml (raw value, or None). `doc` --
    see the PERF NOTE above load_cadence()."""
    if doc is None:
        doc = load_yaml(CADENCE)
    return doc.get("cadence_watch_deadline_local")


def cadence_period_grace_yaml(doc=None):
    """Top-level period_grace_days from ops/cadence.yaml (dict, or None). `doc` -- see the PERF NOTE
    above load_cadence()."""
    if doc is None:
        doc = load_yaml(CADENCE)
    return doc.get("period_grace_days")


def parse_period_grace_sql():
    """{monitor_class: grace_days} from bigquery/24_cadence_period_watch.sql.

    month/quarter/year are OFFSET N (0-indexed -> the (N+1)th trading day); weekly is a plain
    calendar-day count already expressed the same way period_grace_days.weekly_sun is (1 = Monday).
    Returns None if the file is absent (pre-2026-07-03 checkout) so the caller can skip check E.
    """
    if not os.path.exists(PERIOD_WATCH_SQL):
        return None
    txt = read_text(PERIOD_WATCH_SQL)
    out = {}
    for offset, which in PERIOD_GRACE_OFFSET.findall(txt):
        cls = {"month": "monthly_ftd", "quarter": "quarterly_ftd", "year": "annual_ftd"}[which]
        out[cls] = int(offset) + 1
    m = PERIOD_GRACE_WEEKLY.search(txt)
    if m:
        out["weekly_sun"] = int(m.group(1))
    return out


def parse_period_watch_routines_sql():
    """{routine: monitor_class} from bigquery/24_cadence_period_watch.sql's `routines` CTE
    (check J) — post-normalization (scripts/gen_routine_lists.py --write) every row is fully
    labelled `STRUCT('<id>' AS routine, '<class>' AS monitor_class)`. Returns None if the file is
    absent (pre-feature checkout) so the caller can skip check J, same convention as check E's
    parse_period_grace_sql."""
    if not os.path.exists(PERIOD_WATCH_SQL):
        return None
    txt = read_text(PERIOD_WATCH_SQL)
    return dict(PERIOD_WATCH_ROUTINE_ROW.findall(txt))


def parse_unnest_routine_ids(path):
    """Ids inside a `... UNNEST([ ... ]) AS routine` bracket (check K), `--` line comments stripped
    FIRST so an inline comment naming an id (e.g. "-- SL4 (rev ...)") can never be mistaken for a
    quoted list entry. Returns None if `path` does not exist OR if no such bracket is found. main()
    DISTINGUISHES the two by os.path.exists: a file that is ABSENT skips check K silently (pre-
    feature checkout), but a file that is PRESENT-but-unparseable FAILS check K loudly — otherwise a
    reformat that breaks the regex (`AS  routine`, `UNNEST(ARRAY[...]`) would silently disarm the
    only drift guard bigquery/31 and 59 have (2026-07-17 audit — the same regex-rot vacuous-pass
    class checks A/D/E/J/L already fail loud on by returning an empty container, not None)."""
    if not os.path.exists(path):
        return None
    txt = SQL_LINE_COMMENT.sub("", read_text(path))
    m = UNNEST_ROUTINE_BRACKET.search(txt)
    if m is None:
        return None
    return QUOTED_ID.findall(m.group(1))


def parse_inventory_table(plan_path):
    """[(id, cadence_type_cell), ...] rows from ONLY the ROUTINE INVENTORY section of the plan —
    scoped between the "# ROUTINE INVENTORY & BIGQUERY RESPONSIBILITIES" heading and the NEXT `---`
    divider, so the strategy slice-map table elsewhere in the file (which also has `| **...** |`-
    shaped rows, e.g. `| **AR_attacker** |`) can never leak in (check L). Returns None if the exact
    heading text is not found (reworded, or the whole section removed) — main() treats that as a
    single unconditional hard error rather than trying to tell the two cases apart: the ROUTINE
    INVENTORY table is a mandatory section of Claude_Task_Plan.md (which is itself not optional), so
    there is no legitimate case where its absence should be a silent skip (2026-07-29 — replaced a
    substring-based disambiguation that a heading rewording could defeat, see the comment above
    INVENTORY_HEADING)."""
    txt = read_text(plan_path)
    start = txt.find(INVENTORY_HEADING)
    if start == -1:
        return None
    rest = txt[start + len(INVENTORY_HEADING):]
    end = rest.find("\n---")
    section = rest if end == -1 else rest[:end]
    return INVENTORY_ROW.findall(section)


def generate_triggers_manifest(head_by_id, cad):
    """The canonical {id: {monitor_class, instruction}} map — same shape print_routines.py --write
    emits to ops/triggers.json. Delegates to the shared implementation (scripts/lib/routine_manifest.py)
    so CI verifies the committed file against the SAME code path print_routines.py --write uses,
    not an independently-maintained copy of it."""
    return build_triggers_manifest(list(head_by_id.values()), cad)


def check_depends_on(cad):
    """Error strings for any depends_on entry that is not a known routine id in cad (a dangling/typo'd
    dependency -- it feeds the FATAL ops.sp_assert_deps gate, so a silent typo here would abort a live
    routine at runtime instead of failing this offline check)."""
    errors = []
    for rid, r in cad.items():
        for dep in (r.get("depends_on") or []):
            if dep not in cad:
                errors.append(f"{rid}: depends_on '{dep}' is not a routine id in ops/cadence.yaml "
                              f"(dangling/typo'd dependency — it feeds the FATAL sp_assert_deps gate)")
    return errors


def catchup_list_errors(cad, path, filename, tier_word, classes):
    """Check K for ONE of bigquery/31/59's hand-maintained catchup-safe `UNNEST([...]) AS routine`
    lists: it must equal cadence.yaml's {catchup_safe AND monitor_class in <classes>} subset.

    An ABSENT file is skipped silently (pre-feature checkout); a PRESENT-but-unparseable file FAILS
    loudly (DISARMED) so a benign SQL reformat can never silently disarm the guard. The daily
    (bigquery/31) and period (bigquery/59) call sites differ only in (path, filename, tier_word,
    classes), so this shared helper keeps their two error strings — the observable contract — from
    ever drifting apart with a one-sided edit. Returns a list of error strings (possibly empty)."""
    want = {rid for rid, r in cad.items()
            if r.get("catchup_safe") is True and r.get("monitor_class") in classes}
    have = parse_unnest_routine_ids(path)
    if have is None and os.path.exists(path):
        return [
            f"{filename} exists but no `UNNEST([...]) AS routine` bracket could be "
            f"parsed — check K's catchup-safe {tier_word} drift guard is DISARMED (regex rot? e.g. a "
            f"reformat to `AS  routine` or `UNNEST(ARRAY[...]`). Restore a parseable bracket."]
    if have is not None:
        have_set = set(have)
        if have_set != want:
            return [
                f"{filename} catchup-safe {tier_word} UNNEST list DRIFT — "
                f"file has {sorted(have_set)}, cadence.yaml-derived (catchup_safe AND {tier_word} tier) "
                f"wants {sorted(want)}"]
    return []


def class_map_errors(want, have, *, missing_from, mismatch_label, mismatch_ref, extra_in, extra_not_a):
    """Shared want/have `{id: class}` MISSING / mismatch / extra comparison used by check A
    (state.cadence_expected_today vs 12_cadence_monitor.sql) and check J (state.cadence_period_watch's
    routines CTE vs 24_cadence_period_watch.sql) — both independently re-derived this exact
    three-branch loop, differing only in message wording (2026-07-29 dedup).

    Every message fragment is a caller-supplied literal rather than something templated from a single
    filename: the two call sites' existing wording is not even internally consistent with itself
    (check A's own "extra" message says "12_*.sql" while its "missing"/"mismatch" messages say
    "12_cadence_monitor.sql") and these messages are load-bearing — CI and a BigQuery bridge parse
    them — so preserving them byte-for-byte matters more than a cleaner single-filename template."""
    errors = []
    for rid, cls in want.items():
        if rid not in have:
            errors.append(f"{rid}: monitor_class={cls} in cadence.yaml but MISSING from {missing_from}")
        elif have[rid] != cls:
            errors.append(f"{rid}: {mismatch_label} — cadence.yaml='{cls}' vs {mismatch_ref}='{have[rid]}'")
    for rid in have:
        if rid not in want:
            errors.append(f"{rid}: in {extra_in} but not a {extra_not_a}")
    return errors


# ---- check Q (2026-08-31): D3's QUEUE HYGIENE "OWNER-ELIGIBLE-DAY BRANCH" restates each queue-driven
# owner's SCHEDULED local fire time, and its suppress/raise decision turns on comparing those times to
# the moment D3 runs (clause (b)). Those minutes are a MIRROR of ops/cadence.yaml's
# expected_trigger.time_local, and they have drifted before -- AR_orc moved 18:20 -> 18:35 on
# 2026-08-04 (see that entry's own comment in ops/cadence.yaml). A stale restatement here does not
# fail loudly; it silently flips a suppress into a raise (or worse, a raise into a suppress) for the
# fleet's ONLY dead-trigger detector on AR_att/AR_orc/SL2/SL5. So the mirror is machine-checked.
#
# It also asserts the branch's OTHER load-bearing premise -- that all four owners fire Sun-Thu -- by
# reading each one's cron day-of-week field rather than trusting the prose. UTC Mon-Fri (1,2,3,4,5) IS
# Denver Sun-Thu for these evening slots.
QUEUE_OWNER_SLOT_ANCHOR = "CLAUSE (b) IS THE ENTIRE FIX"
# Presence of the raise itself is what puts this file in scope for check Q (see the scope note
# in queue_owner_slot_mirror_errors) -- it is the thing the slot table exists to decide.
QUEUE_OWNER_SLOT_SCOPE = "queue_item_stale"
QUEUE_OWNER_SLOT_PAIR = re.compile(r"\b(AR_att|AR_orc|D3|SL2|SL5)\s+(\d{1,2}:\d{2})\b")
QUEUE_DRIVEN_OWNERS = ("AR_att", "AR_orc", "SL2", "SL5")


def queue_owner_slot_mirror_errors(cad):
    """D3's OWNER-ELIGIBLE-DAY BRANCH fire-time table matches ops/cadence.yaml, and the four
    queue-driven owners really do fire Sun-Thu. Returns a list of error strings."""
    errs = []
    txt = read_text(PLAN)
    # Scope: this check guards the INTERNAL consistency of D3's QUEUE HYGIENE step. A plan text with
    # no queue_item_stale raise at all has nothing to guard (the checker's own unit-test fixtures
    # build exactly such a minimal plan), so skip rather than fail. But if the raise IS present and
    # the clause-(b) slot table is NOT, the guard has been disarmed for real -- report that loudly.
    if QUEUE_OWNER_SLOT_SCOPE not in txt:
        return []
    i = txt.find(QUEUE_OWNER_SLOT_ANCHOR)
    if i < 0:
        return [f"Claude_Task_Plan.md: names the {QUEUE_OWNER_SLOT_SCOPE!r} raise but has no "
                f"{QUEUE_OWNER_SLOT_ANCHOR!r} paragraph — check Q's fire-time mirror guard is "
                f"DISARMED. That paragraph carries the AR_att/AR_orc/D3/SL2/SL5 slot table the "
                f"queue_item_stale suppress/raise decision reads. Restore it, or update this "
                f"checker's anchor."]
    para = txt[i:txt.find("\n\n", i) if txt.find("\n\n", i) > 0 else len(txt)]
    pairs = dict(QUEUE_OWNER_SLOT_PAIR.findall(para))
    expect_ids = set(QUEUE_DRIVEN_OWNERS) | {"D3"}
    if not pairs:
        return ["Claude_Task_Plan.md: found the OWNER-ELIGIBLE-DAY BRANCH clause-(b) paragraph but "
                "parsed ZERO '<routine> HH:MM' pairs out of it — check Q is DISARMED (regex rot, or "
                "the table was reformatted). Restore a parseable table."]
    missing = sorted(expect_ids - set(pairs))
    if missing:
        errs.append(f"Claude_Task_Plan.md: the OWNER-ELIGIBLE-DAY BRANCH slot table omits "
                    f"{', '.join(missing)} — clause (b) compares D3's own run moment against every "
                    f"queue-driven owner's slot, so all of {', '.join(sorted(expect_ids))} must appear.")
    for rid, shown in sorted(pairs.items()):
        r = cad.get(rid)
        if r is None:
            errs.append(f"Claude_Task_Plan.md: the OWNER-ELIGIBLE-DAY BRANCH slot table names "
                        f"'{rid}', which is not a routine id in ops/cadence.yaml.")
            continue
        want_local = str((r.get("expected_trigger") or {}).get("time_local", "")).strip()
        if not want_local:
            errs.append(f"ops/cadence.yaml: {rid} has no expected_trigger.time_local, so D3's "
                        f"OWNER-ELIGIBLE-DAY BRANCH slot table cannot be verified against it.")
            continue
        if shown != want_local:
            errs.append(f"Claude_Task_Plan.md: the OWNER-ELIGIBLE-DAY BRANCH slot table says {rid} "
                        f"fires at {shown}, but ops/cadence.yaml expected_trigger.time_local says "
                        f"{want_local}. That table is what D3's queue_item_stale suppress/raise "
                        f"decision compares against, so a stale minute silently mis-decides the "
                        f"fleet's only dead-trigger detector. Update BOTH in the same pass "
                        f"(ops/cadence.yaml is the source of truth).")
    for rid in QUEUE_DRIVEN_OWNERS:
        r = cad.get(rid)
        if r is None:
            continue
        cron = str((r.get("expected_trigger") or {}).get("cron_utc", "")).split()
        if len(cron) != 5:
            errs.append(f"ops/cadence.yaml: {rid} expected_trigger.cron_utc is not a 5-field cron, "
                        f"so the OWNER-ELIGIBLE-DAY BRANCH's 'fires Sun-Thu' premise cannot be verified.")
            continue
        if cron[4] != "1,2,3,4,5":
            errs.append(f"ops/cadence.yaml: {rid} cron_utc day-of-week is '{cron[4]}', not "
                        f"'1,2,3,4,5' (UTC Mon-Fri = Denver Sun-Thu). D3's OWNER-ELIGIBLE-DAY BRANCH "
                        f"asserts all four queue-driven owners fire Sun-Thu and counts eligible days "
                        f"on that basis; if this owner's day-set really changed, update that "
                        f"paragraph in the same pass.")
    return errs


def main():
    # Parsed/scanned ONCE and threaded through every check that needs it -- see the PERF NOTE above
    # load_cadence() (cadence.yaml, cadence#3) and above _scan_bigquery_dir() (the bigquery/ tree
    # walk, cadence#1). bq_scan/stalled_scan reuse the SAME scan when BIGQUERY_DIR and STALLED_RUNS_
    # BIGQUERY_DIR currently point at the same directory (true in production; see STALLED_RUNS_
    # BIGQUERY_DIR's own comment near BIGQUERY_DIR) and fall back to two independent scans when a
    # test has made them diverge -- read fresh here on every main() call, never cached across calls,
    # so a monkeypatch between two main() calls in the same test process is always picked up.
    cadence_doc = load_yaml(CADENCE)
    cad = load_cadence(cadence_doc)
    bq_scan = _scan_bigquery_dir(BIGQUERY_DIR)
    stalled_scan = (bq_scan if STALLED_RUNS_BIGQUERY_DIR == BIGQUERY_DIR
                     else _scan_bigquery_dir(STALLED_RUNS_BIGQUERY_DIR))
    headings = plan_headings()
    errors = []

    # ---- duplicate routine id in ops/cadence.yaml's routines list (silently collapsed by
    # load_cadence()'s dict comprehension otherwise -- see cadence_duplicate_ids()'s docstring) ----
    for rid in cadence_duplicate_ids(cadence_doc):
        errors.append(f"ops/cadence.yaml: duplicate routine id '{rid}' — each routine id must "
                      f"appear exactly once")

    # ---- canonical maps from the SOURCE OF TRUTH (cadence.yaml + the plan) ----
    head_by_id, dup = {}, []
    for h in headings:
        rid = heading_to_id(h)
        if rid is None:
            errors.append(f"plan heading does not map to a routine id (bad format?): '{h}'")
            continue
        if rid in head_by_id:
            dup.append(rid)
        head_by_id[rid] = h
    for rid in dup:
        errors.append(f"duplicate Claude_Task_Plan.md heading for id {rid}")

    # check B must derive its expectation from the SAME shared template check F uses (lib/
    # routine_manifest.instruction_text) rather than re-literalizing the f-string here -- that literal
    # was the 4th independent copy the 2026-07-20 extraction was supposed to kill (codebase audit
    # 2026-07-26): edit instruction_text's wording and regenerate bigquery/15 via gen_routine_lists.py
    # --write, and this hardcoded copy would silently compute the OLD string, failing CI for every
    # routine with a diff that points at cadence.yaml/plan headings instead of the real culprit.
    want_catalog = {rid: instruction_text(h) for rid, h in head_by_id.items()}
    want_expected = {rid: r["monitor_class"] for rid, r in cad.items()
                     if r.get("monitor_class") in CALENDAR_CLASSES}

    # ---- validate monitor_class presence + vocabulary ----
    for rid, r in cad.items():
        mc = r.get("monitor_class")
        if mc is None:
            errors.append(f"{rid}: missing monitor_class in ops/cadence.yaml")
        elif mc not in ALLOWED_CLASSES:
            errors.append(f"{rid}: monitor_class '{mc}' not in {sorted(ALLOWED_CLASSES)}")

    # ---- depends_on references must be known routine ids (silent-drift guard) ----
    errors.extend(check_depends_on(cad))

    # ---- C. cadence.yaml id <-> plan heading 1:1 ----
    for rid in cad:
        if rid not in head_by_id:
            errors.append(f"{rid}: in ops/cadence.yaml but no matching Claude_Task_Plan.md heading")
    for rid in head_by_id:
        if rid not in cad:
            errors.append(f"{rid}: Claude_Task_Plan.md heading but no ops/cadence.yaml routine")

    # ---- A. state.cadence_expected_today (12_*.sql) == calendar-class routines in cadence.yaml ----
    have_expected = parse_expected_sql()
    if not have_expected:
        errors.append("could not parse any STRUCT(... AS schedule) rows from 12_cadence_monitor.sql")
    errors.extend(class_map_errors(
        want_expected, have_expected,
        missing_from="state.cadence_expected_today (12_cadence_monitor.sql)",
        mismatch_label="schedule class mismatch", mismatch_ref="12_cadence_monitor.sql",
        extra_in="state.cadence_expected_today (12_*.sql)",
        extra_not_a="calendar-class routine in cadence.yaml (queue_driven/unknown routines must NOT be listed)"))

    # ---- B. ops.routine_catalog (15_*.sql) == plan-heading-derived instruction ----
    have_catalog = parse_catalog_sql()
    if not have_catalog:
        errors.append("could not parse any catalog STRUCT rows from 15_routine_catalog.sql")
    for rid, instr in want_catalog.items():
        if rid not in have_catalog:
            errors.append(f"{rid}: has a plan heading but is MISSING from ops.routine_catalog (15_*.sql)")
        elif have_catalog[rid] != instr:
            errors.append(f"{rid}: routine_catalog instruction drift\n"
                          f"     plan-derived: {instr}\n"
                          f"     15_*.sql:     {have_catalog[rid]}")
    for rid in have_catalog:
        if rid not in want_catalog:
            errors.append(f"{rid}: in ops.routine_catalog (15_*.sql) but has no Claude_Task_Plan.md heading")

    # ---- D. cadence_watch deadline guard: cadence.yaml constant == bigquery/12 SQL TIME literal ----
    want_deadline = cadence_deadline_yaml(cadence_doc)
    have_deadlines = parse_deadline_sql()
    deadline_ok = True
    if want_deadline is None:
        errors.append("ops/cadence.yaml: missing top-level 'cadence_watch_deadline_local' "
                      "(declares the state.cadence_watch deadline-guard time)")
        deadline_ok = False
    elif not (isinstance(want_deadline, str) and HHMM.match(want_deadline)):
        errors.append(f"ops/cadence.yaml: cadence_watch_deadline_local must be a quoted \"HH:MM\" string "
                      f"(got {want_deadline!r} — an UNquoted 21:00 is YAML base-60 = 1260; always quote it)")
        deadline_ok = False
    if not have_deadlines:
        errors.append("bigquery/12_cadence_monitor.sql: could not parse the DATETIME(e.today, TIME '..') "
                      "deadline-guard literal from state.cadence_watch (did the clause change shape?)")
        deadline_ok = False
    elif len(set(have_deadlines)) > 1:
        errors.append(f"bigquery/12_cadence_monitor.sql: multiple distinct deadline literals "
                      f"{sorted(set(have_deadlines))} in state.cadence_watch — expected exactly one")
        deadline_ok = False
    if deadline_ok and have_deadlines[0] != want_deadline:
        errors.append(f"cadence_watch deadline DRIFT — ops/cadence.yaml='{want_deadline}' vs "
                      f"bigquery/12_cadence_monitor.sql TIME='{have_deadlines[0]}'. Keep them in sync.")

    # ---- D (extended, 2026-08-06, bigquery/142 revert follow-up): the CANONICAL (highest-numbered)
    # bigquery/*.sql file CURRENTLY defining state.cadence_watch must ALSO agree with cadence.yaml.
    # bigquery/12 is itself long superseded (48 -> 113 -> 129 -> 142); the check above only ever compared
    # against that original, no-longer-deployed body, so a deadline change landed in a superseding file
    # (129's 21:00->21:45 autotune, then 142's revert back to 21:00) had NO CI guard tying it back to
    # cadence.yaml at all — the same registry-vs-body split class check_sq_version_registry.py exists to
    # catch for a heartbeat literal, applied here to this view. ----
    canon_deadlines, canon_number, canon_fn, canon_ambiguous = parse_canonical_deadline_sql(bq_scan)
    canon_deadline_ok = True
    if canon_ambiguous is not None:
        errors.append(
            f"AMBIGUOUS canonical file for state.cadence_watch — bigquery/{canon_number} is the "
            f"winning (highest) leading number, but {len(canon_ambiguous)} DIFFERENT files share it "
            f"and each defines `CREATE OR REPLACE VIEW state.cadence_watch`: "
            f"{', '.join('bigquery/' + fn for fn in canon_ambiguous)}. Check D's canonical-file "
            f"deadline guard cannot determine which is actually deployed — renumber one file so the "
            f"leading number is unique, or determine which definition is actually deployed and "
            f"delete/renumber the other.")
        canon_deadline_ok = False
    elif canon_fn is None:
        errors.append("could not find any bigquery/*.sql file defining "
                      "`CREATE OR REPLACE VIEW state.cadence_watch` at all — check D's canonical-file "
                      "deadline guard cannot run")
        canon_deadline_ok = False
    else:
        if not canon_deadlines:
            errors.append(f"bigquery/{canon_fn}: could not parse the DATETIME(e.today, TIME '..') "
                          f"deadline-guard literal from its state.cadence_watch definition (the "
                          f"highest-numbered file currently defining it — did the clause change shape?)")
            canon_deadline_ok = False
        elif len(set(canon_deadlines)) > 1:
            errors.append(f"bigquery/{canon_fn}: multiple distinct deadline literals "
                          f"{sorted(set(canon_deadlines))} in its state.cadence_watch definition — "
                          f"expected exactly one")
            canon_deadline_ok = False
    if deadline_ok and canon_deadline_ok and canon_fn is not None and canon_deadlines[0] != want_deadline:
        errors.append(f"cadence_watch deadline DRIFT (canonical file) — ops/cadence.yaml="
                      f"'{want_deadline}' vs bigquery/{canon_fn} (the highest-numbered file currently "
                      f"defining state.cadence_watch) TIME='{canon_deadlines[0]}'. Keep them in sync.")

    # ---- E. period_grace_days: cadence.yaml == bigquery/24_cadence_period_watch.sql ----
    want_grace = cadence_period_grace_yaml(cadence_doc)
    have_grace = parse_period_grace_sql()
    if have_grace is not None:  # file present; if absent, this repo predates the feature — skip silently
        if want_grace is None:
            errors.append("ops/cadence.yaml: missing top-level 'period_grace_days' "
                          "(bigquery/24_cadence_period_watch.sql exists and needs a declared source of truth)")
        else:
            for cls in ("weekly_sun", "monthly_ftd", "quarterly_ftd", "annual_ftd"):
                y, s = want_grace.get(cls), have_grace.get(cls)
                if y is None:
                    errors.append(f"ops/cadence.yaml period_grace_days: missing '{cls}'")
                elif s is None:
                    errors.append(f"bigquery/24_cadence_period_watch.sql: could not parse a grace literal for '{cls}'")
                elif y != s:
                    errors.append(f"period_grace_days DRIFT for {cls} — ops/cadence.yaml={y} vs "
                                  f"bigquery/24_cadence_period_watch.sql={s}. Keep them in sync.")

    # ---- J. state.cadence_period_watch's `routines` CTE (24_*.sql) == period-class routines in
    # cadence.yaml (ARCH-3 Item 30b) — the GENERATED counterpart to check A, for the period-tier list. ----
    want_period_routines = {rid: r["monitor_class"] for rid, r in cad.items()
                             if r.get("monitor_class") in PERIOD_CLASSES}
    have_period_routines = parse_period_watch_routines_sql()
    if have_period_routines is not None:  # file present; absent = pre-feature checkout, skip silently
        if not have_period_routines:
            errors.append("could not parse any labelled STRUCT(... AS monitor_class) rows from "
                          "24_cadence_period_watch.sql's `routines` CTE")
        errors.extend(class_map_errors(
            want_period_routines, have_period_routines,
            missing_from="state.cadence_period_watch's routines CTE (24_cadence_period_watch.sql)",
            mismatch_label="period-watch monitor_class mismatch", mismatch_ref="24_cadence_period_watch.sql",
            extra_in="state.cadence_period_watch's routines CTE (24_*.sql)",
            extra_not_a="period-class routine in cadence.yaml"))

    # ---- K. catchup_safe: every cadence.yaml routine must declare the boolean, and bigquery/31/59's
    # hand-maintained UNNEST id lists must equal the corresponding {catchup_safe AND monitor_class in
    # <tier>} subset (ARCH-3 Item 30b — these two lists previously had ZERO drift protection). ----
    for rid, r in cad.items():
        if "catchup_safe" not in r:
            errors.append(f"{rid}: missing catchup_safe boolean in ops/cadence.yaml")
        elif not isinstance(r["catchup_safe"], bool):
            errors.append(f"{rid}: catchup_safe must be a boolean true/false (got {r['catchup_safe']!r})")

    errors.extend(catchup_list_errors(
        cad, CATCHUP_NOTIFY_SQL, "bigquery/31_catchup_notify.sql", "daily", DAILY_CLASSES))
    errors.extend(catchup_list_errors(
        cad, CATCHUP_AUTOFIRE_SQL, "bigquery/59_catchup_autofire.sql", "period", PERIOD_CLASSES))

    # ---- L. Claude_Task_Plan.md's ROUTINE INVENTORY table == cadence.yaml ids, and each row's
    # 'Cadence · Type' cell agrees with that routine's monitor_class (ARCH-3 Item 30b). ----
    have_inventory = parse_inventory_table(PLAN)
    if have_inventory is None:
        # 2026-07-29: unconditional hard error, not a skip. A prior version of this check tried to
        # tell "heading never introduced" (skip silently) apart from "heading reworded" (fail loud)
        # via a loose substring search — PROVEN DEFEATABLE the same day by a rewording that drops the
        # substring too (e.g. "# ROUTINE ROSTER & BIGQUERY RESPONSIBILITIES"), which made both
        # branches miss and let main() exit 0 silently, reproducing the exact bug the heuristic
        # existed to catch. The ROUTINE INVENTORY table is a mandatory section of Claude_Task_Plan.md
        # (itself not optional), so "the table can't be found" is a drift error in every case — there
        # is no legitimate skip case left to preserve.
        errors.append(
            f"Claude_Task_Plan.md: could not locate the exact heading '{INVENTORY_HEADING}' followed "
            f"by a parseable ROUTINE INVENTORY table — check L's drift guard cannot run. Either the "
            f"heading text was reworded (restore it exactly as shown above, or update "
            f"INVENTORY_HEADING in this script to match the new text), or the entire ROUTINE "
            f"INVENTORY section was deleted (restore it — the table is mandatory, so its absence is "
            f"itself a drift error, not a pre-feature-checkout case to skip).")
    else:  # heading present and table parsed — compare its rows against ops/cadence.yaml
        have_inventory_ids = {rid for rid, _cell in have_inventory}
        for rid in sorted(set(cad) - have_inventory_ids):
            errors.append(f"{rid}: in ops/cadence.yaml but missing a row in Claude_Task_Plan.md's "
                          f"ROUTINE INVENTORY table")
        for rid in sorted(have_inventory_ids - set(cad)):
            errors.append(f"{rid}: ROUTINE INVENTORY table row has no matching ops/cadence.yaml routine")
        for rid, cell in have_inventory:
            if rid not in cad:
                continue
            mc = cad[rid].get("monitor_class")
            token = cell.strip().split()[0] if cell.strip() else ""
            if rid in INVENTORY_FOOTNOTE_QUEUE_DRIVEN_IDS and token.rstrip("¹") == "Daily" and token.endswith("¹"):
                allowed = {"queue_driven"}
            else:
                allowed = INVENTORY_CADENCE_TOKEN_MAP.get(token)
            if allowed is None:
                errors.append(f"{rid}: ROUTINE INVENTORY 'Cadence · Type' cell first token '{token}' "
                              f"not recognized (Daily/Weekly/Monthly/Quarterly/Annual/Queue-driven)")
            elif mc not in allowed:
                errors.append(f"{rid}: ROUTINE INVENTORY cadence cell '{token}' implies monitor_class in "
                              f"{sorted(allowed)}, but ops/cadence.yaml has monitor_class='{mc}'")

    # ---- F. ops/triggers.json (if present) == the canonical generated map ----
    if os.path.exists(TRIGGERS_JSON):
        want_manifest = generate_triggers_manifest(head_by_id, cad)
        try:
            have_manifest = json.load(open(TRIGGERS_JSON, encoding="utf-8"))
        except (OSError, ValueError) as e:
            errors.append(f"ops/triggers.json: could not parse as JSON ({e})")
            have_manifest = None
        if have_manifest is not None and have_manifest != want_manifest:
            errors.append("ops/triggers.json is STALE — does not match the canonical map derived from "
                          "ops/cadence.yaml + Claude_Task_Plan.md headings. Regenerate with "
                          "`python scripts/print_routines.py --write` and commit the result "
                          "(it must be GENERATED, never hand-edited).")

    # ---- G. ops/trigger_ids.json (if present): unique trigger_ids, no entry for a routine no
    # longer in cadence.yaml (self-improvement audit, 2026-07-14 — this file had zero CI
    # validation despite being nearly identical in shape/purpose to ops/triggers.json). A cad
    # routine with NO entry yet is expected/transient (recorded once its live trigger is created)
    # and is a WARN, not a build failure. ----
    if os.path.exists(TRIGGER_IDS_JSON):
        try:
            trigger_ids_doc = json.load(open(TRIGGER_IDS_JSON, encoding="utf-8"))
        except (OSError, ValueError) as e:
            errors.append(f"ops/trigger_ids.json: could not parse as JSON ({e})")
            trigger_ids_doc = None
        if trigger_ids_doc is not None:
            have_ids = {k: v for k, v in trigger_ids_doc.items() if k != "_meta"}
            by_trigger = {}
            for rid, entry in have_ids.items():
                tid = (entry or {}).get("trigger_id")
                by_trigger.setdefault(tid, []).append(rid)
            for tid, rids in by_trigger.items():
                if tid and len(rids) > 1:
                    errors.append(f"ops/trigger_ids.json: trigger_id '{tid}' is shared by routines "
                                  f"{sorted(rids)} — duplicate/typo'd id would misdirect a live "
                                  f"RemoteTrigger call")
            stale = sorted(rid for rid in have_ids if rid not in cad)
            if stale:
                errors.append(f"ops/trigger_ids.json: entries for routine(s) no longer in "
                              f"ops/cadence.yaml: {stale} — remove the stale entry")
            missing = sorted(rid for rid in cad if rid not in have_ids)
            if missing:
                print(f"NOTE: ops/trigger_ids.json has no entry yet for {missing} (new routine — "
                      f"record its live trigger id once created via RemoteTrigger/Chrome; not a "
                      f"CI failure, per the file's own not-live-synced caveat).")

            # ---- I. expected_trigger: every routine WITH an ops/trigger_ids.json entry must carry a
            # well-formed `expected_trigger` in ops/cadence.yaml (trigger-config-drift audit, 2026-07-16,
            # ARCH-2/CC-5 merge). This is the structured, mechanically-diffable schedule Q4 step E and
            # OPS0 STEP 3 diff a live RemoteTrigger get() against, replacing the old free-text
            # WEB-UI TRIGGER AUDIT comment block as the enforced source of truth. A routine with NO
            # trigger_ids.json entry yet (OPS0, until its live trigger is created) is a NOTE only,
            # mirroring the NOTE just above — not a build failure. ----
            EXPECTED_TRIGGER_RECURRENCE = {"daily", "weekly", "custom_cron"}
            for rid in sorted(cad):
                et = cad[rid].get("expected_trigger")
                if rid not in have_ids:
                    if et is None:
                        print(f"NOTE: {rid} has no expected_trigger yet (no live trigger id recorded "
                              f"either — expected until ops/trigger_ids.json gets an entry for it).")
                    continue
                if et is None:
                    errors.append(f"{rid}: has an ops/trigger_ids.json entry but no 'expected_trigger' "
                                  f"in ops/cadence.yaml (structured schedule required for the "
                                  f"RemoteTrigger-diff self-heal sweep — Q4 step E / OPS0 STEP 3)")
                    continue
                rec = et.get("recurrence")
                if rec not in EXPECTED_TRIGGER_RECURRENCE:
                    errors.append(f"{rid}: expected_trigger.recurrence={rec!r} not in "
                                  f"{sorted(EXPECTED_TRIGGER_RECURRENCE)}")
                    continue
                if "enabled" not in et:
                    errors.append(f"{rid}: expected_trigger missing 'enabled'")
                if rec in ("daily", "weekly"):
                    tl = et.get("time_local")
                    if not (isinstance(tl, str) and HHMM.match(tl)):
                        errors.append(f"{rid}: expected_trigger.time_local must be a quoted \"HH:MM\" "
                                      f"string for recurrence={rec} (got {tl!r} — an unquoted HH:MM is "
                                      f"YAML base-60, same caveat as cadence_watch_deadline_local)")
                elif rec == "custom_cron":
                    cu = et.get("cron_utc")
                    if not (isinstance(cu, str) and cu.strip()):
                        errors.append(f"{rid}: expected_trigger.cron_utc must be a non-empty string "
                                      f"(TO_POPULATE bootstrap placeholder, or an observed cron once a "
                                      f"sweep has populated it) for recurrence=custom_cron")

    # ---- H. auto-merge-claude.yml's RUNBOOK §38 marker-write routine_re must accept every
    # cadence.yaml id (self-improvement audit, 2026-07-14) — this hand-typed alternation is a
    # second copy of the routine-id set already carried by ops/cadence.yaml, with no guard: a
    # routine added to cadence.yaml but not to this regex has its commits silently skipped by the
    # §38 marker-write self-heal, with no CI signal. Only checks the cadence-ids-subset-of-regex
    # direction (under-inclusive/silent-skip) — the regex being a superset is harmless. ----
    # The literal moved into the sourced helper on 2026-07-29. Look in BOTH locations and validate
    # EVERY copy found (not first-match-wins): if the allowlist is ever duplicated across the helper
    # and the workflow, a stale second copy must fail loudly rather than hide behind a complete one.
    # Read the module globals at call time so tests can monkeypatch either path.
    allowlist_paths = [p for p in (AUTO_MERGE_DECISION_SH, AUTO_MERGE_YML) if os.path.exists(p)]
    if allowlist_paths:
        found = [(p, AUTO_MERGE_ROUTINE_RE.search(read_text(p)))
                 for p in allowlist_paths]
        found = [(p, m) for p, m in found if m is not None]
        if not found:
            errors.append("could not find the RUNBOOK §38 marker-write routine allowlist literal in "
                          "scripts/auto_merge_decision.sh or .github/workflows/auto-merge-claude.yml "
                          "— its shape may have changed; update AUTO_MERGE_ROUTINE_RE / "
                          "AUTO_MERGE_DECISION_SH / AUTO_MERGE_YML in this script to match")
        for _p, m in found:
            _rel = os.path.relpath(_p, ROOT)
            routine_re_pat = re.compile(f"^(?:{m.group(1)})$")
            for rid in cad:
                if not routine_re_pat.fullmatch(rid):
                    errors.append(f"{rid}: in ops/cadence.yaml but NOT matched by {_rel}'s "
                                  f"routine_re — RUNBOOK §38 marker-write will silently skip this "
                                  f"routine's commits (add it to the routine_re alternation)")
    else:
        # Both candidate locations missing is not "nothing to check", it is check H having no signal
        # at all — the same silent-no-op shape as the substring-gate bug check M had (2026-08-08 audit
        # finding). Neither file existing at once is implausible today, but a future rename/move of
        # BOTH without updating this script must not read as a clean CI run.
        errors.append("could not find the RUNBOOK §38 marker-write routine allowlist source — neither "
                      f"{os.path.relpath(AUTO_MERGE_DECISION_SH, ROOT)} nor "
                      f"{os.path.relpath(AUTO_MERGE_YML, ROOT)} exists, so check H validated nothing; "
                      "restore one of these files or update AUTO_MERGE_DECISION_SH / AUTO_MERGE_YML "
                      "in this script to match their new location")

    # ---- M. EVENING-slot daily SAME-DAY guard copies carry the noon-threshold clause (H1). ----
    # Used to be gated on the "SAME-DAY DOUBLE-RUN GUARD" sentinel being present at all, on the theory
    # that this only ever skips a minimal test fixture / pre-feature checkout — but a bare substring
    # gate fails open on ANY loss of that heading (a rename, a rewrite that drops the sentinel word),
    # silently disarming the whole check with no CI signal, not just the fixture case it was written
    # for (2026-08-08 audit finding). The inner loop below already errors loudly, per routine, when
    # GUARD_QUERY_RE[rid] finds no match — there is no reason total absence of the sentinel should be
    # quieter than that. Run unconditionally: a plan with zero SAME-DAY DOUBLE-RUN GUARD text now fails
    # loudly (one error per EVENING_DAILY_GUARD_IDS routine) instead of passing vacuously. Test
    # fixtures that don't care about check M must now carry valid guard text too (see
    # tests/test_cadence_consistency.py's _write_check_fixture / _AR_ATT_PLAN).
    #
    # Membership cross-check FIRST (see evening_slot_guard_membership_errors()'s own docstring): this
    # only asserts every evening-slot routine has been classified into EVENING_DAILY_GUARD_IDS or
    # NOON_CLAUSE_EXEMPT_EVENING_IDS by a human — it does NOT touch Claude_Task_Plan.md, so it cannot
    # itself go vacuous the way a text-derived membership check could.
    errors.extend(evening_slot_guard_membership_errors(cad))

    plan_txt = open(PLAN, encoding="utf-8").read()
    for rid in EVENING_DAILY_GUARD_IDS:
        matches = list(GUARD_QUERY_RE[rid].finditer(plan_txt))
        if not matches:
            errors.append(f"{rid}: could not find its SAME-DAY DOUBLE-RUN GUARD `ops.run_log` "
                          f"COUNT(*) query in Claude_Task_Plan.md — check M's H1 noon-threshold guard "
                          f"is DISARMED for this routine (did the guard query change shape?)")
            continue
        for m in matches:
            if not GUARD_NOON_CLAUSE_RE.search(m.group("after")):
                errors.append(
                    f"{rid}: SAME-DAY DOUBLE-RUN GUARD copy is MISSING the noon-threshold clause "
                    f"(H1) — an EVENING-slot daily routine (slot >= 16:00 MT) must count only "
                    f"completions in the real evening window: append "
                    f"`AND DATETIME(log_ts,'America/Denver') >= DATETIME(<today, America/Denver>, "
                    f"TIME '12:00:00')` to its `status='completed'` COUNT(*) query, so a post-midnight "
                    f"prior-day run mis-stamped onto today by bigquery/12's midnight-crossing grace "
                    f"cannot cancel the genuine evening run (see the shared Observability guard's "
                    f"CYCLE-AWARE VARIANT).")

    # ---- N. model of record: cadence.yaml routine_model == every mirror site ----
    model_errs, model_of_record = check_model_of_record(cadence_doc)
    errors.extend(model_errs)

    # ---- O. state.stalled_runs' `cls` CTE routine list == ops/cadence.yaml's routine ids, BOTH
    # directions (see the comment above STALLED_RUNS_VIEW_DDL for the full WHY -- this is the same
    # class of gap that let OPS0/OPS1/OPS2 hang undetected for weeks until bigquery/148). ----
    cls_ids, cls_number, cls_fn, cls_ambiguous = parse_stalled_runs_cls_ids(stalled_scan)
    if cls_ambiguous is not None:
        errors.append(
            f"AMBIGUOUS canonical file for state.stalled_runs — bigquery/{cls_number} is the "
            f"winning (highest) leading number, but {len(cls_ambiguous)} DIFFERENT files share it "
            f"and each defines `CREATE OR REPLACE VIEW state.stalled_runs`: "
            f"{', '.join('bigquery/' + fn for fn in cls_ambiguous)}. Check O's cls-list drift guard "
            f"cannot determine which is actually deployed — renumber one file so the leading number "
            f"is unique, or determine which definition is actually deployed and delete/renumber the "
            f"other.")
    elif cls_fn is None:
        errors.append("could not find any bigquery/*.sql file defining "
                      "`CREATE OR REPLACE VIEW state.stalled_runs` at all — check O's cls-list drift "
                      "guard cannot run")
    elif not cls_ids:
        errors.append(f"bigquery/{cls_fn}: could not parse any routine id out of state.stalled_runs' "
                      f"`cls` CTE UNNEST([...]) STRUCT list — check O's cls-list drift guard is "
                      f"DISARMED (regex rot? e.g. a reformat of the STRUCT(...) rows, or of the "
                      f"`cls AS (... UNNEST([...]) ...)` shape itself). Restore a parseable `cls` CTE.")
    else:
        cls_set, cad_set = set(cls_ids), set(cad)
        for rid in sorted(cad_set - cls_set):
            errors.append(f"{rid}: in ops/cadence.yaml but MISSING from bigquery/{cls_fn}'s "
                          f"state.stalled_runs `cls` CTE — this routine can NEVER be flagged "
                          f"routine_stalled no matter how long it hangs (the `JOIN cls c USING "
                          f"(routine)` INNER join drops it before the terminal-row anti-join or "
                          f"elapsed-hours threshold ever run — this is exactly the OPS0/OPS1/OPS2 "
                          f"gap bigquery/148 fixed). Add a STRUCT('{rid}', <min_stale_hours>) entry.")
        for rid in sorted(cls_set - cad_set):
            errors.append(f"{rid}: in bigquery/{cls_fn}'s state.stalled_runs `cls` CTE but not a "
                          f"routine id in ops/cadence.yaml — stale entry for a retired/renamed "
                          f"routine, remove it.")

    # ---- check Q: D3's OWNER-ELIGIBLE-DAY BRANCH fire-time table mirrors cadence.yaml ----
    errors.extend(queue_owner_slot_mirror_errors(cad))

    # ---- report ----
    # REFACTOR (2026-08-31 code-quality pass, cross-cutting#0): the FAIL/OK print-and-exit
    # boilerplate now lives in lib/report.py's fail_or_ok(), shared with a dozen sibling checkers —
    # see that module's docstring. The OK-line's `extra`/`canon_note` pieces are built unconditionally
    # here (previously only in the no-errors branch) purely to feed the single fail_or_ok() call
    # below; they are pure string-building over values already computed above with no I/O of their
    # own, so building them even on a FAIL run (where fail_or_ok then never looks at ok_line) changes
    # nothing observable.
    extra = ""
    if have_grace is not None:
        extra += " period_grace_days matches 24_cadence_period_watch.sql."
    if os.path.exists(TRIGGERS_JSON):
        extra += " ops/triggers.json is current."
    if model_of_record:
        extra += f" routine_model {model_of_record} matches all mirror sites."
    if cls_fn is not None:
        extra += f" state.stalled_runs cls list (bigquery/{cls_fn}) matches all {len(cad)} routine ids."
    canon_note = (f" and bigquery/{canon_fn} (canonical)" if canon_fn is not None else "")
    return fail_or_ok(
        "CADENCE CONSISTENCY", errors,
        f"CADENCE CONSISTENCY: OK — {len(cad)} routines; "
        f"{len(want_expected)} calendar-class match state.cadence_expected_today; "
        f"{len(have_catalog)} catalog entries match the plan headings; "
        f"cadence_watch deadline {want_deadline} matches 12_cadence_monitor.sql (superseded reference)"
        f"{canon_note}.{extra}",
        hint=("Fix ops/cadence.yaml (monitor_class) / Claude_Task_Plan.md headings and the matching "
              "bigquery/12_cadence_monitor.sql + bigquery/15_routine_catalog.sql so all three agree, "
              "then re-run. (See ops/cadence.yaml header + scripts/print_routines.py.)"),
    )


if __name__ == "__main__":
    raise SystemExit(main())
