#!/usr/bin/env python3
"""Single-source the cadence: fail CI if the hand-kept SQL drifts from ops/cadence.yaml + the plan.

WHY THIS EXISTS. "What runs when" was hand-maintained in THREE places that had to stay in lockstep
with no automated guard:
  1. ops/cadence.yaml                          — the documented manifest (now carries monitor_class)
  2. state.cadence_expected_today (SQL)        — bigquery/12_cadence_monitor.sql, a hardcoded routine list
  3. ops.routine_catalog (SQL)                 — bigquery/15_routine_catalog.sql, a hardcoded instruction seed
plus the canonical routine headings in Claude_Task_Plan.md. A routine added / renamed / rescheduled in
one place but not the others drifted silently — exactly the RUNBOOK §22-class problem. This check makes
ops/cadence.yaml + Claude_Task_Plan.md the SOURCE OF TRUTH and verifies the two SQL files agree:

  A. state.cadence_expected_today's (routine -> schedule-class) set == cadence.yaml's
     (id -> monitor_class) for every routine whose monitor_class is calendar-predictable
     (i.e. != queue_driven; the AR routines are deliberately excluded from the calendar view).
  B. ops.routine_catalog's (routine -> canonical_instruction) == the instruction derived from each
     Claude_Task_Plan.md routine heading ("Read Claude_Task_Plan.md. Perform <heading>.").
  C. Every cadence.yaml routine id maps 1:1 to a Claude_Task_Plan.md heading and appears in the catalog
     (the scripts/print_routines.py cross-check, extended to the SQL layer).
  D. cadence.yaml's top-level `cadence_watch_deadline_local` == the TIME literal in the
     state.cadence_watch deadline guard (bigquery/12_cadence_monitor.sql). The deadline is otherwise a
     bare SQL constant with no source of truth, so a real cadence shift could silently leave it stale and
     re-open the pre-deadline false-positive window (RUNBOOK §1 step 3 / §20 follow-up).
  E. cadence.yaml's top-level `period_grace_days` == the OFFSET/day-count literals in
     state.cadence_period_watch (bigquery/24_cadence_period_watch.sql) — added 2026-07-03,
     self-improvement audit WO-1/B-6-obs, same discipline as check D.
  F. ops/triggers.json (if present) == the canonical {id, monitor_class, instruction} map derived from
     cadence.yaml + Claude_Task_Plan.md headings — GENERATED by `scripts/print_routines.py --write`,
     never hand-kept (self-improvement audit WO-2). If the file does not yet exist this check is
     skipped (it is an opt-in artifact, not required for every clone).
  J. state.cadence_period_watch's (routine -> monitor_class) STRUCT rows (bigquery/24_cadence_period_
     watch.sql `routines` CTE) == cadence.yaml's routines whose monitor_class is one of the four period
     classes (weekly_sun/monthly_ftd/quarterly_ftd/annual_ftd). The rows are GENERATED by
     `scripts/gen_routine_lists.py --write`; this check verifies the CONTENT still agrees (ARCH-3 Item
     30b, 2026-07-16 — this list previously had zero CI list-drift protection at all).
  K. bigquery/31_catchup_notify.sql's and bigquery/59_catchup_autofire.sql's hand-maintained
     catchup-safe UNNEST id lists == the {routine : catchup_safe AND monitor_class in <tier>} subset of
     cadence.yaml (31 = daily tier: daily_trading/daily_all; 59 = period tier: the four period
     classes). Also requires every cadence.yaml routine to declare an explicit `catchup_safe` boolean
     (missing key = error, mirroring the monitor_class presence check) — these two lists are a
     DECLARED capital-adjacency judgment, never derived from monitor_class (ARCH-3 Item 30b).
  L. The ROUTINE INVENTORY table in Claude_Task_Plan.md (the section between the "# ROUTINE INVENTORY
     & BIGQUERY RESPONSIBILITIES" heading and the next `---` divider) lists exactly the cadence.yaml
     routine ids, and each row's "Cadence · Type" cell agrees with that routine's monitor_class (ARCH-3
     Item 30b — this table previously had zero CI coverage).

This does NOT generate the bigquery/12/15/24 STRUCT rows by hand — `scripts/gen_routine_lists.py
--write` does that (checks A/B/J verify the generator's OUTPUT agrees with cadence.yaml; the CI step
`gen_routine_lists.py --check` verifies the committed files are byte-current with what --write would
produce). This script does NOT generate bigquery/31/59's catchup-safe lists or the plan's ROUTINE
INVENTORY table (those stay hand-authored, declared judgment calls) — it only CHECKS them (checks K/L),
so editing cadence.yaml or a plan heading and forgetting a dependent file fails the build with a
precise diff instead of surfacing weeks later as a false cadence/instruction_drift alert.

Usage:  python scripts/check_cadence_consistency.py        # exit 0 if consistent, 1 + diff if not
"""
import json
import os
import re
import sys

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    raise SystemExit(2)

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib.routine_manifest import (  # noqa: E402
    heading_to_id, parse_routine_headings, build_triggers_manifest, instruction_text,
)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLAN = os.path.join(ROOT, "Claude_Task_Plan.md")
CADENCE = os.path.join(ROOT, "ops", "cadence.yaml")
CADENCE_SQL = os.path.join(ROOT, "bigquery", "12_cadence_monitor.sql")
CATALOG_SQL = os.path.join(ROOT, "bigquery", "15_routine_catalog.sql")
PERIOD_WATCH_SQL = os.path.join(ROOT, "bigquery", "24_cadence_period_watch.sql")
TRIGGERS_JSON = os.path.join(ROOT, "ops", "triggers.json")
TRIGGER_IDS_JSON = os.path.join(ROOT, "ops", "trigger_ids.json")
AUTO_MERGE_YML = os.path.join(ROOT, ".github", "workflows", "auto-merge-claude.yml")
CATCHUP_NOTIFY_SQL = os.path.join(ROOT, "bigquery", "31_catchup_notify.sql")
CATCHUP_AUTOFIRE_SQL = os.path.join(ROOT, "bigquery", "59_catchup_autofire.sql")

# The RUNBOOK §38 marker-write routine-id allowlist: routine_re='^(D1|D2a|...)$'
AUTO_MERGE_ROUTINE_RE = re.compile(r"routine_re='\^\(([^)]+)\)\$'")

# state.cadence_period_watch's OFFSET-N literals, keyed by the column alias they compute.
PERIOD_GRACE_OFFSET = re.compile(r"OFFSET (\d+)\)\s*AS (month|quarter|year)_grace_day")
# The weekly grace is a calendar-day count from that week's Sunday (not an OFFSET into trading days).
PERIOD_GRACE_WEEKLY = re.compile(r"DATE_ADD\(n\.week_start,\s*INTERVAL (\d+) DAY\)")

# The four "period" monitor_class values (check J/K's period tier + the ROUTINE INVENTORY cadence-cell
# mapping, check L). daily_trading/daily_all are the "daily" tier (check K's bigquery/31 side).
PERIOD_CLASSES = {"weekly_sun", "monthly_ftd", "quarterly_ftd", "annual_ftd"}
DAILY_CLASSES = {"daily_trading", "daily_all"}

# ---- check M (H1, whole-system deep audit 2026-07-17): the EVENING-slot daily cohort's SAME-DAY
# DOUBLE-RUN GUARD copies must carry the noon-threshold clause. bigquery/12's midnight-crossing grace
# can stamp a post-midnight prior-day run onto today's run_date; without counting ONLY completions
# whose log_ts is in the real evening window, that mis-stamped early-AM completion cancels the genuine
# evening run. D1/D2/D3/SL3 each carry a per-routine guard copy in Claude_Task_Plan.md (D2a has no
# per-routine copy — its double-run risk is covered by D2's own guard, not a copy of its own). Each
# copy's ops.run_log COUNT(*) query must therefore also filter
# `AND DATETIME(log_ts,'America/Denver') >= DATETIME(<today...>, TIME '12:00:00')`.
EVENING_DAILY_GUARD_IDS = ("D1", "D2", "D3", "SL3")
# The guard query's stable prefix (D2's copy omits the ", America/Denver" qualifier on <today>, so the
# run_date token is matched loosely), capturing what follows status='completed' up to the closing `.
GUARD_QUERY_RE = {
    rid: re.compile(
        r"routine='%s' AND run_date=<today[^>]*> AND status='completed'(?P<after>[^`]{0,160})" % rid)
    for rid in EVENING_DAILY_GUARD_IDS
}
GUARD_NOON_CLAUSE_RE = re.compile(
    r"AND DATETIME\(log_ts,'America/Denver'\) >= DATETIME\(<today[^>]*>, TIME '12:00:00'\)")

# ---- check J: bigquery/24's post-normalization STRUCT rows are ALWAYS fully labelled (both
# `AS routine` and `AS monitor_class`) -- scripts/gen_routine_lists.py emits every row this way.
PERIOD_WATCH_ROUTINE_ROW = re.compile(
    r"STRUCT\('([^']+)'\s+AS routine,\s*'([^']+)'\s+AS monitor_class\)")

# ---- check K: bigquery/31/59's hand-maintained catchup-safe UNNEST([...]) AS routine id lists.
SQL_LINE_COMMENT = re.compile(r"--[^\n]*")
UNNEST_ROUTINE_BRACKET = re.compile(r"UNNEST\(\[(.*?)\]\)\s*AS routine", re.S)
QUOTED_ID = re.compile(r"'([A-Za-z0-9_]+)'")

# ---- check L: the ROUTINE INVENTORY table section of Claude_Task_Plan.md (scoped between its own
# heading and the NEXT '---' divider -- the strategy slice-map table elsewhere in the file also has
# `| **...** |`-shaped rows and must NOT be swept in).
INVENTORY_HEADING = "# ROUTINE INVENTORY & BIGQUERY RESPONSIBILITIES"
# Columns: | ID | Routine | Cadence · Type | BigQuery reads | BigQuery writes | Cadence .md output |
# — group 1 is the id, group 2 is the 'Cadence · Type' cell (the 3rd column; the 2nd, the routine
# name, is skipped over).
INVENTORY_ROW = re.compile(r"^\|\s*\*\*([A-Za-z0-9_]+)\*\*\s*\|[^|]*\|([^|]*)\|", re.M)
# First token of the 'Cadence · Type' cell -> the set of monitor_class values it may legitimately mean.
INVENTORY_CADENCE_TOKEN_MAP = {
    "Daily": DAILY_CLASSES,
    "Weekly": {"weekly_sun"},
    "Monthly": {"monthly_ftd"},
    "Quarterly": {"quarterly_ftd"},
    "Annual": {"annual_ftd"},
    "Queue-driven": {"queue_driven"},
}
# AR_att/AR_orc's cell reads 'Daily¹' (footnote ¹: queue-driven, fires daily but no-ops unless due).
INVENTORY_FOOTNOTE_QUEUE_DRIVEN_IDS = {"AR_att", "AR_orc"}

ALLOWED_CLASSES = {
    "daily_trading", "daily_all", "weekly_sun",
    "monthly_ftd", "quarterly_ftd", "annual_ftd", "queue_driven",
}
# monitor_class values the calendar view (state.cadence_expected_today) must encode.
CALENDAR_CLASSES = ALLOWED_CLASSES - {"queue_driven"}

# The state.cadence_watch deadline-guard literal: DATETIME(e.today, TIME 'HH:MM:SS'). Capture HH:MM.
SQL_DEADLINE = re.compile(r"DATETIME\(\s*e\.today\s*,\s*TIME\s*'(\d{2}:\d{2})(?::\d{2})?'\s*\)")
HHMM = re.compile(r"^\d{2}:\d{2}$")


def plan_headings():
    """Ordered routine section headings from Claude_Task_Plan.md (shared parser)."""
    return parse_routine_headings(PLAN)


def load_cadence():
    doc = yaml.safe_load(open(CADENCE, encoding="utf-8")) or {}
    return {r["id"]: r for r in doc.get("routines", [])}


def cadence_duplicate_ids():
    """[id, ...] (sorted, deduped) for any routine id appearing more than once in ops/cadence.yaml's
    routines list. load_cadence()'s dict comprehension above silently keeps only the LAST such entry
    (valid YAML, no parse error -- a duplicate `id:` across list items, not a duplicate mapping key),
    so every downstream check would validate against whichever duplicate happened to be listed last
    with zero signal. This walks the raw list first so a duplicate id fails loud instead, mirroring
    the duplicate Claude_Task_Plan.md heading check main() already does for `head_by_id` below."""
    doc = yaml.safe_load(open(CADENCE, encoding="utf-8")) or {}
    ids = [r["id"] for r in doc.get("routines", [])]
    return sorted({i for i in ids if ids.count(i) > 1})


def parse_expected_sql():
    """{routine: schedule_class} from the STRUCT(... AS routine, ... AS schedule) list in 12_*.sql."""
    txt = open(CADENCE_SQL, encoding="utf-8").read()
    pat = re.compile(r"STRUCT\('([^']+)'\s+AS routine,\s*'([^']+)'\s+AS schedule\)")
    return dict(pat.findall(txt))


def parse_catalog_sql():
    """{routine: canonical_instruction} from 15_*.sql (handles the first AS-labelled row + shorthand rows).

    The instruction literal may contain BigQuery-escaped single quotes (''), emitted by
    scripts/gen_routine_lists.py gen_15_region (_sql_str) when a routine heading contains an
    apostrophe. Match those doubled quotes and un-escape '' -> ' so the parsed value equals check B's
    want_catalog (derived from the RAW heading text). This is the paired half of gen_15_region's
    escaping -- the two MUST stay in lockstep. Byte-identical on a tree with no apostrophe headings."""
    txt = open(CATALOG_SQL, encoding="utf-8").read()
    pat = re.compile(
        r"STRUCT\('([^']+)'(?:\s+AS routine)?,\s*'(Read Claude_Task_Plan\.md\. Perform (?:[^']|'')*)'")
    return {rid: instr.replace("''", "'") for rid, instr in pat.findall(txt)}


def parse_deadline_sql():
    """['HH:MM', ...] from the DATETIME(e.today, TIME 'HH:MM:SS') deadline guard in 12_*.sql (state.cadence_watch)."""
    return SQL_DEADLINE.findall(open(CADENCE_SQL, encoding="utf-8").read())


def cadence_deadline_yaml():
    """Top-level cadence_watch_deadline_local from ops/cadence.yaml (raw value, or None)."""
    doc = yaml.safe_load(open(CADENCE, encoding="utf-8")) or {}
    return doc.get("cadence_watch_deadline_local")


def cadence_period_grace_yaml():
    """Top-level period_grace_days from ops/cadence.yaml (dict, or None)."""
    doc = yaml.safe_load(open(CADENCE, encoding="utf-8")) or {}
    return doc.get("period_grace_days")


def parse_period_grace_sql():
    """{monitor_class: grace_days} from bigquery/24_cadence_period_watch.sql.

    month/quarter/year are OFFSET N (0-indexed -> the (N+1)th trading day); weekly is a plain
    calendar-day count already expressed the same way period_grace_days.weekly_sun is (1 = Monday).
    Returns None if the file is absent (pre-2026-07-03 checkout) so the caller can skip check E.
    """
    if not os.path.exists(PERIOD_WATCH_SQL):
        return None
    txt = open(PERIOD_WATCH_SQL, encoding="utf-8").read()
    out = {}
    for offset, which in PERIOD_GRACE_OFFSET.findall(txt):
        cls = {"month": "monthly_ftd", "quarter": "quarterly_ftd", "year": "annual_ftd"}[which]
        out[cls] = int(offset) + 1
    m = PERIOD_GRACE_WEEKLY.search(txt)
    if m:
        out["weekly_sun"] = int(m.group(1))
    return out


def parse_period_watch_routines_sql():
    """{routine: monitor_class} from bigquery/24_cadence_period_watch.sql's `routines` CTE
    (check J) — post-normalization (scripts/gen_routine_lists.py --write) every row is fully
    labelled `STRUCT('<id>' AS routine, '<class>' AS monitor_class)`. Returns None if the file is
    absent (pre-feature checkout) so the caller can skip check J, same convention as check E's
    parse_period_grace_sql."""
    if not os.path.exists(PERIOD_WATCH_SQL):
        return None
    txt = open(PERIOD_WATCH_SQL, encoding="utf-8").read()
    return dict(PERIOD_WATCH_ROUTINE_ROW.findall(txt))


def parse_unnest_routine_ids(path):
    """Ids inside a `... UNNEST([ ... ]) AS routine` bracket (check K), `--` line comments stripped
    FIRST so an inline comment naming an id (e.g. "-- SL4 (rev ...)") can never be mistaken for a
    quoted list entry. Returns None if `path` does not exist OR if no such bracket is found. main()
    DISTINGUISHES the two by os.path.exists: a file that is ABSENT skips check K silently (pre-
    feature checkout), but a file that is PRESENT-but-unparseable FAILS check K loudly — otherwise a
    reformat that breaks the regex (`AS  routine`, `UNNEST(ARRAY[...]`) would silently disarm the
    only drift guard bigquery/31 and 59 have (2026-07-17 audit — the same regex-rot vacuous-pass
    class checks A/D/E/J/L already fail loud on by returning an empty container, not None)."""
    if not os.path.exists(path):
        return None
    txt = SQL_LINE_COMMENT.sub("", open(path, encoding="utf-8").read())
    m = UNNEST_ROUTINE_BRACKET.search(txt)
    if m is None:
        return None
    return QUOTED_ID.findall(m.group(1))


def parse_inventory_table(plan_path):
    """[(id, cadence_type_cell), ...] rows from ONLY the ROUTINE INVENTORY section of the plan —
    scoped between the "# ROUTINE INVENTORY & BIGQUERY RESPONSIBILITIES" heading and the NEXT `---`
    divider, so the strategy slice-map table elsewhere in the file (which also has `| **...** |`-
    shaped rows, e.g. `| **AR_attacker** |`) can never leak in (check L). Returns None if the
    heading is not present at all (pre-feature checkout / a minimal test fixture)."""
    txt = open(plan_path, encoding="utf-8").read()
    start = txt.find(INVENTORY_HEADING)
    if start == -1:
        return None
    rest = txt[start + len(INVENTORY_HEADING):]
    end = rest.find("\n---")
    section = rest if end == -1 else rest[:end]
    return INVENTORY_ROW.findall(section)


def generate_triggers_manifest(head_by_id, cad):
    """The canonical {id: {monitor_class, instruction}} map — same shape print_routines.py --write
    emits to ops/triggers.json. Delegates to the shared implementation (scripts/lib/routine_manifest.py)
    so CI verifies the committed file against the SAME code path print_routines.py --write uses,
    not an independently-maintained copy of it."""
    return build_triggers_manifest(list(head_by_id.values()), cad)


def check_depends_on(cad):
    """Error strings for any depends_on entry that is not a known routine id in cad (a dangling/typo'd
    dependency -- it feeds the FATAL ops.sp_assert_deps gate, so a silent typo here would abort a live
    routine at runtime instead of failing this offline check)."""
    errors = []
    for rid, r in cad.items():
        for dep in (r.get("depends_on") or []):
            if dep not in cad:
                errors.append(f"{rid}: depends_on '{dep}' is not a routine id in ops/cadence.yaml "
                              f"(dangling/typo'd dependency — it feeds the FATAL sp_assert_deps gate)")
    return errors


def catchup_list_errors(cad, path, filename, tier_word, classes):
    """Check K for ONE of bigquery/31/59's hand-maintained catchup-safe `UNNEST([...]) AS routine`
    lists: it must equal cadence.yaml's {catchup_safe AND monitor_class in <classes>} subset.

    An ABSENT file is skipped silently (pre-feature checkout); a PRESENT-but-unparseable file FAILS
    loudly (DISARMED) so a benign SQL reformat can never silently disarm the guard. The daily
    (bigquery/31) and period (bigquery/59) call sites differ only in (path, filename, tier_word,
    classes), so this shared helper keeps their two error strings — the observable contract — from
    ever drifting apart with a one-sided edit. Returns a list of error strings (possibly empty)."""
    want = {rid for rid, r in cad.items()
            if r.get("catchup_safe") is True and r.get("monitor_class") in classes}
    have = parse_unnest_routine_ids(path)
    if have is None and os.path.exists(path):
        return [
            f"{filename} exists but no `UNNEST([...]) AS routine` bracket could be "
            f"parsed — check K's catchup-safe {tier_word} drift guard is DISARMED (regex rot? e.g. a "
            f"reformat to `AS  routine` or `UNNEST(ARRAY[...]`). Restore a parseable bracket."]
    if have is not None:
        have_set = set(have)
        if have_set != want:
            return [
                f"{filename} catchup-safe {tier_word} UNNEST list DRIFT — "
                f"file has {sorted(have_set)}, cadence.yaml-derived (catchup_safe AND {tier_word} tier) "
                f"wants {sorted(want)}"]
    return []


def main():
    cad = load_cadence()
    headings = plan_headings()
    errors = []

    # ---- duplicate routine id in ops/cadence.yaml's routines list (silently collapsed by
    # load_cadence()'s dict comprehension otherwise -- see cadence_duplicate_ids()'s docstring) ----
    for rid in cadence_duplicate_ids():
        errors.append(f"ops/cadence.yaml: duplicate routine id '{rid}' — each routine id must "
                      f"appear exactly once")

    # ---- canonical maps from the SOURCE OF TRUTH (cadence.yaml + the plan) ----
    head_by_id, dup = {}, []
    for h in headings:
        rid = heading_to_id(h)
        if rid is None:
            errors.append(f"plan heading does not map to a routine id (bad format?): '{h}'")
            continue
        if rid in head_by_id:
            dup.append(rid)
        head_by_id[rid] = h
    for rid in dup:
        errors.append(f"duplicate Claude_Task_Plan.md heading for id {rid}")

    # check B must derive its expectation from the SAME shared template check F uses (lib/
    # routine_manifest.instruction_text) rather than re-literalizing the f-string here -- that literal
    # was the 4th independent copy the 2026-07-20 extraction was supposed to kill (codebase audit
    # 2026-07-26): edit instruction_text's wording and regenerate bigquery/15 via gen_routine_lists.py
    # --write, and this hardcoded copy would silently compute the OLD string, failing CI for every
    # routine with a diff that points at cadence.yaml/plan headings instead of the real culprit.
    want_catalog = {rid: instruction_text(h) for rid, h in head_by_id.items()}
    want_expected = {rid: r["monitor_class"] for rid, r in cad.items()
                     if r.get("monitor_class") in CALENDAR_CLASSES}

    # ---- validate monitor_class presence + vocabulary ----
    for rid, r in cad.items():
        mc = r.get("monitor_class")
        if mc is None:
            errors.append(f"{rid}: missing monitor_class in ops/cadence.yaml")
        elif mc not in ALLOWED_CLASSES:
            errors.append(f"{rid}: monitor_class '{mc}' not in {sorted(ALLOWED_CLASSES)}")

    # ---- depends_on references must be known routine ids (silent-drift guard) ----
    errors.extend(check_depends_on(cad))

    # ---- C. cadence.yaml id <-> plan heading 1:1 ----
    for rid in cad:
        if rid not in head_by_id:
            errors.append(f"{rid}: in ops/cadence.yaml but no matching Claude_Task_Plan.md heading")
    for rid in head_by_id:
        if rid not in cad:
            errors.append(f"{rid}: Claude_Task_Plan.md heading but no ops/cadence.yaml routine")

    # ---- A. state.cadence_expected_today (12_*.sql) == calendar-class routines in cadence.yaml ----
    have_expected = parse_expected_sql()
    if not have_expected:
        errors.append("could not parse any STRUCT(... AS schedule) rows from 12_cadence_monitor.sql")
    for rid, cls in want_expected.items():
        if rid not in have_expected:
            errors.append(f"{rid}: monitor_class={cls} in cadence.yaml but MISSING from "
                          f"state.cadence_expected_today (12_cadence_monitor.sql)")
        elif have_expected[rid] != cls:
            errors.append(f"{rid}: schedule class mismatch — cadence.yaml='{cls}' vs "
                          f"12_cadence_monitor.sql='{have_expected[rid]}'")
    for rid in have_expected:
        if rid not in want_expected:
            errors.append(f"{rid}: in state.cadence_expected_today (12_*.sql) but not a calendar-class "
                          f"routine in cadence.yaml (queue_driven/unknown routines must NOT be listed)")

    # ---- B. ops.routine_catalog (15_*.sql) == plan-heading-derived instruction ----
    have_catalog = parse_catalog_sql()
    if not have_catalog:
        errors.append("could not parse any catalog STRUCT rows from 15_routine_catalog.sql")
    for rid, instr in want_catalog.items():
        if rid not in have_catalog:
            errors.append(f"{rid}: has a plan heading but is MISSING from ops.routine_catalog (15_*.sql)")
        elif have_catalog[rid] != instr:
            errors.append(f"{rid}: routine_catalog instruction drift\n"
                          f"     plan-derived: {instr}\n"
                          f"     15_*.sql:     {have_catalog[rid]}")
    for rid in have_catalog:
        if rid not in want_catalog:
            errors.append(f"{rid}: in ops.routine_catalog (15_*.sql) but has no Claude_Task_Plan.md heading")

    # ---- D. cadence_watch deadline guard: cadence.yaml constant == bigquery/12 SQL TIME literal ----
    want_deadline = cadence_deadline_yaml()
    have_deadlines = parse_deadline_sql()
    deadline_ok = True
    if want_deadline is None:
        errors.append("ops/cadence.yaml: missing top-level 'cadence_watch_deadline_local' "
                      "(declares the state.cadence_watch deadline-guard time)")
        deadline_ok = False
    elif not (isinstance(want_deadline, str) and HHMM.match(want_deadline)):
        errors.append(f"ops/cadence.yaml: cadence_watch_deadline_local must be a quoted \"HH:MM\" string "
                      f"(got {want_deadline!r} — an UNquoted 21:00 is YAML base-60 = 1260; always quote it)")
        deadline_ok = False
    if not have_deadlines:
        errors.append("bigquery/12_cadence_monitor.sql: could not parse the DATETIME(e.today, TIME '..') "
                      "deadline-guard literal from state.cadence_watch (did the clause change shape?)")
        deadline_ok = False
    elif len(set(have_deadlines)) > 1:
        errors.append(f"bigquery/12_cadence_monitor.sql: multiple distinct deadline literals "
                      f"{sorted(set(have_deadlines))} in state.cadence_watch — expected exactly one")
        deadline_ok = False
    if deadline_ok and have_deadlines[0] != want_deadline:
        errors.append(f"cadence_watch deadline DRIFT — ops/cadence.yaml='{want_deadline}' vs "
                      f"bigquery/12_cadence_monitor.sql TIME='{have_deadlines[0]}'. Keep them in sync.")

    # ---- E. period_grace_days: cadence.yaml == bigquery/24_cadence_period_watch.sql ----
    want_grace = cadence_period_grace_yaml()
    have_grace = parse_period_grace_sql()
    if have_grace is not None:  # file present; if absent, this repo predates the feature — skip silently
        if want_grace is None:
            errors.append("ops/cadence.yaml: missing top-level 'period_grace_days' "
                          "(bigquery/24_cadence_period_watch.sql exists and needs a declared source of truth)")
        else:
            for cls in ("weekly_sun", "monthly_ftd", "quarterly_ftd", "annual_ftd"):
                y, s = want_grace.get(cls), have_grace.get(cls)
                if y is None:
                    errors.append(f"ops/cadence.yaml period_grace_days: missing '{cls}'")
                elif s is None:
                    errors.append(f"bigquery/24_cadence_period_watch.sql: could not parse a grace literal for '{cls}'")
                elif y != s:
                    errors.append(f"period_grace_days DRIFT for {cls} — ops/cadence.yaml={y} vs "
                                  f"bigquery/24_cadence_period_watch.sql={s}. Keep them in sync.")

    # ---- J. state.cadence_period_watch's `routines` CTE (24_*.sql) == period-class routines in
    # cadence.yaml (ARCH-3 Item 30b) — the GENERATED counterpart to check A, for the period-tier list. ----
    want_period_routines = {rid: r["monitor_class"] for rid, r in cad.items()
                             if r.get("monitor_class") in PERIOD_CLASSES}
    have_period_routines = parse_period_watch_routines_sql()
    if have_period_routines is not None:  # file present; absent = pre-feature checkout, skip silently
        if not have_period_routines:
            errors.append("could not parse any labelled STRUCT(... AS monitor_class) rows from "
                          "24_cadence_period_watch.sql's `routines` CTE")
        for rid, cls in want_period_routines.items():
            if rid not in have_period_routines:
                errors.append(f"{rid}: monitor_class={cls} in cadence.yaml but MISSING from "
                              f"state.cadence_period_watch's routines CTE (24_cadence_period_watch.sql)")
            elif have_period_routines[rid] != cls:
                errors.append(f"{rid}: period-watch monitor_class mismatch — cadence.yaml='{cls}' vs "
                              f"24_cadence_period_watch.sql='{have_period_routines[rid]}'")
        for rid in have_period_routines:
            if rid not in want_period_routines:
                errors.append(f"{rid}: in state.cadence_period_watch's routines CTE (24_*.sql) but not "
                              f"a period-class routine in cadence.yaml")

    # ---- K. catchup_safe: every cadence.yaml routine must declare the boolean, and bigquery/31/59's
    # hand-maintained UNNEST id lists must equal the corresponding {catchup_safe AND monitor_class in
    # <tier>} subset (ARCH-3 Item 30b — these two lists previously had ZERO drift protection). ----
    for rid, r in cad.items():
        if "catchup_safe" not in r:
            errors.append(f"{rid}: missing catchup_safe boolean in ops/cadence.yaml")
        elif not isinstance(r["catchup_safe"], bool):
            errors.append(f"{rid}: catchup_safe must be a boolean true/false (got {r['catchup_safe']!r})")

    errors.extend(catchup_list_errors(
        cad, CATCHUP_NOTIFY_SQL, "bigquery/31_catchup_notify.sql", "daily", DAILY_CLASSES))
    errors.extend(catchup_list_errors(
        cad, CATCHUP_AUTOFIRE_SQL, "bigquery/59_catchup_autofire.sql", "period", PERIOD_CLASSES))

    # ---- L. Claude_Task_Plan.md's ROUTINE INVENTORY table == cadence.yaml ids, and each row's
    # 'Cadence · Type' cell agrees with that routine's monitor_class (ARCH-3 Item 30b). ----
    have_inventory = parse_inventory_table(PLAN)
    if have_inventory is not None:  # heading present; absent = pre-feature checkout, skip silently
        have_inventory_ids = {rid for rid, _cell in have_inventory}
        for rid in sorted(set(cad) - have_inventory_ids):
            errors.append(f"{rid}: in ops/cadence.yaml but missing a row in Claude_Task_Plan.md's "
                          f"ROUTINE INVENTORY table")
        for rid in sorted(have_inventory_ids - set(cad)):
            errors.append(f"{rid}: ROUTINE INVENTORY table row has no matching ops/cadence.yaml routine")
        for rid, cell in have_inventory:
            if rid not in cad:
                continue
            mc = cad[rid].get("monitor_class")
            token = cell.strip().split()[0] if cell.strip() else ""
            if rid in INVENTORY_FOOTNOTE_QUEUE_DRIVEN_IDS and token.rstrip("¹") == "Daily" and token.endswith("¹"):
                allowed = {"queue_driven"}
            else:
                allowed = INVENTORY_CADENCE_TOKEN_MAP.get(token)
            if allowed is None:
                errors.append(f"{rid}: ROUTINE INVENTORY 'Cadence · Type' cell first token '{token}' "
                              f"not recognized (Daily/Weekly/Monthly/Quarterly/Annual/Queue-driven)")
            elif mc not in allowed:
                errors.append(f"{rid}: ROUTINE INVENTORY cadence cell '{token}' implies monitor_class in "
                              f"{sorted(allowed)}, but ops/cadence.yaml has monitor_class='{mc}'")

    # ---- F. ops/triggers.json (if present) == the canonical generated map ----
    if os.path.exists(TRIGGERS_JSON):
        want_manifest = generate_triggers_manifest(head_by_id, cad)
        try:
            have_manifest = json.load(open(TRIGGERS_JSON, encoding="utf-8"))
        except (OSError, ValueError) as e:
            errors.append(f"ops/triggers.json: could not parse as JSON ({e})")
            have_manifest = None
        if have_manifest is not None and have_manifest != want_manifest:
            errors.append("ops/triggers.json is STALE — does not match the canonical map derived from "
                          "ops/cadence.yaml + Claude_Task_Plan.md headings. Regenerate with "
                          "`python scripts/print_routines.py --write` and commit the result "
                          "(it must be GENERATED, never hand-edited).")

    # ---- G. ops/trigger_ids.json (if present): unique trigger_ids, no entry for a routine no
    # longer in cadence.yaml (self-improvement audit, 2026-07-14 — this file had zero CI
    # validation despite being nearly identical in shape/purpose to ops/triggers.json). A cad
    # routine with NO entry yet is expected/transient (recorded once its live trigger is created)
    # and is a WARN, not a build failure. ----
    if os.path.exists(TRIGGER_IDS_JSON):
        try:
            trigger_ids_doc = json.load(open(TRIGGER_IDS_JSON, encoding="utf-8"))
        except (OSError, ValueError) as e:
            errors.append(f"ops/trigger_ids.json: could not parse as JSON ({e})")
            trigger_ids_doc = None
        if trigger_ids_doc is not None:
            have_ids = {k: v for k, v in trigger_ids_doc.items() if k != "_meta"}
            by_trigger = {}
            for rid, entry in have_ids.items():
                tid = (entry or {}).get("trigger_id")
                by_trigger.setdefault(tid, []).append(rid)
            for tid, rids in by_trigger.items():
                if tid and len(rids) > 1:
                    errors.append(f"ops/trigger_ids.json: trigger_id '{tid}' is shared by routines "
                                  f"{sorted(rids)} — duplicate/typo'd id would misdirect a live "
                                  f"RemoteTrigger call")
            stale = sorted(rid for rid in have_ids if rid not in cad)
            if stale:
                errors.append(f"ops/trigger_ids.json: entries for routine(s) no longer in "
                              f"ops/cadence.yaml: {stale} — remove the stale entry")
            missing = sorted(rid for rid in cad if rid not in have_ids)
            if missing:
                print(f"NOTE: ops/trigger_ids.json has no entry yet for {missing} (new routine — "
                      f"record its live trigger id once created via RemoteTrigger/Chrome; not a "
                      f"CI failure, per the file's own not-live-synced caveat).")

            # ---- I. expected_trigger: every routine WITH an ops/trigger_ids.json entry must carry a
            # well-formed `expected_trigger` in ops/cadence.yaml (trigger-config-drift audit, 2026-07-16,
            # ARCH-2/CC-5 merge). This is the structured, mechanically-diffable schedule Q4 step E and
            # OPS0 STEP 3 diff a live RemoteTrigger get() against, replacing the old free-text
            # WEB-UI TRIGGER AUDIT comment block as the enforced source of truth. A routine with NO
            # trigger_ids.json entry yet (OPS0, until its live trigger is created) is a NOTE only,
            # mirroring the NOTE just above — not a build failure. ----
            EXPECTED_TRIGGER_RECURRENCE = {"daily", "weekly", "custom_cron"}
            for rid in sorted(cad):
                et = cad[rid].get("expected_trigger")
                if rid not in have_ids:
                    if et is None:
                        print(f"NOTE: {rid} has no expected_trigger yet (no live trigger id recorded "
                              f"either — expected until ops/trigger_ids.json gets an entry for it).")
                    continue
                if et is None:
                    errors.append(f"{rid}: has an ops/trigger_ids.json entry but no 'expected_trigger' "
                                  f"in ops/cadence.yaml (structured schedule required for the "
                                  f"RemoteTrigger-diff self-heal sweep — Q4 step E / OPS0 STEP 3)")
                    continue
                rec = et.get("recurrence")
                if rec not in EXPECTED_TRIGGER_RECURRENCE:
                    errors.append(f"{rid}: expected_trigger.recurrence={rec!r} not in "
                                  f"{sorted(EXPECTED_TRIGGER_RECURRENCE)}")
                    continue
                if "enabled" not in et:
                    errors.append(f"{rid}: expected_trigger missing 'enabled'")
                if rec in ("daily", "weekly"):
                    tl = et.get("time_local")
                    if not (isinstance(tl, str) and HHMM.match(tl)):
                        errors.append(f"{rid}: expected_trigger.time_local must be a quoted \"HH:MM\" "
                                      f"string for recurrence={rec} (got {tl!r} — an unquoted HH:MM is "
                                      f"YAML base-60, same caveat as cadence_watch_deadline_local)")
                elif rec == "custom_cron":
                    cu = et.get("cron_utc")
                    if not (isinstance(cu, str) and cu.strip()):
                        errors.append(f"{rid}: expected_trigger.cron_utc must be a non-empty string "
                                      f"(TO_POPULATE bootstrap placeholder, or an observed cron once a "
                                      f"sweep has populated it) for recurrence=custom_cron")

    # ---- H. auto-merge-claude.yml's RUNBOOK §38 marker-write routine_re must accept every
    # cadence.yaml id (self-improvement audit, 2026-07-14) — this hand-typed alternation is a
    # second copy of the routine-id set already carried by ops/cadence.yaml, with no guard: a
    # routine added to cadence.yaml but not to this regex has its commits silently skipped by the
    # §38 marker-write self-heal, with no CI signal. Only checks the cadence-ids-subset-of-regex
    # direction (under-inclusive/silent-skip) — the regex being a superset is harmless. ----
    if os.path.exists(AUTO_MERGE_YML):
        txt = open(AUTO_MERGE_YML, encoding="utf-8").read()
        m = AUTO_MERGE_ROUTINE_RE.search(txt)
        if m is None:
            errors.append("could not find routine_re='^(...)$' in .github/workflows/auto-merge-claude.yml "
                          "— the RUNBOOK §38 marker-write allowlist literal may have changed shape; "
                          "update AUTO_MERGE_ROUTINE_RE in this script to match")
        else:
            routine_re_pat = re.compile(f"^(?:{m.group(1)})$")
            for rid in cad:
                if not routine_re_pat.fullmatch(rid):
                    errors.append(f"{rid}: in ops/cadence.yaml but NOT matched by "
                                  f"auto-merge-claude.yml's routine_re — RUNBOOK §38 marker-write "
                                  f"will silently skip this routine's commits (add it to the "
                                  f"routine_re alternation on the marker-write line)")

    # ---- M. EVENING-slot daily SAME-DAY guard copies carry the noon-threshold clause (H1). ----
    # Gated on the "SAME-DAY DOUBLE-RUN GUARD" sentinel being present at all, so a minimal test fixture
    # / pre-feature checkout of Claude_Task_Plan.md skips silently — same convention as check L
    # (parse_inventory_table returns None when the ROUTINE INVENTORY heading is absent).
    plan_txt = open(PLAN, encoding="utf-8").read()
    if "SAME-DAY DOUBLE-RUN GUARD" in plan_txt:
        for rid in EVENING_DAILY_GUARD_IDS:
            matches = list(GUARD_QUERY_RE[rid].finditer(plan_txt))
            if not matches:
                errors.append(f"{rid}: could not find its SAME-DAY DOUBLE-RUN GUARD `ops.run_log` "
                              f"COUNT(*) query in Claude_Task_Plan.md — check M's H1 noon-threshold guard "
                              f"is DISARMED for this routine (did the guard query change shape?)")
                continue
            for m in matches:
                if not GUARD_NOON_CLAUSE_RE.search(m.group("after")):
                    errors.append(
                        f"{rid}: SAME-DAY DOUBLE-RUN GUARD copy is MISSING the noon-threshold clause "
                        f"(H1) — an EVENING-slot daily routine (slot >= 16:00 MT) must count only "
                        f"completions in the real evening window: append "
                        f"`AND DATETIME(log_ts,'America/Denver') >= DATETIME(<today, America/Denver>, "
                        f"TIME '12:00:00')` to its `status='completed'` COUNT(*) query, so a post-midnight "
                        f"prior-day run mis-stamped onto today by bigquery/12's midnight-crossing grace "
                        f"cannot cancel the genuine evening run (see the shared Observability guard's "
                        f"CYCLE-AWARE VARIANT).")

    # ---- report ----
    if errors:
        print("CADENCE CONSISTENCY: FAIL\n")
        for e in errors:
            print(" - " + e)
        print("\nFix ops/cadence.yaml (monitor_class) / Claude_Task_Plan.md headings and the matching "
              "bigquery/12_cadence_monitor.sql + bigquery/15_routine_catalog.sql so all three agree, "
              "then re-run. (See ops/cadence.yaml header + scripts/print_routines.py.)")
        return 1

    extra = ""
    if have_grace is not None:
        extra += " period_grace_days matches 24_cadence_period_watch.sql."
    if os.path.exists(TRIGGERS_JSON):
        extra += " ops/triggers.json is current."
    print(f"CADENCE CONSISTENCY: OK — {len(cad)} routines; "
          f"{len(want_expected)} calendar-class match state.cadence_expected_today; "
          f"{len(have_catalog)} catalog entries match the plan headings; "
          f"cadence_watch deadline {want_deadline} matches 12_cadence_monitor.sql.{extra}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
