#!/usr/bin/env python3
"""Print every routine's trigger instruction + cadence — no web-UI screenshots needed.

The Claude-Code-on-Web triggers (schedule + instruction) live ONLY in the web UI and are not
readable from a session (see ops/cadence.yaml header). But they are deterministic: each trigger's
instruction is exactly

    Read Claude_Task_Plan.md. Perform <routine heading>.

and the cadence is mirrored in ops/cadence.yaml. This script reconstructs the canonical list from
those two repo files, so you get one printout to review, to diff against the web UI, or to use when
(re)creating triggers — instead of opening each routine and screenshotting it.

It also cross-checks that every ops/cadence.yaml routine has a matching Claude_Task_Plan.md heading
(and vice-versa), so a drift between the two surfaces here.

EXACT CLOCK TIMES live only in the web UI; ops/cadence.yaml carries the cadence-level schedule
(e.g. "after_close trading_day", "weekly Sun", "monthly first_trading_day"). Record exact times in
cadence.yaml if you want them printed.

VERIFYING THE LIVE TRIGGERS (no screenshots): once routines record the verbatim instruction they
received (ops.run_log.instruction, set by ops.sp_routine_start), run
    SELECT * FROM `stock-trading-498512.state.routine_last_instruction`;
to see the ACTUAL trigger text each routine last received, and diff it against THIS script's canonical
output — any mismatch is a drifted/typo'd web-UI trigger. That check is reactive (only catches drift
after a routine fires) and text-only (no schedule/cron). For a live, on-demand, full check (schedule +
instruction + enabled status), a session can call the RemoteTrigger tool directly — see
ops/trigger_ids.json for the routine id -> live trigger id map (added 2026-07-12, so a session doesn't
have to re-discover IDs via Claude-in-Chrome each time; `list`'s pagination is broken in-session, capped
at ~20 of 31+ routines, which is why that file exists).

VERSIONED TRIGGER MANIFEST (--write, added 2026-07-03, self-improvement audit WO-2). The web-UI
trigger config is the one SPOF this repo can only detect drift in, never set or restore from code —
today a deleted low-frequency trigger is invisible for up to a full cadence window. `--write` emits
ops/triggers.json, the same canonical {id -> monitor_class, instruction} map this script prints, as a
committed, diffable artifact: a deleted/edited trigger is now a `git diff`-visible change the next time
this is regenerated, and the restore procedure is "read this file" instead of re-deriving it from two
source docs by hand. This file MUST be GENERATED by this script, never hand-edited — CI
(scripts/check_cadence_consistency.py check F) fails the build if it drifts from the canonical map.

Usage:  python scripts/print_routines.py
        python scripts/print_routines.py --write   # also (re)writes ops/triggers.json
"""
import json
import os
import sys

try:
    # this module's own read now goes through lib.textio.load_yaml() (2026-07-29 textio
    # adoption), so `yaml` is no longer referenced directly here, but the import stays for this
    # fail-fast ImportError guard (a clear "pip install pyyaml" message beats textio.py's own bare
    # ImportError traceback).
    import yaml  # noqa: F401
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    raise SystemExit(2) from None

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib.routine_manifest import (
    build_triggers_manifest,
    cadence_routines,
    heading_to_id,
    instruction_text,
    parse_routine_headings,
)
from lib.textio import load_yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLAN = os.path.join(ROOT, "Claude_Task_Plan.md")
CADENCE = os.path.join(ROOT, "ops", "cadence.yaml")
TRIGGERS_JSON = os.path.join(ROOT, "ops", "triggers.json")


def routine_headings():
    """Ordered list of routine section headings from Claude_Task_Plan.md (shared parser — see
    scripts/lib/routine_manifest.py; this used to be an independent copy of
    scripts/check_cadence_consistency.py's identical logic, 2026-07-14 audit finding)."""
    return parse_routine_headings(PLAN)


def load_cadence():
    doc = load_yaml(CADENCE)
    sched = {r["id"]: r for r in cadence_routines(doc)}
    return doc.get("timezone", "?"), sched


def main():
    headings = routine_headings()
    tz, cad = load_cadence()
    seen_ids = []

    print("Routine triggers — instruction is `Read Claude_Task_Plan.md. Perform <heading>.`")
    print(f"Cadence timezone: {tz}  (exact clock times are in the web UI only)\n")
    print("=" * 100)
    for h in headings:
        rid = heading_to_id(h) or "?"
        seen_ids.append(rid)
        r = cad.get(rid, {})
        deps = ", ".join(r.get("depends_on") or []) or "—"
        print(f"{rid}   cadence: {r.get('schedule', '(not in cadence.yaml)')}   deps: {deps}")
        print(f"   instruction: {instruction_text(h)}")
        print()
    print("=" * 100)
    print(f"{len(headings)} routines.")
    seen = set(seen_ids)

    # Drift check both directions.
    missing_heading = [cid for cid in cad if cid not in seen]
    if missing_heading:
        print("WARNING: in cadence.yaml but no matching Claude_Task_Plan heading: "
              + ", ".join(missing_heading))
    # Reverse direction: a well-formed heading id with no matching ops/cadence.yaml routine at all
    # (the docstring promises this check "and vice-versa" but it was never implemented — 2026-07-18
    # audit finding; missing_heading above only ever caught cadence-id -> heading drift).
    missing_cadence = sorted({rid for rid in seen if rid != "?" and rid not in cad})
    if missing_cadence:
        print("WARNING: Claude_Task_Plan.md heading(s) with no matching ops/cadence.yaml routine: "
              + ", ".join(missing_cadence))
    if "?" in seen:
        print("WARNING: a routine heading did not map to a cadence id (check heading format).")
    # A set discards duplicates, so two DIFFERENT headings mapping to the SAME id (a copy-pasted
    # heading, or two ids colliding after a typo) previously looked identical to the clean
    # single-heading case here, printing a false "OK: ... maps 1:1" (2026-07-14 audit finding;
    # the real CI gate, scripts/check_cadence_consistency.py, already catches this — this fixes
    # the hand-run tool's own self-check message, which was factually wrong in this case).
    dup_ids = sorted({rid for rid in seen if rid != "?" and seen_ids.count(rid) > 1})
    if dup_ids:
        print("WARNING: multiple Claude_Task_Plan.md headings map to the same routine id (not 1:1): "
              + ", ".join(dup_ids))
    if not missing_heading and not missing_cadence and "?" not in seen and not dup_ids:
        print("OK: every routine heading maps 1:1 to an ops/cadence.yaml routine.")

    if "--write" in sys.argv:
        manifest = build_triggers_manifest(headings, cad)
        # ensure_ascii=False (2026-08-17 fix): json.dump's default (True) \u-escapes every em dash in
        # every instruction, so re-running --write on an UNCHANGED cadence.yaml/plan turned all 32
        # entries into diff noise against the already-committed file (which carries literal UTF-8 em
        # dashes) -- discovered while regenerating for the new OPS2 instruction_note field and verifying
        # "only OPS2 changed" via a before/after diff, which this drift defeated even though the parsed
        # JSON (what check_cadence_consistency.py's check F actually compares) was byte-for-byte
        # unaffected. Matches the checked-in file's existing convention.
        with open(TRIGGERS_JSON, "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2, sort_keys=True, ensure_ascii=False)
            f.write("\n")
        print(f"\nWrote {TRIGGERS_JSON} ({len(manifest)} routines).")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
