#!/usr/bin/env python3
"""Print every routine's trigger instruction + cadence — no web-UI screenshots needed.

The Claude-Code-on-Web triggers (schedule + instruction) live ONLY in the web UI and are not
readable from a session (see ops/cadence.yaml header). But they are deterministic: each trigger's
instruction is exactly

    Read Claude_Task_Plan.md. Perform <routine heading>.

and the cadence is mirrored in ops/cadence.yaml. This script reconstructs the canonical list from
those two repo files, so you get one printout to review, to diff against the web UI, or to use when
(re)creating triggers — instead of opening each routine and screenshotting it.

It also cross-checks that every ops/cadence.yaml routine has a matching Claude_Task_Plan.md heading
(and vice-versa), so a drift between the two surfaces here.

EXACT CLOCK TIMES live only in the web UI; ops/cadence.yaml carries the cadence-level schedule
(e.g. "after_close trading_day", "weekly Sun", "monthly first_trading_day"). Record exact times in
cadence.yaml if you want them printed.

VERIFYING THE LIVE TRIGGERS (no screenshots): once routines record the verbatim instruction they
received (ops.run_log.instruction, set by ops.sp_routine_start), run
    SELECT * FROM `stock-trading-498512.state.routine_last_instruction`;
to see the ACTUAL trigger text each routine last received, and diff it against THIS script's canonical
output — any mismatch is a drifted/typo'd web-UI trigger. That check is reactive (only catches drift
after a routine fires) and text-only (no schedule/cron). For a live, on-demand, full check (schedule +
instruction + enabled status), a session can call the RemoteTrigger tool directly — see
ops/trigger_ids.json for the routine id -> live trigger id map (added 2026-07-12, so a session doesn't
have to re-discover IDs via Claude-in-Chrome each time; `list`'s pagination is broken in-session, capped
at ~20 of 31+ routines, which is why that file exists).

VERSIONED TRIGGER MANIFEST (--write, added 2026-07-03, self-improvement audit WO-2). The web-UI
trigger config is the one SPOF this repo can only detect drift in, never set or restore from code —
today a deleted low-frequency trigger is invisible for up to a full cadence window. `--write` emits
ops/triggers.json, the same canonical {id -> monitor_class, instruction} map this script prints, as a
committed, diffable artifact: a deleted/edited trigger is now a `git diff`-visible change the next time
this is regenerated, and the restore procedure is "read this file" instead of re-deriving it from two
source docs by hand. This file MUST be GENERATED by this script, never hand-edited — CI
(scripts/check_cadence_consistency.py check F) fails the build if it drifts from the canonical map.

Usage:  python scripts/print_routines.py
        python scripts/print_routines.py --write   # also (re)writes ops/triggers.json
"""
import json
import os
import re
import sys

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    raise SystemExit(2)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLAN = os.path.join(ROOT, "Claude_Task_Plan.md")
CADENCE = os.path.join(ROOT, "ops", "cadence.yaml")
TRIGGERS_JSON = os.path.join(ROOT, "ops", "triggers.json")

# A routine section heading ends with its type tag; this excludes preamble/queue-schema headings.
ROUTINE_SUFFIX = re.compile(r"—\s*(deep research|regular routine)\s*$")


def routine_headings():
    """Ordered list of routine section headings from Claude_Task_Plan.md."""
    out = []
    with open(PLAN, encoding="utf-8") as f:
        for ln in f:
            if ln.startswith("## "):
                h = ln[3:].strip()
                if ROUTINE_SUFFIX.search(h):
                    out.append(h)
    return out


def heading_to_id(h):
    """Map a heading to its ops/cadence.yaml id."""
    m = re.match(r"([A-Za-z0-9]+)\.\s", h)   # "D1. ...", "M1a. ...", "Q4. ..."
    if m:
        return m.group(1)
    if "Attacker" in h:
        return "AR_att"
    if "Orchestrator" in h:
        return "AR_orc"
    return None


def load_cadence():
    doc = yaml.safe_load(open(CADENCE, encoding="utf-8")) or {}
    sched = {r["id"]: r for r in doc.get("routines", [])}
    return doc.get("timezone", "?"), sched


def main():
    headings = routine_headings()
    tz, cad = load_cadence()
    seen = set()

    print("Routine triggers — instruction is `Read Claude_Task_Plan.md. Perform <heading>.`")
    print(f"Cadence timezone: {tz}  (exact clock times are in the web UI only)\n")
    print("=" * 100)
    for h in headings:
        rid = heading_to_id(h) or "?"
        seen.add(rid)
        r = cad.get(rid, {})
        deps = ", ".join(r.get("depends_on") or []) or "—"
        print(f"{rid}   cadence: {r.get('schedule', '(not in cadence.yaml)')}   deps: {deps}")
        print(f"   instruction: Read Claude_Task_Plan.md. Perform {h}.")
        print()
    print("=" * 100)
    print(f"{len(headings)} routines.")

    # Drift check both directions.
    missing_heading = [cid for cid in cad if cid not in seen]
    if missing_heading:
        print("WARNING: in cadence.yaml but no matching Claude_Task_Plan heading: "
              + ", ".join(missing_heading))
    if "?" in seen:
        print("WARNING: a routine heading did not map to a cadence id (check heading format).")
    if not missing_heading and "?" not in seen:
        print("OK: every routine heading maps 1:1 to an ops/cadence.yaml routine.")

    if "--write" in sys.argv:
        manifest = {
            rid: {
                "monitor_class": cad.get(rid, {}).get("monitor_class"),
                "instruction": f"Read Claude_Task_Plan.md. Perform {h}.",
            }
            for h in headings
            for rid in [heading_to_id(h)]
            if rid in cad
        }
        with open(TRIGGERS_JSON, "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2, sort_keys=True)
            f.write("\n")
        print(f"\nWrote {TRIGGERS_JSON} ({len(manifest)} routines).")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
