-- SCHEDULED QUERY (P2-1): back up the entire append-only event store to GCS — NO Cloud Run job,
-- NO downloadable key. Runs as the scheduled query's own identity straight from BigQuery.
--
-- Exports every base table in `events` to gs://stock-trading-backups/events/<table>/dt=<date>/ as
-- Snappy Parquet. overwrite=true makes a same-day re-run idempotent; the bucket's >400d lifecycle
-- ages old snapshots out.
--
-- TWO robustness details (learned from the first live run):
--  (1) Parquet cannot serialize BigQuery's native JSON type ("Type JSON is not currently supported
--      for parquet" — and a dry-run does NOT catch this, since it never serializes). So each table's
--      JSON columns are emitted with TO_JSON_STRING(...) — lossless, round-trippable via PARSE_JSON
--      on restore. The column list is built per-table from INFORMATION_SCHEMA.COLUMNS, so it stays
--      correct as columns/tables change. (JSON cols today: adversarial_reviews.weaknesses,
--      decision_log.fields, position_events.invalidation_status, queue_events.payload, trade_fills.raw.)
--  (2) Each table's export is isolated in its own BEGIN/EXCEPTION, so one failing table can't abort
--      the rest of the run. Failures are collected, written to ops.alerts, and re-raised at the end
--      so the scheduled query's "email on failure" still fires.
--
-- ONE-TIME SETUP (ops/RUNBOOK.md §3): create as a daily scheduled query (~05:30 UTC, Location US,
-- no destination table) under the OWNER's own credentials — the owner already owns the bucket, so
-- no IAM grant is needed. (A dedicated SA would instead need roles/storage.objectAdmin on the bucket.)
--
-- Restore a table (JSON columns come back as STRING):
--   bq load --source_format=PARQUET --replace events_restore.<table> \
--     'gs://stock-trading-backups/events/<table>/dt=<YYYY-MM-DD>/*.parquet'
--   -- for tables with JSON cols, re-parse: SELECT * REPLACE(SAFE.PARSE_JSON(<col>) AS <col>) ...
--
-- BODY FROZEN 2026-07-16: real body lives in ops.sp_sq_backup_events_export (bigquery/75_scheduled_query_wrappers.sql);
-- edit THERE + CREATE OR REPLACE via the BigQuery MCP — this console body never changes again.
-- SQ_NAME: backup_events_export
-- SQ_VERSION: (moved into the procedure — see bigquery/75_scheduled_query_wrappers.sql)
CALL `stock-trading-498512.ops.sp_sq_backup_events_export`();
