-- SCHEDULED QUERY (fix A3 + 2026-06-22 automation-health additions): the cadence / control-plane
-- dead-man's switch. Complements daily_freshness_check.sql (which catches a stale ENGINE / D2 data work).
-- This one catches the things that "ran or didn't" rather than "data is current":
--   * missed_run            — a MONITORED routine expected today logged no 'completed' run (state.cadence_watch)
--   * backup_stale          — the events.* GCS backup has gone silent (state.backup_health; 16_automation_health.sql)
--   * automation_heartbeat  — an out-of-band Apps Script (alert_emailer / weekly_report) went silent (state.automation_heartbeat)
--   * instruction_drift     — a routine's live web-UI trigger differs from the canonical catalog (state.instruction_drift; W2)
--
-- SELF-BOOTSTRAPPING (see bigquery/12 + 16): every signal here only fires once a routine/backup/script has
-- demonstrably started logging, so this never false-alarms on something not yet adopted.
--
-- RECORD-THEN-RAISE: every condition writes a durable, idempotent ops.alerts row FIRST (so no condition
-- masks another), then a SINGLE consolidated RAISE at the end fires BigQuery's built-in "Send email
-- notifications on failure" — an identity-independent channel that delivers even when the thing that
-- failed is the alert emailer itself. instruction_drift is a config bug to FIX, not a halt, so it records
-- a warning but does NOT contribute to the RAISE (matching the prior behaviour).
--
-- TIMING: BigQuery schedules are UTC. Run ~05:15 UTC (= 23:15 MDT / 22:15 MST) — same Denver evening,
-- (CORRECTED 2026-08-03, W5: this line previously read "≈ 22:45 MDT / 21:45 MST", which is 30 min early in
-- both seasons — 05:15 UTC is UTC-6 => 23:15 MDT and UTC-7 => 22:15 MST. The error mattered: the WINTER
-- 22:15 MST run is the hard ceiling on ops/cadence.yaml's cadence_watch_deadline_local, because
-- state.cadence_watch.needs_attention only alarms once Denver time passes that deadline. A reader trusting
-- the old "21:45 MST" figure would have mis-sized that ceiling by half an hour in the tightening direction.)
-- after D2/D3, like the freshness check. APPLY ORDER: bigquery/16_automation_health.sql must be applied
-- BEFORE re-pasting this query (it references state.backup_health + state.automation_heartbeat). See
-- ops/RUNBOOK.md "Scheduled queries". Also apply bigquery/34_alert_lifecycle.sql before re-pasting
-- (it defines ops.sp_auto_resolve_alerts, called below — self-improvement audit WP2, 2026-07-07), and
-- bigquery/38_run_log_selfheal.sql before re-pasting (it defines ops.sp_backfill_run_log_from_markers,
-- called FIRST below — RUNBOOK section 38 self-heal, ITEM 3). Also apply
-- bigquery/45_monitor_promotion.sql before re-pasting (it CREATEs ops.monitor_health_history, the
-- table this query's MERGE statements below target — 2026-07-14 audit finding: this dependency was
-- never listed here even though the MERGEs have needed it since it was added).
--
-- NOTE (repo vs live): this query's LIVE scheduled-query body still ran without the
-- sp_auto_resolve_alerts call as of this file's edit — the repo copy needs a console re-paste
-- (RUNBOOK "Scheduled queries" console procedure) to take effect. The routine-level wiring in
-- Claude_Task_Plan.md's Observability preamble (`CALL ops.sp_auto_resolve_alerts()` at the top of
-- every routine run) is the primary, already-live path; this scheduled-query call is defense in
-- depth for days with zero routine runs.
--
-- BODY FROZEN 2026-07-16: real body lives in ops.sp_sq_cadence_check (bigquery/75_scheduled_query_wrappers.sql);
-- edit THERE + CREATE OR REPLACE via the BigQuery MCP — this console body never changes again.
-- SQ_NAME: cadence_check
-- SQ_VERSION: (moved into the procedure — see bigquery/75_scheduled_query_wrappers.sql)
CALL `stock-trading-498512.ops.sp_sq_cadence_check`();
