-- SCHEDULED QUERY (P0-2): the dead-man's switch. Detects a silently-skipped D2
-- (stale marks/engine), unhealthy embeddings, firing kill flags, or open critical alerts.
--
-- NOTIFICATION (zero extra infra): this query RAISEs an error when the system is not
-- green, so BigQuery's built-in "Send email notifications on failure" toggle emails the
-- owner. It ALSO writes a durable ops.alerts row (idempotent — one open row per issue).
--
-- TIMING MATTERS: BigQuery schedules are UTC. Run at 05:00 UTC (= ~22:30 MDT / 21:30 MST) so it
-- lands in the Denver EVENING after D2 has ingested the close — NOT 21:30 UTC (= 15:30 MDT, before
-- D2, which would false-alarm every trading day). state.system_health compares marks/engine to the
-- last TRADING day (state.trading_day_today off CURRENT_DATE('America/Denver')), so it auto-
-- suppresses on weekends/holidays (last_trading_day is the prior close, already covered). See
-- ops/RUNBOOK.md "Scheduled queries".
--
-- BODY FROZEN 2026-07-16: real body lives in ops.sp_sq_daily_freshness_check (bigquery/75_scheduled_query_wrappers.sql);
-- edit THERE + CREATE OR REPLACE via the BigQuery MCP — this console body never changes again.
-- SQ_NAME: daily_freshness_check
-- SQ_VERSION: (moved into the procedure — see bigquery/75_scheduled_query_wrappers.sql)
CALL `stock-trading-498512.ops.sp_sq_daily_freshness_check`();
