-- SCHEDULED QUERY (2026-07-04 audit finding): wires up state.daily_staging_totals
-- (bigquery/23_trading_control.sql), which was computed but read by nothing — a per-order guard
-- (analytics.fn_order_guard) cannot stop a runaway session staging many small in-band orders; this is
-- that missing daily-aggregate backstop actually being checked.
--
-- POSTURE: RECORD-ONLY WARNING (no RAISE) — same staged-rollout posture as integrity_check.sql. A
-- breach means "review today's staging before crafting one more", not a proven hard failure of any one
-- order, so it should not flip all_green or storm the DTS failure-email until a clean baseline is
-- confirmed. Promote to critical + RAISE later if desired (cadence_check.sql's pattern).
--
-- RETIRED 2026-07-26 (owner directive): the daily_cap_breach warning this check raised is gone — no
-- daily cap on staged order count/notional applies anymore (bigquery/109_retire_daily_staging_cap.sql).
-- ops.sp_sq_daily_staging_cap_check (bigquery/75_scheduled_query_wrappers.sql, bumped to v4) now runs
-- only the order_guard_omitted / order_guard_verdict_mismatch per-order guard-record checks, which are
-- UNRELATED to the retired cap and remain fully active.
--
-- TIMING: any time during/after the trading day; ~05:25 UTC sits with the other daily control-plane
-- checks (after D2 has staged the day's orders). APPLY ORDER: bigquery/23_trading_control.sql must be
-- applied first.
--
-- BODY FROZEN 2026-07-16: real body lives in ops.sp_sq_daily_staging_cap_check (bigquery/75_scheduled_query_wrappers.sql);
-- edit THERE + CREATE OR REPLACE via the BigQuery MCP — this console body never changes again.
-- SQ_NAME: daily_staging_cap_check
-- SQ_VERSION: (moved into the procedure — see bigquery/75_scheduled_query_wrappers.sql)
CALL `stock-trading-498512.ops.sp_sq_daily_staging_cap_check`();
