-- SCHEDULED QUERY (P0-3): keep decision-log embeddings fresh with no active session.
-- ops.sp_embed_pending() is idempotent, self-healing, and costs pennies at the
-- ~1-entry/day cadence. Without this it only runs when a routine calls it.
--
-- Set up (BigQuery Studio -> Scheduled queries -> Create):
--   Schedule: daily ~06:00 UTC (BigQuery schedules are UTC; timing is irrelevant — idempotent)
--   Location: US     Project: stock-trading-498512
--   (No destination table.)  See ops/RUNBOOK.md "Scheduled queries".
--
-- BODY FROZEN 2026-07-16: real body lives in ops.sp_sq_embed_pending (bigquery/75_scheduled_query_wrappers.sql);
-- edit THERE + CREATE OR REPLACE via the BigQuery MCP — this console body never changes again.
-- SQ_NAME: embed_pending
-- SQ_VERSION: (moved into the procedure — see bigquery/75_scheduled_query_wrappers.sql)
CALL `stock-trading-498512.ops.sp_sq_embed_pending`();
