-- SCHEDULED QUERY (2026-06-28 stack review #2, #2): back up the ops.* control-plane / audit dataset to
-- GCS — the sibling of backup_events_export.sql. NO Cloud Run job, NO downloadable key.
--
-- WHY THIS EXISTS. backup_events_export.sql backs up events.* on the premise "everything else rebuilds
-- from events.*". That holds for state/perf/analytics (derived views) but NOT for ops.* base tables:
--   * ops.run_log         — the entire "what ran when" audit trail (no upstream)
--   * ops.alerts          — every raised/resolved alert + notified_ts (no upstream)
--   * ops.backup_log      — the backup markers the restore drill anchors on (no upstream)
--   * ops.heartbeat       — Apps Script liveness beats (no upstream)
--   * ops.account_snapshot — weekly NAV/TWR (softer: partially re-derivable from IBKR, but cheap to keep)
--   * ops.drill_log       — restore-drill liveness markers (no upstream)
-- The operating model permits out-of-band console/MCP mutation and only 7-day time-travel protects ops.*,
-- so an accidental ops drop would permanently erase the audit trail AND the DR anchor. This closes that
-- single-point-of-loss. Kept SEPARATE from the events export so an ops-export failure can never abort the
-- irreplaceable events.* backup.
--
-- Exports every BASE TABLE in `ops` to gs://stock-trading-backups/ops/<table>/dt=<date>/ as Snappy
-- Parquet (overwrite=true → same-day re-run idempotent; the bucket's >400d lifecycle ages snapshots out).
-- Skips ops.* objects that are NOT base tables (procedures, the text_embed/gemini remote models, views).
-- JSON columns (ops.alerts.payload) are emitted via TO_JSON_STRING — Parquet cannot serialize native JSON;
-- re-parse with PARSE_JSON on restore (same convention as the events export). Per-table isolation so one
-- failing table cannot abort the rest. On full success, logs an ops.backup_log marker with dataset='ops'
-- (state.ops_backup_health / cadence_check.sql detect a silently-stalled ops backup).
--
-- ONE-TIME SETUP (ops/RUNBOOK.md §3): create as a daily scheduled query (~05:35 UTC, after the events
-- export at ~05:30; Location US; no destination table), under the SAME identity as the events backup
-- (bq-scheduler@; it already holds roles/storage.objectAdmin on gs://stock-trading-backups). Enable
-- "Send email on failure". APPLY ORDER: bigquery/16_automation_health.sql (adds backup_log.dataset +
-- state.ops_backup_health) must be applied BEFORE creating this query.
--
-- Restore an ops table (JSON columns come back as STRING):
--   bq load --source_format=PARQUET --replace ops_restore.<table> \
--     'gs://stock-trading-backups/ops/<table>/dt=<YYYY-MM-DD>/*.parquet'
--   -- DDL-first (faithful) restore: see ops/RUNBOOK.md §3 "DDL-first restore".
--
-- BODY FROZEN 2026-07-16: real body lives in ops.sp_sq_ops_export (bigquery/75_scheduled_query_wrappers.sql);
-- edit THERE + CREATE OR REPLACE via the BigQuery MCP — this console body never changes again.
-- SQ_NAME: ops_export
-- SQ_VERSION: (moved into the procedure — see bigquery/75_scheduled_query_wrappers.sql)
CALL `stock-trading-498512.ops.sp_sq_ops_export`();
