-- SCHEDULED QUERY: monthly backup RESTORE drill (DR verification). CALLs ops.sp_restore_drill()
-- (bigquery/17_restore_drill.sql), which loads the latest logged backup snapshot (ops.backup_log.run_date)
-- of every events.* table into a throwaway scratch dataset, sanity-checks restored row counts vs live,
-- drops the scratch, and RAISEs on any table that fails to restore / restores empty (when live is
-- non-empty) / restores more rows than live. A backup you have never restored is a hope, not a backup;
-- this turns "we export Parquet" into "we have verified we can recover."
--
-- NOTIFICATION: RAISEs on failure so BigQuery's built-in "Send email notifications on failure" emails
-- the owner, AND writes a durable idempotent ops.alerts row (category 'restore_drill').
--
-- SELF-BOOTSTRAPPING: a no-op until the backup has logged its first ops.backup_log success marker.
--
-- SCHEDULE: monthly is plenty (e.g. 06:00 UTC on the 1st), Location US, no destination. APPLY ORDER:
-- bigquery/17_restore_drill.sql (the procedure) must be applied first.
--
-- IDENTITY / IAM (least privilege): runs as bq-scheduler@. It needs (a) roles/storage.objectViewer on
-- gs://stock-trading-backups (read the backups) and (b) roles/bigquery.dataEditor on the
-- events_restore_drill dataset ONLY (load the scratch tables). (b) + the pre-created scratch dataset are
-- already applied via SQL (see 17_restore_drill.sql one-time setup); (a) is GCS IAM (not SQL) and is the
-- ONE console grant still required — ops/RUNBOOK.md §3. Deliberately NOT project-level dataEditor:
-- bq-scheduler@ must never get write on the append-only events.* source of truth.
--
-- BODY FROZEN 2026-07-16: real body lives in ops.sp_sq_restore_drill (bigquery/75_scheduled_query_wrappers.sql);
-- edit THERE + CREATE OR REPLACE via the BigQuery MCP — this console body never changes again.
-- SQ_NAME: restore_drill
-- SQ_VERSION: (moved into the procedure — see bigquery/75_scheduled_query_wrappers.sql)
CALL `stock-trading-498512.ops.sp_sq_restore_drill`();
